// flow-typed signature: 33a30dc883ad283466d6f6f067cde6de
// flow-typed version: <<STUB>>/@turf/area_v3.5.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/area'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/area' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@turf/area/test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@turf/area/index' {
  declare module.exports: $Exports<'@turf/area'>;
}
declare module '@turf/area/index.js' {
  declare module.exports: $Exports<'@turf/area'>;
}
declare module '@turf/area/test.js' {
  declare module.exports: $Exports<'@turf/area/test'>;
}
