// flow-typed signature: 1842dac032af0aebf4cb86c8feb39c69
// flow-typed version: <<STUB>>/@turf/bbox_v^4.4.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/bbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/bbox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@turf/bbox/index' {
  declare module.exports: $Exports<'@turf/bbox'>;
}
declare module '@turf/bbox/index.js' {
  declare module.exports: $Exports<'@turf/bbox'>;
}
