// flow-typed signature: 125a9d3b72ed345aed11a80de1034a16
// flow-typed version: <<STUB>>/@turf/bbox-polygon_v^4.6.0/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/bbox-polygon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/bbox-polygon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@turf/bbox-polygon/index' {
  declare module.exports: $Exports<'@turf/bbox-polygon'>;
}
declare module '@turf/bbox-polygon/index.js' {
  declare module.exports: $Exports<'@turf/bbox-polygon'>;
}
