// flow-typed signature: 90664a6f953c2febfc50dfcf6e803b9b
// flow-typed version: <<STUB>>/@turf/bbox-polygon_v5.1.5/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/bbox-polygon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/bbox-polygon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@turf/bbox-polygon/main.es' {
  declare module.exports: any;
}

declare module '@turf/bbox-polygon/main' {
  declare module.exports: any;
}

// Filename aliases
declare module '@turf/bbox-polygon/index' {
  declare module.exports: $Exports<'@turf/bbox-polygon'>;
}
declare module '@turf/bbox-polygon/index.js' {
  declare module.exports: $Exports<'@turf/bbox-polygon'>;
}
declare module '@turf/bbox-polygon/main.es.js' {
  declare module.exports: $Exports<'@turf/bbox-polygon/main.es'>;
}
declare module '@turf/bbox-polygon/main.js' {
  declare module.exports: $Exports<'@turf/bbox-polygon/main'>;
}
