// flow-typed signature: a4ed415844e33eb9b605c510c3795b8e
// flow-typed version: <<STUB>>/@turf/bbox_v3.6.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/bbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/bbox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@turf/bbox/test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@turf/bbox/index' {
  declare module.exports: $Exports<'@turf/bbox'>;
}
declare module '@turf/bbox/index.js' {
  declare module.exports: $Exports<'@turf/bbox'>;
}
declare module '@turf/bbox/test.js' {
  declare module.exports: $Exports<'@turf/bbox/test'>;
}
