// flow-typed signature: 46b537e8395db6f483a8144b88445d9b
// flow-typed version: <<STUB>>/@turf/buffer_v^4.4.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/buffer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/buffer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@turf/buffer/index' {
  declare module.exports: $Exports<'@turf/buffer'>;
}
declare module '@turf/buffer/index.js' {
  declare module.exports: $Exports<'@turf/buffer'>;
}
