// flow-typed signature: 4705e1c28eab0beb33fe84ecfd31654b
// flow-typed version: <<STUB>>/@turf/buffer_v^5.0.4/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/buffer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/buffer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@turf/buffer/main.es' {
  declare module.exports: any;
}

declare module '@turf/buffer/main' {
  declare module.exports: any;
}

// Filename aliases
declare module '@turf/buffer/index' {
  declare module.exports: $Exports<'@turf/buffer'>;
}
declare module '@turf/buffer/index.js' {
  declare module.exports: $Exports<'@turf/buffer'>;
}
declare module '@turf/buffer/main.es.js' {
  declare module.exports: $Exports<'@turf/buffer/main.es'>;
}
declare module '@turf/buffer/main.js' {
  declare module.exports: $Exports<'@turf/buffer/main'>;
}
