// flow-typed signature: df45a162a4141045724e6e30abcfd194
// flow-typed version: <<STUB>>/@turf/centroid_v^4.6.1/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/centroid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/centroid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@turf/centroid/index' {
  declare module.exports: $Exports<'@turf/centroid'>;
}
declare module '@turf/centroid/index.js' {
  declare module.exports: $Exports<'@turf/centroid'>;
}
