// flow-typed signature: 7bf123575560fef3c31dc51413f10cf0
// flow-typed version: <<STUB>>/@turf/centroid_v3.6.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/centroid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/centroid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@turf/centroid/bench' {
  declare module.exports: any;
}

declare module '@turf/centroid/test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@turf/centroid/bench.js' {
  declare module.exports: $Exports<'@turf/centroid/bench'>;
}
declare module '@turf/centroid/index' {
  declare module.exports: $Exports<'@turf/centroid'>;
}
declare module '@turf/centroid/index.js' {
  declare module.exports: $Exports<'@turf/centroid'>;
}
declare module '@turf/centroid/test.js' {
  declare module.exports: $Exports<'@turf/centroid/test'>;
}
