// flow-typed signature: 4af4a188290052b05a4240804b30c2f9
// flow-typed version: <<STUB>>/@turf/centroid_v5.1.5/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/centroid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/centroid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@turf/centroid/main.es' {
  declare module.exports: any;
}

declare module '@turf/centroid/main' {
  declare module.exports: any;
}

// Filename aliases
declare module '@turf/centroid/index' {
  declare module.exports: $Exports<'@turf/centroid'>;
}
declare module '@turf/centroid/index.js' {
  declare module.exports: $Exports<'@turf/centroid'>;
}
declare module '@turf/centroid/main.es.js' {
  declare module.exports: $Exports<'@turf/centroid/main.es'>;
}
declare module '@turf/centroid/main.js' {
  declare module.exports: $Exports<'@turf/centroid/main'>;
}
