// flow-typed signature: be0156750534d113efcc8e19725b88c4
// flow-typed version: <<STUB>>/@turf/distance_v5.1.5/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/distance'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/distance' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@turf/distance/main.es' {
  declare module.exports: any;
}

declare module '@turf/distance/main' {
  declare module.exports: any;
}

// Filename aliases
declare module '@turf/distance/index' {
  declare module.exports: $Exports<'@turf/distance'>;
}
declare module '@turf/distance/index.js' {
  declare module.exports: $Exports<'@turf/distance'>;
}
declare module '@turf/distance/main.es.js' {
  declare module.exports: $Exports<'@turf/distance/main.es'>;
}
declare module '@turf/distance/main.js' {
  declare module.exports: $Exports<'@turf/distance/main'>;
}
