// flow-typed signature: a59a788cf6ae56d0fe9dd33f88ae6383
// flow-typed version: <<STUB>>/@turf/distance_v^4.4.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/distance'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/distance' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@turf/distance/index' {
  declare module.exports: $Exports<'@turf/distance'>;
}
declare module '@turf/distance/index.js' {
  declare module.exports: $Exports<'@turf/distance'>;
}
