// flow-typed signature: b0d99ad62c916faa65f2c344c0535dd9
// flow-typed version: <<STUB>>/@turf/helpers_v5.1.5/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/helpers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/helpers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@turf/helpers/main.es' {
  declare module.exports: any;
}

declare module '@turf/helpers/main' {
  declare module.exports: any;
}

// Filename aliases
declare module '@turf/helpers/index' {
  declare module.exports: $Exports<'@turf/helpers'>;
}
declare module '@turf/helpers/index.js' {
  declare module.exports: $Exports<'@turf/helpers'>;
}
declare module '@turf/helpers/main.es.js' {
  declare module.exports: $Exports<'@turf/helpers/main.es'>;
}
declare module '@turf/helpers/main.js' {
  declare module.exports: $Exports<'@turf/helpers/main'>;
}
