// flow-typed signature: 428ff6bda3689ff05688a01c4e6f2189
// flow-typed version: <<STUB>>/@turf/inside_v^4.4.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/inside'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/inside' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@turf/inside/index' {
  declare module.exports: $Exports<'@turf/inside'>;
}
declare module '@turf/inside/index.js' {
  declare module.exports: $Exports<'@turf/inside'>;
}
