// flow-typed signature: 37b1d8c3539aab1ae8b34ab98b4e485b
// flow-typed version: <<STUB>>/@turf/intersect_v^4.6.0/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/intersect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/intersect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@turf/intersect/index' {
  declare module.exports: $Exports<'@turf/intersect'>;
}
declare module '@turf/intersect/index.js' {
  declare module.exports: $Exports<'@turf/intersect'>;
}
