// flow-typed signature: fdd7d44c8101cb907d865bd5b088dcc3
// flow-typed version: <<STUB>>/@turf/intersect_v^5.0.4/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/intersect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/intersect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@turf/intersect/main.es' {
  declare module.exports: any;
}

declare module '@turf/intersect/main' {
  declare module.exports: any;
}

// Filename aliases
declare module '@turf/intersect/index' {
  declare module.exports: $Exports<'@turf/intersect'>;
}
declare module '@turf/intersect/index.js' {
  declare module.exports: $Exports<'@turf/intersect'>;
}
declare module '@turf/intersect/main.es.js' {
  declare module.exports: $Exports<'@turf/intersect/main.es'>;
}
declare module '@turf/intersect/main.js' {
  declare module.exports: $Exports<'@turf/intersect/main'>;
}
