// flow-typed signature: 5e2dc1f3c28f7decada5c33334eae44a
// flow-typed version: <<STUB>>/@turf/length_v^5.1.5/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/length'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/length' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@turf/length/main.es' {
  declare module.exports: any;
}

declare module '@turf/length/main' {
  declare module.exports: any;
}

// Filename aliases
declare module '@turf/length/index' {
  declare module.exports: $Exports<'@turf/length'>;
}
declare module '@turf/length/index.js' {
  declare module.exports: $Exports<'@turf/length'>;
}
declare module '@turf/length/main.es.js' {
  declare module.exports: $Exports<'@turf/length/main.es'>;
}
declare module '@turf/length/main.js' {
  declare module.exports: $Exports<'@turf/length/main'>;
}
