// flow-typed signature: d70c8cae077486ccc4703723eb0d722d
// flow-typed version: <<STUB>>/@turf/line-distance_v^4.7.3/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@turf/line-distance'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@turf/line-distance' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@turf/line-distance/index' {
  declare module.exports: $Exports<'@turf/line-distance'>;
}
declare module '@turf/line-distance/index.js' {
  declare module.exports: $Exports<'@turf/line-distance'>;
}
