FROM nginx:alpine

#MapHubs Static Assets
MAINTAINER Kristofor Carle - MapHubs <kris@maphubs.com>

RUN apk add --update git && mkdir -p /data

WORKDIR /data

#install iD
RUN git clone -b maphubs-dev --single-branch https://github.com/openmaphub/iD.git

COPY ./assets /data/assets
COPY ./public /data/public

COPY ./env/maphubsnginx_assets.template /etc/nginx/nginx.conf

CMD  ["nginx", "-g", "'daemon off;'"]