import Reflux from 'reflux';
export default Reflux.createActions([
  'setSearchLayers',
  'setMapLayers',
  'setMapId',
  'setStoryId',
  'setHubId',
  'search',
  'addToMap',
  'removeFromMap',
  'updateLayerStyle',
  'setMapTitle',
  'setMapPosition',
  'setMapBasemap',
  'setPrivate',
  'savePrivate',
  'setOwnedByGroupId',
  'saveMap',
  'createMap',
  'toggleVisibility',
  'reset',
  'deleteMap',
  'startEditing',
  'stopEditing',
  'setSettings',
  'setPublic'
]);