import Rehydrate from 'reflux-rehydrate';
export default Rehydrate.createActions([
  'setSearchLayers',
  'setMapLayers',
  'setMapId',
  'setStoryId',
  'setHubId',
  'search',
  'addToMap',
  'removeFromMap',
  'updateLayerStyle',
  'setMapTitle',
  'setMapPosition',
  'setMapBasemap',
  'setPrivate',
  'savePrivate',
  'setOwnedByGroupId',
  'saveMap',
  'createMap',
  'toggleVisibility',
  'reset',
  'deleteMap',
  'startEditing',
  'stopEditing'
]);