// flow-typed signature: ea2a063153906fb69b3d9c90e1d88c68
// flow-typed version: <<STUB>>/babel-plugin-stylus-compiler_v^1.4.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-stylus-compiler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-stylus-compiler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-stylus-compiler/build/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-stylus-compiler/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-stylus-compiler/build/index.js' {
  declare module.exports: $Exports<'babel-plugin-stylus-compiler/build/index'>;
}
declare module 'babel-plugin-stylus-compiler/src/index.js' {
  declare module.exports: $Exports<'babel-plugin-stylus-compiler/src/index'>;
}
