// flow-typed signature: 6c8e743ed3b8222c75092f6a95ba5528
// flow-typed version: <<STUB>>/babel-plugin-transform-css-import-to-string_v^0.0.2/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-css-import-to-string'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-css-import-to-string' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-css-import-to-string/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-css-import-to-string/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-css-import-to-string/lib/index'>;
}
