// flow-typed signature: 1ec4eedf931524089682eaa751822626
// flow-typed version: <<STUB>>/babel-plugin-version-inline_v^1.0.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-version-inline'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-version-inline' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-version-inline/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-version-inline/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-version-inline/lib/index'>;
}
