// flow-typed signature: bf5178a58cb3f15af7a1ab178f11f712
// flow-typed version: <<STUB>>/clipboard-polyfill_v^2.4.6/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clipboard-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'clipboard-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'clipboard-polyfill/build/clipboard-polyfill' {
  declare module.exports: any;
}

declare module 'clipboard-polyfill/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'clipboard-polyfill/build/clipboard-polyfill.js' {
  declare module.exports: $Exports<'clipboard-polyfill/build/clipboard-polyfill'>;
}
declare module 'clipboard-polyfill/webpack.config.js' {
  declare module.exports: $Exports<'clipboard-polyfill/webpack.config'>;
}
