// flow-typed signature: e91c92f6b96be5fa54bc7857259eb2b6
// flow-typed version: <<STUB>>/clipboard-js_v^0.3.5/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clipboard-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'clipboard-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'clipboard-js/clipboard' {
  declare module.exports: any;
}

declare module 'clipboard-js/clipboard.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'clipboard-js/clipboard.js' {
  declare module.exports: $Exports<'clipboard-js/clipboard'>;
}
declare module 'clipboard-js/clipboard.min.js' {
  declare module.exports: $Exports<'clipboard-js/clipboard.min'>;
}
