// flow-typed signature: 7250cc6c6740ecc50a45766c09db39fd
// flow-typed version: <<STUB>>/connect-session-knex_v1.3.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'connect-session-knex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'connect-session-knex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'connect-session-knex/index' {
  declare module.exports: $Exports<'connect-session-knex'>;
}
declare module 'connect-session-knex/index.js' {
  declare module.exports: $Exports<'connect-session-knex'>;
}
