// flow-typed signature: ecce27d3015b4f7cd75459fc9845689d
// flow-typed version: <<STUB>>/connect-session-knex_v^1.3.4/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'connect-session-knex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'connect-session-knex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'connect-session-knex/index' {
  declare module.exports: $Exports<'connect-session-knex'>;
}
declare module 'connect-session-knex/index.js' {
  declare module.exports: $Exports<'connect-session-knex'>;
}
