// flow-typed signature: e2901b2fbb8eb015c1e31ed1aa44d6c6
// flow-typed version: <<STUB>>/consign_v^0.1.6/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'consign'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'consign' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'consign/lib/consign' {
  declare module.exports: any;
}

// Filename aliases
declare module 'consign/index' {
  declare module.exports: $Exports<'consign'>;
}
declare module 'consign/index.js' {
  declare module.exports: $Exports<'consign'>;
}
declare module 'consign/lib/consign.js' {
  declare module.exports: $Exports<'consign/lib/consign'>;
}
