// flow-typed signature: 4d7a0e8b8745f7283f8126e1d327a36f
// flow-typed version: <<STUB>>/csurf_v1.9.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'csurf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'csurf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'csurf/index' {
  declare module.exports: $Exports<'csurf'>;
}
declare module 'csurf/index.js' {
  declare module.exports: $Exports<'csurf'>;
}
