// flow-typed signature: cc3b1e1bf6e95d46691b358782b4d85e
// flow-typed version: <<STUB>>/csv2geojson_v5.0.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'csv2geojson'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'csv2geojson' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'csv2geojson/csv2geojson' {
  declare module.exports: any;
}

// Filename aliases
declare module 'csv2geojson/csv2geojson.js' {
  declare module.exports: $Exports<'csv2geojson/csv2geojson'>;
}
declare module 'csv2geojson/index' {
  declare module.exports: $Exports<'csv2geojson'>;
}
declare module 'csv2geojson/index.js' {
  declare module.exports: $Exports<'csv2geojson'>;
}
