// flow-typed signature: 5c3f84b4b8d986314ba8ade605a81418
// flow-typed version: <<STUB>>/dbgeo_v^1.1.0/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dbgeo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dbgeo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dbgeo/lib/dbgeo' {
  declare module.exports: any;
}

declare module 'dbgeo/test/benchmark' {
  declare module.exports: any;
}

declare module 'dbgeo/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dbgeo/index' {
  declare module.exports: $Exports<'dbgeo'>;
}
declare module 'dbgeo/index.js' {
  declare module.exports: $Exports<'dbgeo'>;
}
declare module 'dbgeo/lib/dbgeo.js' {
  declare module.exports: $Exports<'dbgeo/lib/dbgeo'>;
}
declare module 'dbgeo/test/benchmark.js' {
  declare module.exports: $Exports<'dbgeo/test/benchmark'>;
}
declare module 'dbgeo/test/test.js' {
  declare module.exports: $Exports<'dbgeo/test/test'>;
}
