// flow-typed signature: 2f0a453ada989bcb11c27b4c74d2a69d
// flow-typed version: <<STUB>>/dms2dec_v1.1.0/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dms2dec'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dms2dec' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dms2dec/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dms2dec/index' {
  declare module.exports: $Exports<'dms2dec'>;
}
declare module 'dms2dec/index.js' {
  declare module.exports: $Exports<'dms2dec'>;
}
declare module 'dms2dec/test.js' {
  declare module.exports: $Exports<'dms2dec/test'>;
}
