// flow-typed signature: 375eb393f2bca9becc8944da5aa40fcf
// flow-typed version: <<STUB>>/easyimage_v2.1.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'easyimage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'easyimage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'easyimage/easyimage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'easyimage/easyimage.js' {
  declare module.exports: $Exports<'easyimage/easyimage'>;
}
