// flow-typed signature: a33481004feabfa7422cb17fe028c1f5
// flow-typed version: <<STUB>>/exif-js_v2.3.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'exif-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'exif-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'exif-js/exif' {
  declare module.exports: any;
}

// Filename aliases
declare module 'exif-js/exif.js' {
  declare module.exports: $Exports<'exif-js/exif'>;
}
