// flow-typed signature: c083f2f3d758683c18243718d06ae0d0
// flow-typed version: <<STUB>>/express-http-proxy_v^1.0.6/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-http-proxy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-http-proxy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-http-proxy/app/steps/buildProxyReq' {
  declare module.exports: any;
}

declare module 'express-http-proxy/app/steps/copyProxyResHeadersToUserRes' {
  declare module.exports: any;
}

declare module 'express-http-proxy/app/steps/decorateProxyReqBody' {
  declare module.exports: any;
}

declare module 'express-http-proxy/app/steps/decorateProxyReqOpts' {
  declare module.exports: any;
}

declare module 'express-http-proxy/app/steps/decorateUserRes' {
  declare module.exports: any;
}

declare module 'express-http-proxy/app/steps/decorateUserResHeaders' {
  declare module.exports: any;
}

declare module 'express-http-proxy/app/steps/maybeSkipToNextHandler' {
  declare module.exports: any;
}

declare module 'express-http-proxy/app/steps/prepareProxyReq' {
  declare module.exports: any;
}

declare module 'express-http-proxy/app/steps/resolveProxyHost' {
  declare module.exports: any;
}

declare module 'express-http-proxy/app/steps/resolveProxyReqPath' {
  declare module.exports: any;
}

declare module 'express-http-proxy/app/steps/sendProxyRequest' {
  declare module.exports: any;
}

declare module 'express-http-proxy/app/steps/sendUserRes' {
  declare module.exports: any;
}

declare module 'express-http-proxy/lib/as' {
  declare module.exports: any;
}

declare module 'express-http-proxy/lib/chunkLength' {
  declare module.exports: any;
}

declare module 'express-http-proxy/lib/isUnset' {
  declare module.exports: any;
}

declare module 'express-http-proxy/lib/mockHTTP' {
  declare module.exports: any;
}

declare module 'express-http-proxy/lib/requestOptions' {
  declare module.exports: any;
}

declare module 'express-http-proxy/lib/resolveOptions' {
  declare module.exports: any;
}

declare module 'express-http-proxy/lib/scopeContainer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-http-proxy/app/steps/buildProxyReq.js' {
  declare module.exports: $Exports<'express-http-proxy/app/steps/buildProxyReq'>;
}
declare module 'express-http-proxy/app/steps/copyProxyResHeadersToUserRes.js' {
  declare module.exports: $Exports<'express-http-proxy/app/steps/copyProxyResHeadersToUserRes'>;
}
declare module 'express-http-proxy/app/steps/decorateProxyReqBody.js' {
  declare module.exports: $Exports<'express-http-proxy/app/steps/decorateProxyReqBody'>;
}
declare module 'express-http-proxy/app/steps/decorateProxyReqOpts.js' {
  declare module.exports: $Exports<'express-http-proxy/app/steps/decorateProxyReqOpts'>;
}
declare module 'express-http-proxy/app/steps/decorateUserRes.js' {
  declare module.exports: $Exports<'express-http-proxy/app/steps/decorateUserRes'>;
}
declare module 'express-http-proxy/app/steps/decorateUserResHeaders.js' {
  declare module.exports: $Exports<'express-http-proxy/app/steps/decorateUserResHeaders'>;
}
declare module 'express-http-proxy/app/steps/maybeSkipToNextHandler.js' {
  declare module.exports: $Exports<'express-http-proxy/app/steps/maybeSkipToNextHandler'>;
}
declare module 'express-http-proxy/app/steps/prepareProxyReq.js' {
  declare module.exports: $Exports<'express-http-proxy/app/steps/prepareProxyReq'>;
}
declare module 'express-http-proxy/app/steps/resolveProxyHost.js' {
  declare module.exports: $Exports<'express-http-proxy/app/steps/resolveProxyHost'>;
}
declare module 'express-http-proxy/app/steps/resolveProxyReqPath.js' {
  declare module.exports: $Exports<'express-http-proxy/app/steps/resolveProxyReqPath'>;
}
declare module 'express-http-proxy/app/steps/sendProxyRequest.js' {
  declare module.exports: $Exports<'express-http-proxy/app/steps/sendProxyRequest'>;
}
declare module 'express-http-proxy/app/steps/sendUserRes.js' {
  declare module.exports: $Exports<'express-http-proxy/app/steps/sendUserRes'>;
}
declare module 'express-http-proxy/index' {
  declare module.exports: $Exports<'express-http-proxy'>;
}
declare module 'express-http-proxy/index.js' {
  declare module.exports: $Exports<'express-http-proxy'>;
}
declare module 'express-http-proxy/lib/as.js' {
  declare module.exports: $Exports<'express-http-proxy/lib/as'>;
}
declare module 'express-http-proxy/lib/chunkLength.js' {
  declare module.exports: $Exports<'express-http-proxy/lib/chunkLength'>;
}
declare module 'express-http-proxy/lib/isUnset.js' {
  declare module.exports: $Exports<'express-http-proxy/lib/isUnset'>;
}
declare module 'express-http-proxy/lib/mockHTTP.js' {
  declare module.exports: $Exports<'express-http-proxy/lib/mockHTTP'>;
}
declare module 'express-http-proxy/lib/requestOptions.js' {
  declare module.exports: $Exports<'express-http-proxy/lib/requestOptions'>;
}
declare module 'express-http-proxy/lib/resolveOptions.js' {
  declare module.exports: $Exports<'express-http-proxy/lib/resolveOptions'>;
}
declare module 'express-http-proxy/lib/scopeContainer.js' {
  declare module.exports: $Exports<'express-http-proxy/lib/scopeContainer'>;
}
