// flow-typed signature: c3cbbe4afc9fb63e0dfcea47f50547b4
// flow-typed version: <<STUB>>/express-load_v^1.1.16/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-load'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-load' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-load/lib/express-load' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-load/index' {
  declare module.exports: $Exports<'express-load'>;
}
declare module 'express-load/index.js' {
  declare module.exports: $Exports<'express-load'>;
}
declare module 'express-load/lib/express-load.js' {
  declare module.exports: $Exports<'express-load/lib/express-load'>;
}
