// flow-typed signature: 10323cbb11fab89838d03b5c5eb8b87e
// flow-typed version: <<STUB>>/express-remove-route_v0.1.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-remove-route'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-remove-route' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'express-remove-route/index' {
  declare module.exports: $Exports<'express-remove-route'>;
}
declare module 'express-remove-route/index.js' {
  declare module.exports: $Exports<'express-remove-route'>;
}
