// flow-typed signature: c086405e41135dd974a2d97e0e1d63f6
// flow-typed version: <<STUB>>/express-xml-bodyparser_v0.3.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-xml-bodyparser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-xml-bodyparser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-xml-bodyparser/lib/types/xml' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-xml-bodyparser/index' {
  declare module.exports: $Exports<'express-xml-bodyparser'>;
}
declare module 'express-xml-bodyparser/index.js' {
  declare module.exports: $Exports<'express-xml-bodyparser'>;
}
declare module 'express-xml-bodyparser/lib/types/xml.js' {
  declare module.exports: $Exports<'express-xml-bodyparser/lib/types/xml'>;
}
