// flow-typed signature: 8c04446acd1a75bf24d6ec9d536e02c1
// flow-typed version: <<STUB>>/express-sharp_v^2.1.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-sharp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-sharp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-sharp/lib/image-url' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-sharp/index' {
  declare module.exports: $Exports<'express-sharp'>;
}
declare module 'express-sharp/index.js' {
  declare module.exports: $Exports<'express-sharp'>;
}
declare module 'express-sharp/lib/image-url.js' {
  declare module.exports: $Exports<'express-sharp/lib/image-url'>;
}
