// flow-typed signature: aee3c2ce26064b8307f4a91a69bdd154
// flow-typed version: <<STUB>>/formsy-react_v1.1.4/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'formsy-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'formsy-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'formsy-react/lib/index' {
  declare module.exports: any;
}

declare module 'formsy-react/lib/utils' {
  declare module.exports: any;
}

declare module 'formsy-react/lib/validationRules' {
  declare module.exports: any;
}

declare module 'formsy-react/lib/Wrapper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'formsy-react/lib/index.js' {
  declare module.exports: $Exports<'formsy-react/lib/index'>;
}
declare module 'formsy-react/lib/utils.js' {
  declare module.exports: $Exports<'formsy-react/lib/utils'>;
}
declare module 'formsy-react/lib/validationRules.js' {
  declare module.exports: $Exports<'formsy-react/lib/validationRules'>;
}
declare module 'formsy-react/lib/Wrapper.js' {
  declare module.exports: $Exports<'formsy-react/lib/Wrapper'>;
}
