// flow-typed signature: 4aa44b56fcfbf934733f8f594b11ebed
// flow-typed version: <<STUB>>/geobuf_v^3.0.0/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'geobuf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'geobuf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'geobuf/decode' {
  declare module.exports: any;
}

declare module 'geobuf/dist/geobuf-dev' {
  declare module.exports: any;
}

declare module 'geobuf/dist/geobuf' {
  declare module.exports: any;
}

declare module 'geobuf/encode' {
  declare module.exports: any;
}

// Filename aliases
declare module 'geobuf/decode.js' {
  declare module.exports: $Exports<'geobuf/decode'>;
}
declare module 'geobuf/dist/geobuf-dev.js' {
  declare module.exports: $Exports<'geobuf/dist/geobuf-dev'>;
}
declare module 'geobuf/dist/geobuf.js' {
  declare module.exports: $Exports<'geobuf/dist/geobuf'>;
}
declare module 'geobuf/encode.js' {
  declare module.exports: $Exports<'geobuf/encode'>;
}
declare module 'geobuf/index' {
  declare module.exports: $Exports<'geobuf'>;
}
declare module 'geobuf/index.js' {
  declare module.exports: $Exports<'geobuf'>;
}
