// flow-typed signature: 998104024182b2c9a90f24cc34521e81
// flow-typed version: <<STUB>>/geojson2dsv_v^0.1.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'geojson2dsv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'geojson2dsv' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'geojson2dsv/index' {
  declare module.exports: $Exports<'geojson2dsv'>;
}
declare module 'geojson2dsv/index.js' {
  declare module.exports: $Exports<'geojson2dsv'>;
}
