// flow-typed signature: d1f5626fe9f93674358f9dd0cce60e4e
// flow-typed version: <<STUB>>/geojson-flow_v^1.0.1/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'geojson-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'geojson-flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'geojson-flow/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'geojson-flow/types.js' {
  declare module.exports: $Exports<'geojson-flow/types'>;
}
