// flow-typed signature: 722edf914d284cbc7bb1433ddec38c37
// flow-typed version: <<STUB>>/geojson-validation_v0.1.6/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'geojson-validation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'geojson-validation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'geojson-validation/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'geojson-validation/index' {
  declare module.exports: $Exports<'geojson-validation'>;
}
declare module 'geojson-validation/index.js' {
  declare module.exports: $Exports<'geojson-validation'>;
}
declare module 'geojson-validation/test/index.js' {
  declare module.exports: $Exports<'geojson-validation/test/index'>;
}
