// flow-typed signature: 0a355e49de579b27cee37fb8a707aad9
// flow-typed version: <<STUB>>/getenv_v0.7.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'getenv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'getenv' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'getenv/lib/getenv' {
  declare module.exports: any;
}

// Filename aliases
declare module 'getenv/index' {
  declare module.exports: $Exports<'getenv'>;
}
declare module 'getenv/index.js' {
  declare module.exports: $Exports<'getenv'>;
}
declare module 'getenv/lib/getenv.js' {
  declare module.exports: $Exports<'getenv/lib/getenv'>;
}
