// flow-typed signature: 4ed42941d60b8f473376d539fe2925e4
// flow-typed version: <<STUB>>/griddle-react_v0.6.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'griddle-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'griddle-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'griddle-react/build/Griddle' {
  declare module.exports: any;
}

declare module 'griddle-react/karma.conf' {
  declare module.exports: any;
}

declare module 'griddle-react/modules/columnProperties' {
  declare module.exports: any;
}

declare module 'griddle-react/modules/customFilterContainer.jsx' {
  declare module.exports: any;
}

declare module 'griddle-react/modules/customPaginationContainer.jsx' {
  declare module.exports: any;
}

declare module 'griddle-react/modules/customRowComponentContainer.jsx' {
  declare module.exports: any;
}

declare module 'griddle-react/modules/deep' {
  declare module.exports: any;
}

declare module 'griddle-react/modules/griddle.jsx' {
  declare module.exports: any;
}

declare module 'griddle-react/modules/gridFilter.jsx' {
  declare module.exports: any;
}

declare module 'griddle-react/modules/gridNoData.jsx' {
  declare module.exports: any;
}

declare module 'griddle-react/modules/gridPagination.jsx' {
  declare module.exports: any;
}

declare module 'griddle-react/modules/gridRow.jsx' {
  declare module.exports: any;
}

declare module 'griddle-react/modules/gridRowContainer.jsx' {
  declare module.exports: any;
}

declare module 'griddle-react/modules/gridSettings.jsx' {
  declare module.exports: any;
}

declare module 'griddle-react/modules/gridTable.jsx' {
  declare module.exports: any;
}

declare module 'griddle-react/modules/gridTitle.jsx' {
  declare module.exports: any;
}

declare module 'griddle-react/modules/rowProperties' {
  declare module.exports: any;
}

// Filename aliases
declare module 'griddle-react/build/Griddle.js' {
  declare module.exports: $Exports<'griddle-react/build/Griddle'>;
}
declare module 'griddle-react/karma.conf.js' {
  declare module.exports: $Exports<'griddle-react/karma.conf'>;
}
declare module 'griddle-react/modules/columnProperties.js' {
  declare module.exports: $Exports<'griddle-react/modules/columnProperties'>;
}
declare module 'griddle-react/modules/customFilterContainer.jsx.js' {
  declare module.exports: $Exports<'griddle-react/modules/customFilterContainer.jsx'>;
}
declare module 'griddle-react/modules/customPaginationContainer.jsx.js' {
  declare module.exports: $Exports<'griddle-react/modules/customPaginationContainer.jsx'>;
}
declare module 'griddle-react/modules/customRowComponentContainer.jsx.js' {
  declare module.exports: $Exports<'griddle-react/modules/customRowComponentContainer.jsx'>;
}
declare module 'griddle-react/modules/deep.js' {
  declare module.exports: $Exports<'griddle-react/modules/deep'>;
}
declare module 'griddle-react/modules/griddle.jsx.js' {
  declare module.exports: $Exports<'griddle-react/modules/griddle.jsx'>;
}
declare module 'griddle-react/modules/gridFilter.jsx.js' {
  declare module.exports: $Exports<'griddle-react/modules/gridFilter.jsx'>;
}
declare module 'griddle-react/modules/gridNoData.jsx.js' {
  declare module.exports: $Exports<'griddle-react/modules/gridNoData.jsx'>;
}
declare module 'griddle-react/modules/gridPagination.jsx.js' {
  declare module.exports: $Exports<'griddle-react/modules/gridPagination.jsx'>;
}
declare module 'griddle-react/modules/gridRow.jsx.js' {
  declare module.exports: $Exports<'griddle-react/modules/gridRow.jsx'>;
}
declare module 'griddle-react/modules/gridRowContainer.jsx.js' {
  declare module.exports: $Exports<'griddle-react/modules/gridRowContainer.jsx'>;
}
declare module 'griddle-react/modules/gridSettings.jsx.js' {
  declare module.exports: $Exports<'griddle-react/modules/gridSettings.jsx'>;
}
declare module 'griddle-react/modules/gridTable.jsx.js' {
  declare module.exports: $Exports<'griddle-react/modules/gridTable.jsx'>;
}
declare module 'griddle-react/modules/gridTitle.jsx.js' {
  declare module.exports: $Exports<'griddle-react/modules/gridTitle.jsx'>;
}
declare module 'griddle-react/modules/rowProperties.js' {
  declare module.exports: $Exports<'griddle-react/modules/rowProperties'>;
}
