// flow-typed signature: 118563d8ca88af9fe0278fea01e7d4f7
// flow-typed version: <<STUB>>/i18n_v0.8.3/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'i18n'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'i18n' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'i18n/i18n' {
  declare module.exports: any;
}

// Filename aliases
declare module 'i18n/i18n.js' {
  declare module.exports: $Exports<'i18n/i18n'>;
}
declare module 'i18n/index' {
  declare module.exports: $Exports<'i18n'>;
}
declare module 'i18n/index.js' {
  declare module.exports: $Exports<'i18n'>;
}
