// flow-typed signature: 34eb8adaf7902e40bc9c18f60a39a033
// flow-typed version: <<STUB>>/libxmljs_v0.18.7/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'libxmljs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'libxmljs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'libxmljs/lib/bindings' {
  declare module.exports: any;
}

declare module 'libxmljs/lib/comment' {
  declare module.exports: any;
}

declare module 'libxmljs/lib/document' {
  declare module.exports: any;
}

declare module 'libxmljs/lib/element' {
  declare module.exports: any;
}

declare module 'libxmljs/lib/sax_parser' {
  declare module.exports: any;
}

declare module 'libxmljs/lib/text' {
  declare module.exports: any;
}

// Filename aliases
declare module 'libxmljs/index' {
  declare module.exports: $Exports<'libxmljs'>;
}
declare module 'libxmljs/index.js' {
  declare module.exports: $Exports<'libxmljs'>;
}
declare module 'libxmljs/lib/bindings.js' {
  declare module.exports: $Exports<'libxmljs/lib/bindings'>;
}
declare module 'libxmljs/lib/comment.js' {
  declare module.exports: $Exports<'libxmljs/lib/comment'>;
}
declare module 'libxmljs/lib/document.js' {
  declare module.exports: $Exports<'libxmljs/lib/document'>;
}
declare module 'libxmljs/lib/element.js' {
  declare module.exports: $Exports<'libxmljs/lib/element'>;
}
declare module 'libxmljs/lib/sax_parser.js' {
  declare module.exports: $Exports<'libxmljs/lib/sax_parser'>;
}
declare module 'libxmljs/lib/text.js' {
  declare module.exports: $Exports<'libxmljs/lib/text'>;
}
