// flow-typed signature: 700838bf3a2a4c76e8421c47f1bca3c0
// flow-typed version: <<STUB>>/libxmljs_v0.18.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'libxmljs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'libxmljs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'libxmljs/examples/cdata' {
  declare module.exports: any;
}

declare module 'libxmljs/lib/bindings' {
  declare module.exports: any;
}

declare module 'libxmljs/lib/comment' {
  declare module.exports: any;
}

declare module 'libxmljs/lib/document' {
  declare module.exports: any;
}

declare module 'libxmljs/lib/element' {
  declare module.exports: any;
}

declare module 'libxmljs/lib/sax_parser' {
  declare module.exports: any;
}

declare module 'libxmljs/lib/text' {
  declare module.exports: any;
}

declare module 'libxmljs/test/attribute' {
  declare module.exports: any;
}

declare module 'libxmljs/test/comment' {
  declare module.exports: any;
}

declare module 'libxmljs/test/document' {
  declare module.exports: any;
}

declare module 'libxmljs/test/element' {
  declare module.exports: any;
}

declare module 'libxmljs/test/html_parser' {
  declare module.exports: any;
}

declare module 'libxmljs/test/main' {
  declare module.exports: any;
}

declare module 'libxmljs/test/memory_management' {
  declare module.exports: any;
}

declare module 'libxmljs/test/namespace' {
  declare module.exports: any;
}

declare module 'libxmljs/test/node_attributes' {
  declare module.exports: any;
}

declare module 'libxmljs/test/ref_integrity' {
  declare module.exports: any;
}

declare module 'libxmljs/test/searching' {
  declare module.exports: any;
}

declare module 'libxmljs/test/text_node' {
  declare module.exports: any;
}

declare module 'libxmljs/test/text' {
  declare module.exports: any;
}

declare module 'libxmljs/test/traversal' {
  declare module.exports: any;
}

declare module 'libxmljs/test/xml_parser' {
  declare module.exports: any;
}

declare module 'libxmljs/test/xml_sax_parser' {
  declare module.exports: any;
}

declare module 'libxmljs/test/z_memory_leak' {
  declare module.exports: any;
}

// Filename aliases
declare module 'libxmljs/examples/cdata.js' {
  declare module.exports: $Exports<'libxmljs/examples/cdata'>;
}
declare module 'libxmljs/index' {
  declare module.exports: $Exports<'libxmljs'>;
}
declare module 'libxmljs/index.js' {
  declare module.exports: $Exports<'libxmljs'>;
}
declare module 'libxmljs/lib/bindings.js' {
  declare module.exports: $Exports<'libxmljs/lib/bindings'>;
}
declare module 'libxmljs/lib/comment.js' {
  declare module.exports: $Exports<'libxmljs/lib/comment'>;
}
declare module 'libxmljs/lib/document.js' {
  declare module.exports: $Exports<'libxmljs/lib/document'>;
}
declare module 'libxmljs/lib/element.js' {
  declare module.exports: $Exports<'libxmljs/lib/element'>;
}
declare module 'libxmljs/lib/sax_parser.js' {
  declare module.exports: $Exports<'libxmljs/lib/sax_parser'>;
}
declare module 'libxmljs/lib/text.js' {
  declare module.exports: $Exports<'libxmljs/lib/text'>;
}
declare module 'libxmljs/test/attribute.js' {
  declare module.exports: $Exports<'libxmljs/test/attribute'>;
}
declare module 'libxmljs/test/comment.js' {
  declare module.exports: $Exports<'libxmljs/test/comment'>;
}
declare module 'libxmljs/test/document.js' {
  declare module.exports: $Exports<'libxmljs/test/document'>;
}
declare module 'libxmljs/test/element.js' {
  declare module.exports: $Exports<'libxmljs/test/element'>;
}
declare module 'libxmljs/test/html_parser.js' {
  declare module.exports: $Exports<'libxmljs/test/html_parser'>;
}
declare module 'libxmljs/test/main.js' {
  declare module.exports: $Exports<'libxmljs/test/main'>;
}
declare module 'libxmljs/test/memory_management.js' {
  declare module.exports: $Exports<'libxmljs/test/memory_management'>;
}
declare module 'libxmljs/test/namespace.js' {
  declare module.exports: $Exports<'libxmljs/test/namespace'>;
}
declare module 'libxmljs/test/node_attributes.js' {
  declare module.exports: $Exports<'libxmljs/test/node_attributes'>;
}
declare module 'libxmljs/test/ref_integrity.js' {
  declare module.exports: $Exports<'libxmljs/test/ref_integrity'>;
}
declare module 'libxmljs/test/searching.js' {
  declare module.exports: $Exports<'libxmljs/test/searching'>;
}
declare module 'libxmljs/test/text_node.js' {
  declare module.exports: $Exports<'libxmljs/test/text_node'>;
}
declare module 'libxmljs/test/text.js' {
  declare module.exports: $Exports<'libxmljs/test/text'>;
}
declare module 'libxmljs/test/traversal.js' {
  declare module.exports: $Exports<'libxmljs/test/traversal'>;
}
declare module 'libxmljs/test/xml_parser.js' {
  declare module.exports: $Exports<'libxmljs/test/xml_parser'>;
}
declare module 'libxmljs/test/xml_sax_parser.js' {
  declare module.exports: $Exports<'libxmljs/test/xml_sax_parser'>;
}
declare module 'libxmljs/test/z_memory_leak.js' {
  declare module.exports: $Exports<'libxmljs/test/z_memory_leak'>;
}
