// flow-typed signature: 25f61cb0d8592172ee5cd04458f9e73f
// flow-typed version: <<STUB>>/lodash.endswith_v4.2.1/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.endswith'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.endswith' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.endswith/index' {
  declare module.exports: $Exports<'lodash.endswith'>;
}
declare module 'lodash.endswith/index.js' {
  declare module.exports: $Exports<'lodash.endswith'>;
}
