// flow-typed signature: cfb36d4bba47deb0e4e08fc8e3112055
// flow-typed version: <<STUB>>/lodash.difference_v^4.5.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.difference'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.difference' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.difference/index' {
  declare module.exports: $Exports<'lodash.difference'>;
}
declare module 'lodash.difference/index.js' {
  declare module.exports: $Exports<'lodash.difference'>;
}
