// flow-typed signature: 80355da699901392e2ffe889e6dcbd40
// flow-typed version: <<STUB>>/lodash.min_v4.0.1/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.min'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.min' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.min/index' {
  declare module.exports: $Exports<'lodash.min'>;
}
declare module 'lodash.min/index.js' {
  declare module.exports: $Exports<'lodash.min'>;
}
