// flow-typed signature: e1131d616178529e37c047eaef395977
// flow-typed version: <<STUB>>/lodash.max_v4.0.1/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.max'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.max' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.max/index' {
  declare module.exports: $Exports<'lodash.max'>;
}
declare module 'lodash.max/index.js' {
  declare module.exports: $Exports<'lodash.max'>;
}
