// flow-typed signature: 6f488f11e2e300c9147c3f68f6f386a0
// flow-typed version: <<STUB>>/lodash.zipobject_v4.1.3/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.zipobject'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.zipobject' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.zipobject/index' {
  declare module.exports: $Exports<'lodash.zipobject'>;
}
declare module 'lodash.zipobject/index.js' {
  declare module.exports: $Exports<'lodash.zipobject'>;
}
