// flow-typed signature: 29bc873c82f630ee64cf05658055602c
// flow-typed version: <<STUB>>/lodash.remove_v4.7.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.remove'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.remove' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.remove/index' {
  declare module.exports: $Exports<'lodash.remove'>;
}
declare module 'lodash.remove/index.js' {
  declare module.exports: $Exports<'lodash.remove'>;
}
