// flow-typed signature: cbd5c8277979381ca38c2e9e8ee3f6a2
// flow-typed version: <<STUB>>/lodash.every_v4.6.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.every'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.every' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.every/index' {
  declare module.exports: $Exports<'lodash.every'>;
}
declare module 'lodash.every/index.js' {
  declare module.exports: $Exports<'lodash.every'>;
}
