// flow-typed signature: 67f5c33ec96709c4398fbd5b25c96275
// flow-typed version: <<STUB>>/lodash.assignin_v4.2.0/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.assignin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.assignin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.assignin/index' {
  declare module.exports: $Exports<'lodash.assignin'>;
}
declare module 'lodash.assignin/index.js' {
  declare module.exports: $Exports<'lodash.assignin'>;
}
