// flow-typed signature: c8051aa0f82479006747807119325ec6
// flow-typed version: <<STUB>>/lodash.foreachright_v4.4.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.foreachright'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.foreachright' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.foreachright/index' {
  declare module.exports: $Exports<'lodash.foreachright'>;
}
declare module 'lodash.foreachright/index.js' {
  declare module.exports: $Exports<'lodash.foreachright'>;
}
