// flow-typed signature: f9f1a210d0e5a3caff8a9b3db52f3331
// flow-typed version: <<STUB>>/lodash.foreach_v4.5.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.foreach'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.foreach' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.foreach/index' {
  declare module.exports: $Exports<'lodash.foreach'>;
}
declare module 'lodash.foreach/index.js' {
  declare module.exports: $Exports<'lodash.foreach'>;
}
