// flow-typed signature: 585f323b62b4cd702472b6e557b9b516
// flow-typed version: <<STUB>>/mailcomposer_v3.12.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mailcomposer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mailcomposer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mailcomposer/Gruntfile' {
  declare module.exports: any;
}

declare module 'mailcomposer/lib/mailcomposer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mailcomposer/Gruntfile.js' {
  declare module.exports: $Exports<'mailcomposer/Gruntfile'>;
}
declare module 'mailcomposer/lib/mailcomposer.js' {
  declare module.exports: $Exports<'mailcomposer/lib/mailcomposer'>;
}
