// flow-typed signature: a090ac28aadadfcdc8e799e392b2afb6
// flow-typed version: <<STUB>>/mailchimp-api-v3_v^1.7.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mailchimp-api-v3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mailchimp-api-v3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'mailchimp-api-v3/index' {
  declare module.exports: $Exports<'mailchimp-api-v3'>;
}
declare module 'mailchimp-api-v3/index.js' {
  declare module.exports: $Exports<'mailchimp-api-v3'>;
}
