// flow-typed signature: b86c352de831fc584a2cfcef263c710d
// flow-typed version: <<STUB>>/mailcomposer_v^4.0.2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mailcomposer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mailcomposer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mailcomposer/Gruntfile' {
  declare module.exports: any;
}

declare module 'mailcomposer/lib/mailcomposer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mailcomposer/Gruntfile.js' {
  declare module.exports: $Exports<'mailcomposer/Gruntfile'>;
}
declare module 'mailcomposer/lib/mailcomposer.js' {
  declare module.exports: $Exports<'mailcomposer/lib/mailcomposer'>;
}
