// flow-typed signature: 2b509313240b3de79e0a42b0a52012ab
// flow-typed version: <<STUB>>/mapbox-gl-regex-query_v0.1.2/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mapbox-gl-regex-query'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mapbox-gl-regex-query' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mapbox-gl-regex-query/dist/mapbox-gl-regex-query-dev' {
  declare module.exports: any;
}

declare module 'mapbox-gl-regex-query/dist/mapbox-gl-regex-query' {
  declare module.exports: any;
}

declare module 'mapbox-gl-regex-query/src/feature_filter' {
  declare module.exports: any;
}

declare module 'mapbox-gl-regex-query/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mapbox-gl-regex-query/dist/mapbox-gl-regex-query-dev.js' {
  declare module.exports: $Exports<'mapbox-gl-regex-query/dist/mapbox-gl-regex-query-dev'>;
}
declare module 'mapbox-gl-regex-query/dist/mapbox-gl-regex-query.js' {
  declare module.exports: $Exports<'mapbox-gl-regex-query/dist/mapbox-gl-regex-query'>;
}
declare module 'mapbox-gl-regex-query/src/feature_filter.js' {
  declare module.exports: $Exports<'mapbox-gl-regex-query/src/feature_filter'>;
}
declare module 'mapbox-gl-regex-query/src/index.js' {
  declare module.exports: $Exports<'mapbox-gl-regex-query/src/index'>;
}
