// flow-typed signature: 19dba37e312b96f6658cfb7b1fad924e
// flow-typed version: <<STUB>>/mapbox-gl-dual-scale-control_v^0.1.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mapbox-gl-dual-scale-control'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mapbox-gl-dual-scale-control' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mapbox-gl-dual-scale-control/dist/mapbox-gl-dual-scale-control-dev' {
  declare module.exports: any;
}

declare module 'mapbox-gl-dual-scale-control/dist/mapbox-gl-dual-scale-control' {
  declare module.exports: any;
}

declare module 'mapbox-gl-dual-scale-control/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mapbox-gl-dual-scale-control/dist/mapbox-gl-dual-scale-control-dev.js' {
  declare module.exports: $Exports<'mapbox-gl-dual-scale-control/dist/mapbox-gl-dual-scale-control-dev'>;
}
declare module 'mapbox-gl-dual-scale-control/dist/mapbox-gl-dual-scale-control.js' {
  declare module.exports: $Exports<'mapbox-gl-dual-scale-control/dist/mapbox-gl-dual-scale-control'>;
}
declare module 'mapbox-gl-dual-scale-control/src/index.js' {
  declare module.exports: $Exports<'mapbox-gl-dual-scale-control/src/index'>;
}
