// flow-typed signature: 20ffff544229aec5b0eb3eeb0233aa9f
// flow-typed version: <<STUB>>/mapbox-gl-arcgis-tiled-map-service_v^0.1.2/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mapbox-gl-arcgis-tiled-map-service'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mapbox-gl-arcgis-tiled-map-service' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mapbox-gl-arcgis-tiled-map-service/dist/mapbox-gl-arcgis-tiled-map-service-dev' {
  declare module.exports: any;
}

declare module 'mapbox-gl-arcgis-tiled-map-service/dist/mapbox-gl-arcgis-tiled-map-service' {
  declare module.exports: any;
}

declare module 'mapbox-gl-arcgis-tiled-map-service/src/arcgis_tiled_map_service_source' {
  declare module.exports: any;
}

declare module 'mapbox-gl-arcgis-tiled-map-service/src/index' {
  declare module.exports: any;
}

declare module 'mapbox-gl-arcgis-tiled-map-service/src/load_arcgis_mapserver' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mapbox-gl-arcgis-tiled-map-service/dist/mapbox-gl-arcgis-tiled-map-service-dev.js' {
  declare module.exports: $Exports<'mapbox-gl-arcgis-tiled-map-service/dist/mapbox-gl-arcgis-tiled-map-service-dev'>;
}
declare module 'mapbox-gl-arcgis-tiled-map-service/dist/mapbox-gl-arcgis-tiled-map-service.js' {
  declare module.exports: $Exports<'mapbox-gl-arcgis-tiled-map-service/dist/mapbox-gl-arcgis-tiled-map-service'>;
}
declare module 'mapbox-gl-arcgis-tiled-map-service/src/arcgis_tiled_map_service_source.js' {
  declare module.exports: $Exports<'mapbox-gl-arcgis-tiled-map-service/src/arcgis_tiled_map_service_source'>;
}
declare module 'mapbox-gl-arcgis-tiled-map-service/src/index.js' {
  declare module.exports: $Exports<'mapbox-gl-arcgis-tiled-map-service/src/index'>;
}
declare module 'mapbox-gl-arcgis-tiled-map-service/src/load_arcgis_mapserver.js' {
  declare module.exports: $Exports<'mapbox-gl-arcgis-tiled-map-service/src/load_arcgis_mapserver'>;
}
