// flow-typed signature: 4f5473e46aa8f3c6398d35510d69d8d7
// flow-typed version: <<STUB>>/node-sass-middleware_v0.11.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-sass-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-sass-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-sass-middleware/middleware' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-sass-middleware/middleware.js' {
  declare module.exports: $Exports<'node-sass-middleware/middleware'>;
}
