// flow-typed signature: 1ecd6d573eb8be18b414051608015694
// flow-typed version: <<STUB>>/nodejs-dashboard_v^0.4.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nodejs-dashboard'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nodejs-dashboard' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nodejs-dashboard/bin/nodejs-dashboard' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/lib/config' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/lib/dashboard-agent' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/lib/dashboard' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/lib/default-layout-config' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/lib/generate-layouts' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/lib/parse-settings' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/lib/providers/log-provider' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/lib/providers/metrics-provider' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/lib/utils' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/lib/views/base-line-graph' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/lib/views/base-view' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/lib/views/cpu-view' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/lib/views/eventloop-view' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/lib/views/help' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/lib/views/memory-gauge-view' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/lib/views/memory-graph-view' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/lib/views/stream-view' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/test/app/index' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/test/app/layouts' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/test/lib/dashboard-agent.spec' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/test/lib/generate-layouts.spec' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/test/lib/parse-settings.spec' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/test/lib/providers/log-provider.spec' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/test/lib/providers/metrics-provider.spec' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/test/lib/views/base-line-graph.spec' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/test/lib/views/base-view.spec' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/test/lib/views/cpu-view.spec' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/test/lib/views/eventloop-view.spec' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/test/lib/views/help.spec' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/test/lib/views/memory-gauge-view.spec' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/test/lib/views/stream-view.spec' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/test/setup' {
  declare module.exports: any;
}

declare module 'nodejs-dashboard/test/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nodejs-dashboard/bin/nodejs-dashboard.js' {
  declare module.exports: $Exports<'nodejs-dashboard/bin/nodejs-dashboard'>;
}
declare module 'nodejs-dashboard/index' {
  declare module.exports: $Exports<'nodejs-dashboard'>;
}
declare module 'nodejs-dashboard/index.js' {
  declare module.exports: $Exports<'nodejs-dashboard'>;
}
declare module 'nodejs-dashboard/lib/config.js' {
  declare module.exports: $Exports<'nodejs-dashboard/lib/config'>;
}
declare module 'nodejs-dashboard/lib/dashboard-agent.js' {
  declare module.exports: $Exports<'nodejs-dashboard/lib/dashboard-agent'>;
}
declare module 'nodejs-dashboard/lib/dashboard.js' {
  declare module.exports: $Exports<'nodejs-dashboard/lib/dashboard'>;
}
declare module 'nodejs-dashboard/lib/default-layout-config.js' {
  declare module.exports: $Exports<'nodejs-dashboard/lib/default-layout-config'>;
}
declare module 'nodejs-dashboard/lib/generate-layouts.js' {
  declare module.exports: $Exports<'nodejs-dashboard/lib/generate-layouts'>;
}
declare module 'nodejs-dashboard/lib/parse-settings.js' {
  declare module.exports: $Exports<'nodejs-dashboard/lib/parse-settings'>;
}
declare module 'nodejs-dashboard/lib/providers/log-provider.js' {
  declare module.exports: $Exports<'nodejs-dashboard/lib/providers/log-provider'>;
}
declare module 'nodejs-dashboard/lib/providers/metrics-provider.js' {
  declare module.exports: $Exports<'nodejs-dashboard/lib/providers/metrics-provider'>;
}
declare module 'nodejs-dashboard/lib/utils.js' {
  declare module.exports: $Exports<'nodejs-dashboard/lib/utils'>;
}
declare module 'nodejs-dashboard/lib/views/base-line-graph.js' {
  declare module.exports: $Exports<'nodejs-dashboard/lib/views/base-line-graph'>;
}
declare module 'nodejs-dashboard/lib/views/base-view.js' {
  declare module.exports: $Exports<'nodejs-dashboard/lib/views/base-view'>;
}
declare module 'nodejs-dashboard/lib/views/cpu-view.js' {
  declare module.exports: $Exports<'nodejs-dashboard/lib/views/cpu-view'>;
}
declare module 'nodejs-dashboard/lib/views/eventloop-view.js' {
  declare module.exports: $Exports<'nodejs-dashboard/lib/views/eventloop-view'>;
}
declare module 'nodejs-dashboard/lib/views/help.js' {
  declare module.exports: $Exports<'nodejs-dashboard/lib/views/help'>;
}
declare module 'nodejs-dashboard/lib/views/memory-gauge-view.js' {
  declare module.exports: $Exports<'nodejs-dashboard/lib/views/memory-gauge-view'>;
}
declare module 'nodejs-dashboard/lib/views/memory-graph-view.js' {
  declare module.exports: $Exports<'nodejs-dashboard/lib/views/memory-graph-view'>;
}
declare module 'nodejs-dashboard/lib/views/stream-view.js' {
  declare module.exports: $Exports<'nodejs-dashboard/lib/views/stream-view'>;
}
declare module 'nodejs-dashboard/test/app/index.js' {
  declare module.exports: $Exports<'nodejs-dashboard/test/app/index'>;
}
declare module 'nodejs-dashboard/test/app/layouts.js' {
  declare module.exports: $Exports<'nodejs-dashboard/test/app/layouts'>;
}
declare module 'nodejs-dashboard/test/lib/dashboard-agent.spec.js' {
  declare module.exports: $Exports<'nodejs-dashboard/test/lib/dashboard-agent.spec'>;
}
declare module 'nodejs-dashboard/test/lib/generate-layouts.spec.js' {
  declare module.exports: $Exports<'nodejs-dashboard/test/lib/generate-layouts.spec'>;
}
declare module 'nodejs-dashboard/test/lib/parse-settings.spec.js' {
  declare module.exports: $Exports<'nodejs-dashboard/test/lib/parse-settings.spec'>;
}
declare module 'nodejs-dashboard/test/lib/providers/log-provider.spec.js' {
  declare module.exports: $Exports<'nodejs-dashboard/test/lib/providers/log-provider.spec'>;
}
declare module 'nodejs-dashboard/test/lib/providers/metrics-provider.spec.js' {
  declare module.exports: $Exports<'nodejs-dashboard/test/lib/providers/metrics-provider.spec'>;
}
declare module 'nodejs-dashboard/test/lib/views/base-line-graph.spec.js' {
  declare module.exports: $Exports<'nodejs-dashboard/test/lib/views/base-line-graph.spec'>;
}
declare module 'nodejs-dashboard/test/lib/views/base-view.spec.js' {
  declare module.exports: $Exports<'nodejs-dashboard/test/lib/views/base-view.spec'>;
}
declare module 'nodejs-dashboard/test/lib/views/cpu-view.spec.js' {
  declare module.exports: $Exports<'nodejs-dashboard/test/lib/views/cpu-view.spec'>;
}
declare module 'nodejs-dashboard/test/lib/views/eventloop-view.spec.js' {
  declare module.exports: $Exports<'nodejs-dashboard/test/lib/views/eventloop-view.spec'>;
}
declare module 'nodejs-dashboard/test/lib/views/help.spec.js' {
  declare module.exports: $Exports<'nodejs-dashboard/test/lib/views/help.spec'>;
}
declare module 'nodejs-dashboard/test/lib/views/memory-gauge-view.spec.js' {
  declare module.exports: $Exports<'nodejs-dashboard/test/lib/views/memory-gauge-view.spec'>;
}
declare module 'nodejs-dashboard/test/lib/views/stream-view.spec.js' {
  declare module.exports: $Exports<'nodejs-dashboard/test/lib/views/stream-view.spec'>;
}
declare module 'nodejs-dashboard/test/setup.js' {
  declare module.exports: $Exports<'nodejs-dashboard/test/setup'>;
}
declare module 'nodejs-dashboard/test/utils.js' {
  declare module.exports: $Exports<'nodejs-dashboard/test/utils'>;
}
