// flow-typed signature: 4805bcfe9e117a13476893fe0c6583fa
// flow-typed version: <<STUB>>/nuka-carousel_v^2.0.4/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nuka-carousel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nuka-carousel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nuka-carousel/demo/app' {
  declare module.exports: any;
}

declare module 'nuka-carousel/Gulpfile' {
  declare module.exports: any;
}

declare module 'nuka-carousel/karma.conf' {
  declare module.exports: any;
}

declare module 'nuka-carousel/lib/carousel' {
  declare module.exports: any;
}

declare module 'nuka-carousel/lib/decorators' {
  declare module.exports: any;
}

declare module 'nuka-carousel/src/carousel' {
  declare module.exports: any;
}

declare module 'nuka-carousel/src/decorators' {
  declare module.exports: any;
}

declare module 'nuka-carousel/test/helpers/phantomjs-shims' {
  declare module.exports: any;
}

declare module 'nuka-carousel/test/helpers/raf-polyfill' {
  declare module.exports: any;
}

declare module 'nuka-carousel/test/specs/carousel.spec' {
  declare module.exports: any;
}

declare module 'nuka-carousel/webpack.config' {
  declare module.exports: any;
}

declare module 'nuka-carousel/webpack.dist.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nuka-carousel/demo/app.js' {
  declare module.exports: $Exports<'nuka-carousel/demo/app'>;
}
declare module 'nuka-carousel/Gulpfile.js' {
  declare module.exports: $Exports<'nuka-carousel/Gulpfile'>;
}
declare module 'nuka-carousel/index' {
  declare module.exports: $Exports<'nuka-carousel'>;
}
declare module 'nuka-carousel/index.js' {
  declare module.exports: $Exports<'nuka-carousel'>;
}
declare module 'nuka-carousel/karma.conf.js' {
  declare module.exports: $Exports<'nuka-carousel/karma.conf'>;
}
declare module 'nuka-carousel/lib/carousel.js' {
  declare module.exports: $Exports<'nuka-carousel/lib/carousel'>;
}
declare module 'nuka-carousel/lib/decorators.js' {
  declare module.exports: $Exports<'nuka-carousel/lib/decorators'>;
}
declare module 'nuka-carousel/src/carousel.js' {
  declare module.exports: $Exports<'nuka-carousel/src/carousel'>;
}
declare module 'nuka-carousel/src/decorators.js' {
  declare module.exports: $Exports<'nuka-carousel/src/decorators'>;
}
declare module 'nuka-carousel/test/helpers/phantomjs-shims.js' {
  declare module.exports: $Exports<'nuka-carousel/test/helpers/phantomjs-shims'>;
}
declare module 'nuka-carousel/test/helpers/raf-polyfill.js' {
  declare module.exports: $Exports<'nuka-carousel/test/helpers/raf-polyfill'>;
}
declare module 'nuka-carousel/test/specs/carousel.spec.js' {
  declare module.exports: $Exports<'nuka-carousel/test/specs/carousel.spec'>;
}
declare module 'nuka-carousel/webpack.config.js' {
  declare module.exports: $Exports<'nuka-carousel/webpack.config'>;
}
declare module 'nuka-carousel/webpack.dist.config.js' {
  declare module.exports: $Exports<'nuka-carousel/webpack.dist.config'>;
}
