// flow-typed signature: f5434499627ca99ae95e448753a27cfb
// flow-typed version: <<STUB>>/oauthorize_v0.1.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'oauthorize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'oauthorize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'oauthorize/lib/errors/authorizationerror' {
  declare module.exports: any;
}

declare module 'oauthorize/lib/errors/badrequesterror' {
  declare module.exports: any;
}

declare module 'oauthorize/lib/index' {
  declare module.exports: any;
}

declare module 'oauthorize/lib/middleware/accessToken' {
  declare module.exports: any;
}

declare module 'oauthorize/lib/middleware/errorHandler' {
  declare module.exports: any;
}

declare module 'oauthorize/lib/middleware/requestToken' {
  declare module.exports: any;
}

declare module 'oauthorize/lib/middleware/transactionLoader' {
  declare module.exports: any;
}

declare module 'oauthorize/lib/middleware/userAuthorization' {
  declare module.exports: any;
}

declare module 'oauthorize/lib/middleware/userDecision' {
  declare module.exports: any;
}

declare module 'oauthorize/lib/server' {
  declare module.exports: any;
}

declare module 'oauthorize/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'oauthorize/lib/errors/authorizationerror.js' {
  declare module.exports: $Exports<'oauthorize/lib/errors/authorizationerror'>;
}
declare module 'oauthorize/lib/errors/badrequesterror.js' {
  declare module.exports: $Exports<'oauthorize/lib/errors/badrequesterror'>;
}
declare module 'oauthorize/lib/index.js' {
  declare module.exports: $Exports<'oauthorize/lib/index'>;
}
declare module 'oauthorize/lib/middleware/accessToken.js' {
  declare module.exports: $Exports<'oauthorize/lib/middleware/accessToken'>;
}
declare module 'oauthorize/lib/middleware/errorHandler.js' {
  declare module.exports: $Exports<'oauthorize/lib/middleware/errorHandler'>;
}
declare module 'oauthorize/lib/middleware/requestToken.js' {
  declare module.exports: $Exports<'oauthorize/lib/middleware/requestToken'>;
}
declare module 'oauthorize/lib/middleware/transactionLoader.js' {
  declare module.exports: $Exports<'oauthorize/lib/middleware/transactionLoader'>;
}
declare module 'oauthorize/lib/middleware/userAuthorization.js' {
  declare module.exports: $Exports<'oauthorize/lib/middleware/userAuthorization'>;
}
declare module 'oauthorize/lib/middleware/userDecision.js' {
  declare module.exports: $Exports<'oauthorize/lib/middleware/userDecision'>;
}
declare module 'oauthorize/lib/server.js' {
  declare module.exports: $Exports<'oauthorize/lib/server'>;
}
declare module 'oauthorize/lib/utils.js' {
  declare module.exports: $Exports<'oauthorize/lib/utils'>;
}
