// flow-typed signature: deeb034befea4049a7b21992b5e3aa66
// flow-typed version: <<STUB>>/object-sizeof_v^1.1.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'object-sizeof'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'object-sizeof' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'object-sizeof/byte_size' {
  declare module.exports: any;
}

declare module 'object-sizeof/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'object-sizeof/byte_size.js' {
  declare module.exports: $Exports<'object-sizeof/byte_size'>;
}
declare module 'object-sizeof/index' {
  declare module.exports: $Exports<'object-sizeof'>;
}
declare module 'object-sizeof/index.js' {
  declare module.exports: $Exports<'object-sizeof'>;
}
declare module 'object-sizeof/test/test.js' {
  declare module.exports: $Exports<'object-sizeof/test/test'>;
}
