// flow-typed signature: f13955d16a543ac18fcb7ba075d89b1a
// flow-typed version: <<STUB>>/ogr2ogr_v^1.2.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ogr2ogr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ogr2ogr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ogr2ogr/modules/csv' {
  declare module.exports: any;
}

declare module 'ogr2ogr/modules/util' {
  declare module.exports: any;
}

declare module 'ogr2ogr/modules/zip' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ogr2ogr/index' {
  declare module.exports: $Exports<'ogr2ogr'>;
}
declare module 'ogr2ogr/index.js' {
  declare module.exports: $Exports<'ogr2ogr'>;
}
declare module 'ogr2ogr/modules/csv.js' {
  declare module.exports: $Exports<'ogr2ogr/modules/csv'>;
}
declare module 'ogr2ogr/modules/util.js' {
  declare module.exports: $Exports<'ogr2ogr/modules/util'>;
}
declare module 'ogr2ogr/modules/zip.js' {
  declare module.exports: $Exports<'ogr2ogr/modules/zip'>;
}
