// flow-typed signature: 10c57408a816794e76df27753fcddf4d
// flow-typed version: <<STUB>>/ogr2ogr_v^1.0.1/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ogr2ogr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ogr2ogr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ogr2ogr/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'ogr2ogr/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'ogr2ogr/examples/exec' {
  declare module.exports: any;
}

declare module 'ogr2ogr/examples/geojson-obj' {
  declare module.exports: any;
}

declare module 'ogr2ogr/examples/geojson-url' {
  declare module.exports: any;
}

declare module 'ogr2ogr/examples/georss-url' {
  declare module.exports: any;
}

declare module 'ogr2ogr/examples/in-stream' {
  declare module.exports: any;
}

declare module 'ogr2ogr/examples/postgres' {
  declare module.exports: any;
}

declare module 'ogr2ogr/examples/stream' {
  declare module.exports: any;
}

declare module 'ogr2ogr/lib/csv' {
  declare module.exports: any;
}

declare module 'ogr2ogr/lib/util' {
  declare module.exports: any;
}

declare module 'ogr2ogr/lib/zip' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ogr2ogr/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'ogr2ogr/coverage/lcov-report/prettify'>;
}
declare module 'ogr2ogr/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'ogr2ogr/coverage/lcov-report/sorter'>;
}
declare module 'ogr2ogr/examples/exec.js' {
  declare module.exports: $Exports<'ogr2ogr/examples/exec'>;
}
declare module 'ogr2ogr/examples/geojson-obj.js' {
  declare module.exports: $Exports<'ogr2ogr/examples/geojson-obj'>;
}
declare module 'ogr2ogr/examples/geojson-url.js' {
  declare module.exports: $Exports<'ogr2ogr/examples/geojson-url'>;
}
declare module 'ogr2ogr/examples/georss-url.js' {
  declare module.exports: $Exports<'ogr2ogr/examples/georss-url'>;
}
declare module 'ogr2ogr/examples/in-stream.js' {
  declare module.exports: $Exports<'ogr2ogr/examples/in-stream'>;
}
declare module 'ogr2ogr/examples/postgres.js' {
  declare module.exports: $Exports<'ogr2ogr/examples/postgres'>;
}
declare module 'ogr2ogr/examples/stream.js' {
  declare module.exports: $Exports<'ogr2ogr/examples/stream'>;
}
declare module 'ogr2ogr/index' {
  declare module.exports: $Exports<'ogr2ogr'>;
}
declare module 'ogr2ogr/index.js' {
  declare module.exports: $Exports<'ogr2ogr'>;
}
declare module 'ogr2ogr/lib/csv.js' {
  declare module.exports: $Exports<'ogr2ogr/lib/csv'>;
}
declare module 'ogr2ogr/lib/util.js' {
  declare module.exports: $Exports<'ogr2ogr/lib/util'>;
}
declare module 'ogr2ogr/lib/zip.js' {
  declare module.exports: $Exports<'ogr2ogr/lib/zip'>;
}
