// flow-typed signature: 4d2323114e51660bb3426aae24c31d1b
// flow-typed version: <<STUB>>/osm-and-geojson_vopenmaphub/osm-and-geojson/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'osm-and-geojson'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'osm-and-geojson' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'osm-and-geojson/osm_geojson' {
  declare module.exports: any;
}

declare module 'osm-and-geojson/test/osm.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'osm-and-geojson/osm_geojson.js' {
  declare module.exports: $Exports<'osm-and-geojson/osm_geojson'>;
}
declare module 'osm-and-geojson/test/osm.test.js' {
  declare module.exports: $Exports<'osm-and-geojson/test/osm.test'>;
}
