// flow-typed signature: 69294d349d53ac6030dea4e973575e22
// flow-typed version: <<STUB>>/passport-openstreetmap_v0.1.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-openstreetmap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-openstreetmap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-openstreetmap/lib/passport-openstreetmap/index' {
  declare module.exports: any;
}

declare module 'passport-openstreetmap/lib/passport-openstreetmap/strategy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-openstreetmap/lib/passport-openstreetmap/index.js' {
  declare module.exports: $Exports<'passport-openstreetmap/lib/passport-openstreetmap/index'>;
}
declare module 'passport-openstreetmap/lib/passport-openstreetmap/strategy.js' {
  declare module.exports: $Exports<'passport-openstreetmap/lib/passport-openstreetmap/strategy'>;
}
