// flow-typed signature: ab82971f3a2f0b173c743da7b8dea43e
// flow-typed version: <<STUB>>/passport-auth0_v^0.6.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-auth0'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-auth0' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-auth0/lib/index' {
  declare module.exports: any;
}

declare module 'passport-auth0/lib/Profile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-auth0/lib/index.js' {
  declare module.exports: $Exports<'passport-auth0/lib/index'>;
}
declare module 'passport-auth0/lib/Profile.js' {
  declare module.exports: $Exports<'passport-auth0/lib/Profile'>;
}
