// flow-typed signature: 91cfb8fbc91296cf4155b58c724958ba
// flow-typed version: <<STUB>>/passport-http-oauth_v0.1.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-http-oauth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-http-oauth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-http-oauth/lib/passport-http-oauth/index' {
  declare module.exports: any;
}

declare module 'passport-http-oauth/lib/passport-http-oauth/multihash' {
  declare module.exports: any;
}

declare module 'passport-http-oauth/lib/passport-http-oauth/strategies/consumer' {
  declare module.exports: any;
}

declare module 'passport-http-oauth/lib/passport-http-oauth/strategies/token' {
  declare module.exports: any;
}

declare module 'passport-http-oauth/lib/passport-http-oauth/strategies/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-http-oauth/lib/passport-http-oauth/index.js' {
  declare module.exports: $Exports<'passport-http-oauth/lib/passport-http-oauth/index'>;
}
declare module 'passport-http-oauth/lib/passport-http-oauth/multihash.js' {
  declare module.exports: $Exports<'passport-http-oauth/lib/passport-http-oauth/multihash'>;
}
declare module 'passport-http-oauth/lib/passport-http-oauth/strategies/consumer.js' {
  declare module.exports: $Exports<'passport-http-oauth/lib/passport-http-oauth/strategies/consumer'>;
}
declare module 'passport-http-oauth/lib/passport-http-oauth/strategies/token.js' {
  declare module.exports: $Exports<'passport-http-oauth/lib/passport-http-oauth/strategies/token'>;
}
declare module 'passport-http-oauth/lib/passport-http-oauth/strategies/utils.js' {
  declare module.exports: $Exports<'passport-http-oauth/lib/passport-http-oauth/strategies/utils'>;
}
