// flow-typed signature: ef106507c50326f5f598a57ba57acc29
// flow-typed version: <<STUB>>/pbf_v^3.0.5/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pbf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pbf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pbf/bench/bench-tiles' {
  declare module.exports: any;
}

declare module 'pbf/bench/bench' {
  declare module.exports: any;
}

declare module 'pbf/bench/data' {
  declare module.exports: any;
}

declare module 'pbf/bench/vector_tile' {
  declare module.exports: any;
}

declare module 'pbf/compile' {
  declare module.exports: any;
}

declare module 'pbf/dist/pbf-dev' {
  declare module.exports: any;
}

declare module 'pbf/dist/pbf' {
  declare module.exports: any;
}

declare module 'pbf/test/compile.test' {
  declare module.exports: any;
}

declare module 'pbf/test/pbf.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pbf/bench/bench-tiles.js' {
  declare module.exports: $Exports<'pbf/bench/bench-tiles'>;
}
declare module 'pbf/bench/bench.js' {
  declare module.exports: $Exports<'pbf/bench/bench'>;
}
declare module 'pbf/bench/data.js' {
  declare module.exports: $Exports<'pbf/bench/data'>;
}
declare module 'pbf/bench/vector_tile.js' {
  declare module.exports: $Exports<'pbf/bench/vector_tile'>;
}
declare module 'pbf/compile.js' {
  declare module.exports: $Exports<'pbf/compile'>;
}
declare module 'pbf/dist/pbf-dev.js' {
  declare module.exports: $Exports<'pbf/dist/pbf-dev'>;
}
declare module 'pbf/dist/pbf.js' {
  declare module.exports: $Exports<'pbf/dist/pbf'>;
}
declare module 'pbf/index' {
  declare module.exports: $Exports<'pbf'>;
}
declare module 'pbf/index.js' {
  declare module.exports: $Exports<'pbf'>;
}
declare module 'pbf/test/compile.test.js' {
  declare module.exports: $Exports<'pbf/test/compile.test'>;
}
declare module 'pbf/test/pbf.test.js' {
  declare module.exports: $Exports<'pbf/test/pbf.test'>;
}
