// flow-typed signature: 25e064c2ebb059914da3e44ed05af782
// flow-typed version: <<STUB>>/pg-native_v^2.2.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pg-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pg-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pg-native/bench/index' {
  declare module.exports: any;
}

declare module 'pg-native/bench/leaks' {
  declare module.exports: any;
}

declare module 'pg-native/lib/build-result' {
  declare module.exports: any;
}

declare module 'pg-native/lib/copy-stream' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pg-native/bench/index.js' {
  declare module.exports: $Exports<'pg-native/bench/index'>;
}
declare module 'pg-native/bench/leaks.js' {
  declare module.exports: $Exports<'pg-native/bench/leaks'>;
}
declare module 'pg-native/index' {
  declare module.exports: $Exports<'pg-native'>;
}
declare module 'pg-native/index.js' {
  declare module.exports: $Exports<'pg-native'>;
}
declare module 'pg-native/lib/build-result.js' {
  declare module.exports: $Exports<'pg-native/lib/build-result'>;
}
declare module 'pg-native/lib/copy-stream.js' {
  declare module.exports: $Exports<'pg-native/lib/copy-stream'>;
}
