// flow-typed signature: d91f3488ad1584ba243aa8dce619d4fc
// flow-typed version: <<STUB>>/pica_v2.0.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pica'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pica' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pica/dist/pica' {
  declare module.exports: any;
}

declare module 'pica/dist/pica.min' {
  declare module.exports: any;
}

declare module 'pica/lib/js/create_canvas_browser' {
  declare module.exports: any;
}

declare module 'pica/lib/js/create_canvas' {
  declare module.exports: any;
}

declare module 'pica/lib/js/generate_id' {
  declare module.exports: any;
}

declare module 'pica/lib/js/pool' {
  declare module.exports: any;
}

declare module 'pica/lib/js/resize_array' {
  declare module.exports: any;
}

declare module 'pica/lib/js/unsharp' {
  declare module.exports: any;
}

declare module 'pica/lib/js/utils' {
  declare module.exports: any;
}

declare module 'pica/lib/js/worker' {
  declare module.exports: any;
}

declare module 'pica/lib/resize_js_ww' {
  declare module.exports: any;
}

declare module 'pica/lib/resize_js' {
  declare module.exports: any;
}

declare module 'pica/lib/resize_webgl' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pica/dist/pica.js' {
  declare module.exports: $Exports<'pica/dist/pica'>;
}
declare module 'pica/dist/pica.min.js' {
  declare module.exports: $Exports<'pica/dist/pica.min'>;
}
declare module 'pica/index' {
  declare module.exports: $Exports<'pica'>;
}
declare module 'pica/index.js' {
  declare module.exports: $Exports<'pica'>;
}
declare module 'pica/lib/js/create_canvas_browser.js' {
  declare module.exports: $Exports<'pica/lib/js/create_canvas_browser'>;
}
declare module 'pica/lib/js/create_canvas.js' {
  declare module.exports: $Exports<'pica/lib/js/create_canvas'>;
}
declare module 'pica/lib/js/generate_id.js' {
  declare module.exports: $Exports<'pica/lib/js/generate_id'>;
}
declare module 'pica/lib/js/pool.js' {
  declare module.exports: $Exports<'pica/lib/js/pool'>;
}
declare module 'pica/lib/js/resize_array.js' {
  declare module.exports: $Exports<'pica/lib/js/resize_array'>;
}
declare module 'pica/lib/js/unsharp.js' {
  declare module.exports: $Exports<'pica/lib/js/unsharp'>;
}
declare module 'pica/lib/js/utils.js' {
  declare module.exports: $Exports<'pica/lib/js/utils'>;
}
declare module 'pica/lib/js/worker.js' {
  declare module.exports: $Exports<'pica/lib/js/worker'>;
}
declare module 'pica/lib/resize_js_ww.js' {
  declare module.exports: $Exports<'pica/lib/resize_js_ww'>;
}
declare module 'pica/lib/resize_js.js' {
  declare module.exports: $Exports<'pica/lib/resize_js'>;
}
declare module 'pica/lib/resize_webgl.js' {
  declare module.exports: $Exports<'pica/lib/resize_webgl'>;
}
