// flow-typed signature: b4cb1ad4d0bd6bde0ee2b5095eb0bee5
// flow-typed version: <<STUB>>/react-cropper_v1.0.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-cropper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-cropper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-cropper/dist/react-cropper' {
  declare module.exports: any;
}

declare module 'react-cropper/server' {
  declare module.exports: any;
}

declare module 'react-cropper/webpack.config.dev' {
  declare module.exports: any;
}

declare module 'react-cropper/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-cropper/dist/react-cropper.js' {
  declare module.exports: $Exports<'react-cropper/dist/react-cropper'>;
}
declare module 'react-cropper/server.js' {
  declare module.exports: $Exports<'react-cropper/server'>;
}
declare module 'react-cropper/webpack.config.dev.js' {
  declare module.exports: $Exports<'react-cropper/webpack.config.dev'>;
}
declare module 'react-cropper/webpack.config.js' {
  declare module.exports: $Exports<'react-cropper/webpack.config'>;
}
