// flow-typed signature: 36ed9cdd8b89a8f23fa76c0d8fb2f345
// flow-typed version: <<STUB>>/react-disqus-thread_vmaphubs/react-disqus-thread#4114ce406af88bd15b65cc4b7bb0744985a3dd48/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-disqus-thread'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-disqus-thread' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-disqus-thread/dist/react-disqus-thread' {
  declare module.exports: any;
}

declare module 'react-disqus-thread/dist/react-disqus-thread.min' {
  declare module.exports: any;
}

declare module 'react-disqus-thread/examples/basic/app' {
  declare module.exports: any;
}

declare module 'react-disqus-thread/lib/components/__tests__/DisqusThread-test' {
  declare module.exports: any;
}

declare module 'react-disqus-thread/lib/components/DisqusThread' {
  declare module.exports: any;
}

declare module 'react-disqus-thread/lib/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-disqus-thread/dist/react-disqus-thread.js' {
  declare module.exports: $Exports<'react-disqus-thread/dist/react-disqus-thread'>;
}
declare module 'react-disqus-thread/dist/react-disqus-thread.min.js' {
  declare module.exports: $Exports<'react-disqus-thread/dist/react-disqus-thread.min'>;
}
declare module 'react-disqus-thread/examples/basic/app.js' {
  declare module.exports: $Exports<'react-disqus-thread/examples/basic/app'>;
}
declare module 'react-disqus-thread/lib/components/__tests__/DisqusThread-test.js' {
  declare module.exports: $Exports<'react-disqus-thread/lib/components/__tests__/DisqusThread-test'>;
}
declare module 'react-disqus-thread/lib/components/DisqusThread.js' {
  declare module.exports: $Exports<'react-disqus-thread/lib/components/DisqusThread'>;
}
declare module 'react-disqus-thread/lib/main.js' {
  declare module.exports: $Exports<'react-disqus-thread/lib/main'>;
}
