// flow-typed signature: f89864f805ac364a2b9992fe5c85eee5
// flow-typed version: <<STUB>>/react-material-select_v^1.2.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-material-select'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-material-select' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-material-select/dist/app.d6a0eabd0d1b15b6c337' {
  declare module.exports: any;
}

declare module 'react-material-select/dist/vendor.d6a0eabd0d1b15b6c337' {
  declare module.exports: any;
}

declare module 'react-material-select/lib/components/ReactMaterialSelect' {
  declare module.exports: any;
}

declare module 'react-material-select/lib/index' {
  declare module.exports: any;
}

declare module 'react-material-select/webpack.build' {
  declare module.exports: any;
}

declare module 'react-material-select/webpack.config' {
  declare module.exports: any;
}

declare module 'react-material-select/webpack.make' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-material-select/dist/app.d6a0eabd0d1b15b6c337.js' {
  declare module.exports: $Exports<'react-material-select/dist/app.d6a0eabd0d1b15b6c337'>;
}
declare module 'react-material-select/dist/vendor.d6a0eabd0d1b15b6c337.js' {
  declare module.exports: $Exports<'react-material-select/dist/vendor.d6a0eabd0d1b15b6c337'>;
}
declare module 'react-material-select/lib/components/ReactMaterialSelect.js' {
  declare module.exports: $Exports<'react-material-select/lib/components/ReactMaterialSelect'>;
}
declare module 'react-material-select/lib/index.js' {
  declare module.exports: $Exports<'react-material-select/lib/index'>;
}
declare module 'react-material-select/webpack.build.js' {
  declare module.exports: $Exports<'react-material-select/webpack.build'>;
}
declare module 'react-material-select/webpack.config.js' {
  declare module.exports: $Exports<'react-material-select/webpack.config'>;
}
declare module 'react-material-select/webpack.make.js' {
  declare module.exports: $Exports<'react-material-select/webpack.make'>;
}
