// flow-typed signature: 3b84b4b308f54c84f52a7f8d363cbf24
// flow-typed version: <<STUB>>/react-responsive-mixin_v^0.4.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-responsive-mixin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-responsive-mixin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-responsive-mixin/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-responsive-mixin/index' {
  declare module.exports: $Exports<'react-responsive-mixin'>;
}
declare module 'react-responsive-mixin/index.js' {
  declare module.exports: $Exports<'react-responsive-mixin'>;
}
declare module 'react-responsive-mixin/webpack.config.js' {
  declare module.exports: $Exports<'react-responsive-mixin/webpack.config'>;
}
