// flow-typed signature: e20e422188d49d9c12eb3c41d12eba31
// flow-typed version: <<STUB>>/react-data-grid_vmaphubs/react-data-grid#34cda5225ce224b2803eb550fb433914cb8dd3e1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-data-grid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-data-grid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-data-grid/addons' {
  declare module.exports: any;
}

declare module 'react-data-grid/ci/publish/getCurrentVersion' {
  declare module.exports: any;
}

declare module 'react-data-grid/ci/publish/getNextVersion' {
  declare module.exports: any;
}

declare module 'react-data-grid/config/karma' {
  declare module.exports: any;
}

declare module 'react-data-grid/config/webpack.common' {
  declare module.exports: any;
}

declare module 'react-data-grid/config/webpack.react-data-grid' {
  declare module.exports: any;
}

declare module 'react-data-grid/config/webpack.ui-plugins' {
  declare module.exports: any;
}

declare module 'react-data-grid/dist/react-data-grid' {
  declare module.exports: any;
}

declare module 'react-data-grid/dist/react-data-grid.min' {
  declare module.exports: any;
}

declare module 'react-data-grid/dist/react-data-grid.ui-plugins' {
  declare module.exports: any;
}

declare module 'react-data-grid/dist/react-data-grid.ui-plugins.min' {
  declare module.exports: any;
}

declare module 'react-data-grid/docs/utils/generalUtils' {
  declare module.exports: any;
}

declare module 'react-data-grid/docs/utils/generateMarkdown' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/assets/js/affix' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/assets/js/bootstrap.min' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/assets/js/codeMirror' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/assets/js/docs' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/assets/js/dropdown' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/assets/js/google-map' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/assets/js/headroom.min' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/assets/js/html5shiv' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/assets/js/javascript' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/assets/js/jQuery.headroom.min' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/assets/js/jquery' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/assets/js/markdown' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/assets/js/react-router.min' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/assets/js/react-with-addons' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/assets/js/react' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/assets/js/ReactPlayground' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/assets/js/respond.min' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/assets/js/scrollspy' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/assets/js/template' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/components/BasicExample' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/components/ColsDescription' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/components/ExampleList' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/components/Navbar' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/components/QuickStartDescription' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/components/RenderGrid' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/components/RowsDescription' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/documentation' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/examples' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/index' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/scripts/documentation01-gettingstarted' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/scripts/documentation02-apireference' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/scripts/documentation03-components' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/scripts/example01-basic' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/scripts/example02-resizable-cols' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/scripts/example03-fixed-cols' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/scripts/example04-editable' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/scripts/example05-custom-formatters' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/scripts/example06-built-in-editors' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/scripts/example08-sortable-cols' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/scripts/example09-filterable-grid' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/scripts/example10-one-million-rows' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/scripts/example11-immutable-data' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/scripts/example12-customRowRenderer' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/scripts/example13-all-features' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/scripts/example14-all-features-immutable' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/scripts/example15-empty-rows' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/scripts/example16-cell-drag-down' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/scripts/example16-filterable-sortable-grid' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/scripts/example16-row-select' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/scripts/example17-single-row-select' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/scripts/example18-context-menu' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/scripts/example19-column-events' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/scripts/example20-cell-navigation' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/scripts/example21-cell-selection-events' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/scripts/FakeObjectDataStore' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/scripts/index' {
  declare module.exports: any;
}

declare module 'react-data-grid/examples/shared' {
  declare module.exports: any;
}

declare module 'react-data-grid/flow/libs/CellCopyPasteEvent' {
  declare module.exports: any;
}

declare module 'react-data-grid/flow/libs/CellDragEvent' {
  declare module.exports: any;
}

declare module 'react-data-grid/flow/libs/Editor' {
  declare module.exports: any;
}

declare module 'react-data-grid/flow/libs/SyntheticKeyboardEvent' {
  declare module.exports: any;
}

declare module 'react-data-grid/gulp/index' {
  declare module.exports: any;
}

declare module 'react-data-grid/gulp/tasks/browserSync' {
  declare module.exports: any;
}

declare module 'react-data-grid/gulp/tasks/bundle' {
  declare module.exports: any;
}

declare module 'react-data-grid/gulp/tasks/clean' {
  declare module.exports: any;
}

declare module 'react-data-grid/gulp/tasks/coveralls' {
  declare module.exports: any;
}

declare module 'react-data-grid/gulp/tasks/default' {
  declare module.exports: any;
}

declare module 'react-data-grid/gulp/tasks/dist' {
  declare module.exports: any;
}

declare module 'react-data-grid/gulp/tasks/docs' {
  declare module.exports: any;
}

declare module 'react-data-grid/gulp/tasks/docsGen' {
  declare module.exports: any;
}

declare module 'react-data-grid/gulp/tasks/eslint' {
  declare module.exports: any;
}

declare module 'react-data-grid/gulp/tasks/examples' {
  declare module.exports: any;
}

declare module 'react-data-grid/gulp/tasks/flow' {
  declare module.exports: any;
}

declare module 'react-data-grid/gulp/tasks/setWatch' {
  declare module.exports: any;
}

declare module 'react-data-grid/gulp/tasks/tests' {
  declare module.exports: any;
}

declare module 'react-data-grid/gulp/tasks/watch' {
  declare module.exports: any;
}

declare module 'react-data-grid/gulp/util/bundleBuilder' {
  declare module.exports: any;
}

declare module 'react-data-grid/gulp/util/bundleLogger' {
  declare module.exports: any;
}

declare module 'react-data-grid/gulp/util/handleErrors' {
  declare module.exports: any;
}

declare module 'react-data-grid/gulp/util/scriptFilter' {
  declare module.exports: any;
}

declare module 'react-data-grid/gulpfile' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/__tests__/Canvas.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/__tests__/Cell.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/__tests__/ColumnMetrics.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/__tests__/ColumnUtils.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/__tests__/Grid.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/__tests__/GridPropHelpers' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/__tests__/Header.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/__tests__/HeaderCell.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/__tests__/HeaderRow.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/__tests__/ReactDataGrid.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/__tests__/Row.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/__tests__/RowsContainer.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/__tests__/data/MockStateObject' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/__tests__/Grid.integration-spec' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/__tests__/Grid.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/__tests__/GridRunner' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/cells/headerCells/FilterableHeaderCell' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/cells/headerCells/SortableHeaderCell' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/data/DataStore' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/data/index' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/editors/__tests__/AutoCompleteEditor-integration.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/editors/__tests__/AutoCompleteEditor.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/editors/__tests__/CheckboxEditor.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/editors/__tests__/DropDownEditor.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/editors/__tests__/EditorContainer.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/editors/__tests__/SimpleTextEditor.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/editors/AutoCompleteEditor' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/editors/AutoCompleteTokensEditor' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/editors/CheckboxEditor' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/editors/DateRangeEditor' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/editors/DropDownEditor' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/editors/EditorBase' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/editors/EditorContainer' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/editors/index' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/editors/SimpleTextEditor' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/editors/widgets/DateRangeFilter' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/formatters/DateRangeFormatter' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/formatters/ImageFormatter' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/formatters/index' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/formatters/SimpleCellFormatter' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/index' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/menu/__tests__/ContextMenu.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/menu/__tests__/MenuHeader.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/menu/ContextMenu' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/menu/index' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/menu/MenuHeader' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/toolbars/Toolbar' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/addons/utils/isFunction' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/Canvas' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/Cell' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/ColumnComparer' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/ColumnMetrics' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/ColumnMetricsMixin' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/ColumnUtils' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/DOMMetrics' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/Draggable' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/getScrollbarSize' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/getWindowSize' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/Grid' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/GridScrollMixin' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/Header' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/HeaderCell' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/HeaderCellType' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/HeaderRow' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/index' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/KeyboardHandlerMixin' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/PropTypeShapes/CellMetaDataShape' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/PropTypeShapes/ExcelColumn' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/ReactDataGrid' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/ResizeHandle' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/Row' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/RowsContainer' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/RowUtils' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/ScrollShim' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/shallowCloneObject' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/Viewport' {
  declare module.exports: any;
}

declare module 'react-data-grid/src/ViewportScrollMixin' {
  declare module.exports: any;
}

declare module 'react-data-grid/test/browser/common.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid/test/browser/helpers' {
  declare module.exports: any;
}

declare module 'react-data-grid/test/browser/Viewport/scroll.spec' {
  declare module.exports: any;
}

declare module 'react-data-grid/test/FullTests' {
  declare module.exports: any;
}

declare module 'react-data-grid/test/integrationTests' {
  declare module.exports: any;
}

declare module 'react-data-grid/test/PropTestUtils' {
  declare module.exports: any;
}

declare module 'react-data-grid/test/rewireModule' {
  declare module.exports: any;
}

declare module 'react-data-grid/test/StubComponent' {
  declare module.exports: any;
}

declare module 'react-data-grid/test/unitTests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-data-grid/addons.js' {
  declare module.exports: $Exports<'react-data-grid/addons'>;
}
declare module 'react-data-grid/ci/publish/getCurrentVersion.js' {
  declare module.exports: $Exports<'react-data-grid/ci/publish/getCurrentVersion'>;
}
declare module 'react-data-grid/ci/publish/getNextVersion.js' {
  declare module.exports: $Exports<'react-data-grid/ci/publish/getNextVersion'>;
}
declare module 'react-data-grid/config/karma.js' {
  declare module.exports: $Exports<'react-data-grid/config/karma'>;
}
declare module 'react-data-grid/config/webpack.common.js' {
  declare module.exports: $Exports<'react-data-grid/config/webpack.common'>;
}
declare module 'react-data-grid/config/webpack.react-data-grid.js' {
  declare module.exports: $Exports<'react-data-grid/config/webpack.react-data-grid'>;
}
declare module 'react-data-grid/config/webpack.ui-plugins.js' {
  declare module.exports: $Exports<'react-data-grid/config/webpack.ui-plugins'>;
}
declare module 'react-data-grid/dist/react-data-grid.js' {
  declare module.exports: $Exports<'react-data-grid/dist/react-data-grid'>;
}
declare module 'react-data-grid/dist/react-data-grid.min.js' {
  declare module.exports: $Exports<'react-data-grid/dist/react-data-grid.min'>;
}
declare module 'react-data-grid/dist/react-data-grid.ui-plugins.js' {
  declare module.exports: $Exports<'react-data-grid/dist/react-data-grid.ui-plugins'>;
}
declare module 'react-data-grid/dist/react-data-grid.ui-plugins.min.js' {
  declare module.exports: $Exports<'react-data-grid/dist/react-data-grid.ui-plugins.min'>;
}
declare module 'react-data-grid/docs/utils/generalUtils.js' {
  declare module.exports: $Exports<'react-data-grid/docs/utils/generalUtils'>;
}
declare module 'react-data-grid/docs/utils/generateMarkdown.js' {
  declare module.exports: $Exports<'react-data-grid/docs/utils/generateMarkdown'>;
}
declare module 'react-data-grid/examples/assets/js/affix.js' {
  declare module.exports: $Exports<'react-data-grid/examples/assets/js/affix'>;
}
declare module 'react-data-grid/examples/assets/js/bootstrap.min.js' {
  declare module.exports: $Exports<'react-data-grid/examples/assets/js/bootstrap.min'>;
}
declare module 'react-data-grid/examples/assets/js/codeMirror.js' {
  declare module.exports: $Exports<'react-data-grid/examples/assets/js/codeMirror'>;
}
declare module 'react-data-grid/examples/assets/js/docs.js' {
  declare module.exports: $Exports<'react-data-grid/examples/assets/js/docs'>;
}
declare module 'react-data-grid/examples/assets/js/dropdown.js' {
  declare module.exports: $Exports<'react-data-grid/examples/assets/js/dropdown'>;
}
declare module 'react-data-grid/examples/assets/js/google-map.js' {
  declare module.exports: $Exports<'react-data-grid/examples/assets/js/google-map'>;
}
declare module 'react-data-grid/examples/assets/js/headroom.min.js' {
  declare module.exports: $Exports<'react-data-grid/examples/assets/js/headroom.min'>;
}
declare module 'react-data-grid/examples/assets/js/html5shiv.js' {
  declare module.exports: $Exports<'react-data-grid/examples/assets/js/html5shiv'>;
}
declare module 'react-data-grid/examples/assets/js/javascript.js' {
  declare module.exports: $Exports<'react-data-grid/examples/assets/js/javascript'>;
}
declare module 'react-data-grid/examples/assets/js/jQuery.headroom.min.js' {
  declare module.exports: $Exports<'react-data-grid/examples/assets/js/jQuery.headroom.min'>;
}
declare module 'react-data-grid/examples/assets/js/jquery.js' {
  declare module.exports: $Exports<'react-data-grid/examples/assets/js/jquery'>;
}
declare module 'react-data-grid/examples/assets/js/markdown.js' {
  declare module.exports: $Exports<'react-data-grid/examples/assets/js/markdown'>;
}
declare module 'react-data-grid/examples/assets/js/react-router.min.js' {
  declare module.exports: $Exports<'react-data-grid/examples/assets/js/react-router.min'>;
}
declare module 'react-data-grid/examples/assets/js/react-with-addons.js' {
  declare module.exports: $Exports<'react-data-grid/examples/assets/js/react-with-addons'>;
}
declare module 'react-data-grid/examples/assets/js/react.js' {
  declare module.exports: $Exports<'react-data-grid/examples/assets/js/react'>;
}
declare module 'react-data-grid/examples/assets/js/ReactPlayground.js' {
  declare module.exports: $Exports<'react-data-grid/examples/assets/js/ReactPlayground'>;
}
declare module 'react-data-grid/examples/assets/js/respond.min.js' {
  declare module.exports: $Exports<'react-data-grid/examples/assets/js/respond.min'>;
}
declare module 'react-data-grid/examples/assets/js/scrollspy.js' {
  declare module.exports: $Exports<'react-data-grid/examples/assets/js/scrollspy'>;
}
declare module 'react-data-grid/examples/assets/js/template.js' {
  declare module.exports: $Exports<'react-data-grid/examples/assets/js/template'>;
}
declare module 'react-data-grid/examples/components/BasicExample.js' {
  declare module.exports: $Exports<'react-data-grid/examples/components/BasicExample'>;
}
declare module 'react-data-grid/examples/components/ColsDescription.js' {
  declare module.exports: $Exports<'react-data-grid/examples/components/ColsDescription'>;
}
declare module 'react-data-grid/examples/components/ExampleList.js' {
  declare module.exports: $Exports<'react-data-grid/examples/components/ExampleList'>;
}
declare module 'react-data-grid/examples/components/Navbar.js' {
  declare module.exports: $Exports<'react-data-grid/examples/components/Navbar'>;
}
declare module 'react-data-grid/examples/components/QuickStartDescription.js' {
  declare module.exports: $Exports<'react-data-grid/examples/components/QuickStartDescription'>;
}
declare module 'react-data-grid/examples/components/RenderGrid.js' {
  declare module.exports: $Exports<'react-data-grid/examples/components/RenderGrid'>;
}
declare module 'react-data-grid/examples/components/RowsDescription.js' {
  declare module.exports: $Exports<'react-data-grid/examples/components/RowsDescription'>;
}
declare module 'react-data-grid/examples/documentation.js' {
  declare module.exports: $Exports<'react-data-grid/examples/documentation'>;
}
declare module 'react-data-grid/examples/examples.js' {
  declare module.exports: $Exports<'react-data-grid/examples/examples'>;
}
declare module 'react-data-grid/examples/index.js' {
  declare module.exports: $Exports<'react-data-grid/examples/index'>;
}
declare module 'react-data-grid/examples/scripts/documentation01-gettingstarted.js' {
  declare module.exports: $Exports<'react-data-grid/examples/scripts/documentation01-gettingstarted'>;
}
declare module 'react-data-grid/examples/scripts/documentation02-apireference.js' {
  declare module.exports: $Exports<'react-data-grid/examples/scripts/documentation02-apireference'>;
}
declare module 'react-data-grid/examples/scripts/documentation03-components.js' {
  declare module.exports: $Exports<'react-data-grid/examples/scripts/documentation03-components'>;
}
declare module 'react-data-grid/examples/scripts/example01-basic.js' {
  declare module.exports: $Exports<'react-data-grid/examples/scripts/example01-basic'>;
}
declare module 'react-data-grid/examples/scripts/example02-resizable-cols.js' {
  declare module.exports: $Exports<'react-data-grid/examples/scripts/example02-resizable-cols'>;
}
declare module 'react-data-grid/examples/scripts/example03-fixed-cols.js' {
  declare module.exports: $Exports<'react-data-grid/examples/scripts/example03-fixed-cols'>;
}
declare module 'react-data-grid/examples/scripts/example04-editable.js' {
  declare module.exports: $Exports<'react-data-grid/examples/scripts/example04-editable'>;
}
declare module 'react-data-grid/examples/scripts/example05-custom-formatters.js' {
  declare module.exports: $Exports<'react-data-grid/examples/scripts/example05-custom-formatters'>;
}
declare module 'react-data-grid/examples/scripts/example06-built-in-editors.js' {
  declare module.exports: $Exports<'react-data-grid/examples/scripts/example06-built-in-editors'>;
}
declare module 'react-data-grid/examples/scripts/example08-sortable-cols.js' {
  declare module.exports: $Exports<'react-data-grid/examples/scripts/example08-sortable-cols'>;
}
declare module 'react-data-grid/examples/scripts/example09-filterable-grid.js' {
  declare module.exports: $Exports<'react-data-grid/examples/scripts/example09-filterable-grid'>;
}
declare module 'react-data-grid/examples/scripts/example10-one-million-rows.js' {
  declare module.exports: $Exports<'react-data-grid/examples/scripts/example10-one-million-rows'>;
}
declare module 'react-data-grid/examples/scripts/example11-immutable-data.js' {
  declare module.exports: $Exports<'react-data-grid/examples/scripts/example11-immutable-data'>;
}
declare module 'react-data-grid/examples/scripts/example12-customRowRenderer.js' {
  declare module.exports: $Exports<'react-data-grid/examples/scripts/example12-customRowRenderer'>;
}
declare module 'react-data-grid/examples/scripts/example13-all-features.js' {
  declare module.exports: $Exports<'react-data-grid/examples/scripts/example13-all-features'>;
}
declare module 'react-data-grid/examples/scripts/example14-all-features-immutable.js' {
  declare module.exports: $Exports<'react-data-grid/examples/scripts/example14-all-features-immutable'>;
}
declare module 'react-data-grid/examples/scripts/example15-empty-rows.js' {
  declare module.exports: $Exports<'react-data-grid/examples/scripts/example15-empty-rows'>;
}
declare module 'react-data-grid/examples/scripts/example16-cell-drag-down.js' {
  declare module.exports: $Exports<'react-data-grid/examples/scripts/example16-cell-drag-down'>;
}
declare module 'react-data-grid/examples/scripts/example16-filterable-sortable-grid.js' {
  declare module.exports: $Exports<'react-data-grid/examples/scripts/example16-filterable-sortable-grid'>;
}
declare module 'react-data-grid/examples/scripts/example16-row-select.js' {
  declare module.exports: $Exports<'react-data-grid/examples/scripts/example16-row-select'>;
}
declare module 'react-data-grid/examples/scripts/example17-single-row-select.js' {
  declare module.exports: $Exports<'react-data-grid/examples/scripts/example17-single-row-select'>;
}
declare module 'react-data-grid/examples/scripts/example18-context-menu.js' {
  declare module.exports: $Exports<'react-data-grid/examples/scripts/example18-context-menu'>;
}
declare module 'react-data-grid/examples/scripts/example19-column-events.js' {
  declare module.exports: $Exports<'react-data-grid/examples/scripts/example19-column-events'>;
}
declare module 'react-data-grid/examples/scripts/example20-cell-navigation.js' {
  declare module.exports: $Exports<'react-data-grid/examples/scripts/example20-cell-navigation'>;
}
declare module 'react-data-grid/examples/scripts/example21-cell-selection-events.js' {
  declare module.exports: $Exports<'react-data-grid/examples/scripts/example21-cell-selection-events'>;
}
declare module 'react-data-grid/examples/scripts/FakeObjectDataStore.js' {
  declare module.exports: $Exports<'react-data-grid/examples/scripts/FakeObjectDataStore'>;
}
declare module 'react-data-grid/examples/scripts/index.js' {
  declare module.exports: $Exports<'react-data-grid/examples/scripts/index'>;
}
declare module 'react-data-grid/examples/shared.js' {
  declare module.exports: $Exports<'react-data-grid/examples/shared'>;
}
declare module 'react-data-grid/flow/libs/CellCopyPasteEvent.js' {
  declare module.exports: $Exports<'react-data-grid/flow/libs/CellCopyPasteEvent'>;
}
declare module 'react-data-grid/flow/libs/CellDragEvent.js' {
  declare module.exports: $Exports<'react-data-grid/flow/libs/CellDragEvent'>;
}
declare module 'react-data-grid/flow/libs/Editor.js' {
  declare module.exports: $Exports<'react-data-grid/flow/libs/Editor'>;
}
declare module 'react-data-grid/flow/libs/SyntheticKeyboardEvent.js' {
  declare module.exports: $Exports<'react-data-grid/flow/libs/SyntheticKeyboardEvent'>;
}
declare module 'react-data-grid/gulp/index.js' {
  declare module.exports: $Exports<'react-data-grid/gulp/index'>;
}
declare module 'react-data-grid/gulp/tasks/browserSync.js' {
  declare module.exports: $Exports<'react-data-grid/gulp/tasks/browserSync'>;
}
declare module 'react-data-grid/gulp/tasks/bundle.js' {
  declare module.exports: $Exports<'react-data-grid/gulp/tasks/bundle'>;
}
declare module 'react-data-grid/gulp/tasks/clean.js' {
  declare module.exports: $Exports<'react-data-grid/gulp/tasks/clean'>;
}
declare module 'react-data-grid/gulp/tasks/coveralls.js' {
  declare module.exports: $Exports<'react-data-grid/gulp/tasks/coveralls'>;
}
declare module 'react-data-grid/gulp/tasks/default.js' {
  declare module.exports: $Exports<'react-data-grid/gulp/tasks/default'>;
}
declare module 'react-data-grid/gulp/tasks/dist.js' {
  declare module.exports: $Exports<'react-data-grid/gulp/tasks/dist'>;
}
declare module 'react-data-grid/gulp/tasks/docs.js' {
  declare module.exports: $Exports<'react-data-grid/gulp/tasks/docs'>;
}
declare module 'react-data-grid/gulp/tasks/docsGen.js' {
  declare module.exports: $Exports<'react-data-grid/gulp/tasks/docsGen'>;
}
declare module 'react-data-grid/gulp/tasks/eslint.js' {
  declare module.exports: $Exports<'react-data-grid/gulp/tasks/eslint'>;
}
declare module 'react-data-grid/gulp/tasks/examples.js' {
  declare module.exports: $Exports<'react-data-grid/gulp/tasks/examples'>;
}
declare module 'react-data-grid/gulp/tasks/flow.js' {
  declare module.exports: $Exports<'react-data-grid/gulp/tasks/flow'>;
}
declare module 'react-data-grid/gulp/tasks/setWatch.js' {
  declare module.exports: $Exports<'react-data-grid/gulp/tasks/setWatch'>;
}
declare module 'react-data-grid/gulp/tasks/tests.js' {
  declare module.exports: $Exports<'react-data-grid/gulp/tasks/tests'>;
}
declare module 'react-data-grid/gulp/tasks/watch.js' {
  declare module.exports: $Exports<'react-data-grid/gulp/tasks/watch'>;
}
declare module 'react-data-grid/gulp/util/bundleBuilder.js' {
  declare module.exports: $Exports<'react-data-grid/gulp/util/bundleBuilder'>;
}
declare module 'react-data-grid/gulp/util/bundleLogger.js' {
  declare module.exports: $Exports<'react-data-grid/gulp/util/bundleLogger'>;
}
declare module 'react-data-grid/gulp/util/handleErrors.js' {
  declare module.exports: $Exports<'react-data-grid/gulp/util/handleErrors'>;
}
declare module 'react-data-grid/gulp/util/scriptFilter.js' {
  declare module.exports: $Exports<'react-data-grid/gulp/util/scriptFilter'>;
}
declare module 'react-data-grid/gulpfile.js' {
  declare module.exports: $Exports<'react-data-grid/gulpfile'>;
}
declare module 'react-data-grid/index' {
  declare module.exports: $Exports<'react-data-grid'>;
}
declare module 'react-data-grid/index.js' {
  declare module.exports: $Exports<'react-data-grid'>;
}
declare module 'react-data-grid/src/__tests__/Canvas.spec.js' {
  declare module.exports: $Exports<'react-data-grid/src/__tests__/Canvas.spec'>;
}
declare module 'react-data-grid/src/__tests__/Cell.spec.js' {
  declare module.exports: $Exports<'react-data-grid/src/__tests__/Cell.spec'>;
}
declare module 'react-data-grid/src/__tests__/ColumnMetrics.spec.js' {
  declare module.exports: $Exports<'react-data-grid/src/__tests__/ColumnMetrics.spec'>;
}
declare module 'react-data-grid/src/__tests__/ColumnUtils.spec.js' {
  declare module.exports: $Exports<'react-data-grid/src/__tests__/ColumnUtils.spec'>;
}
declare module 'react-data-grid/src/__tests__/Grid.spec.js' {
  declare module.exports: $Exports<'react-data-grid/src/__tests__/Grid.spec'>;
}
declare module 'react-data-grid/src/__tests__/GridPropHelpers.js' {
  declare module.exports: $Exports<'react-data-grid/src/__tests__/GridPropHelpers'>;
}
declare module 'react-data-grid/src/__tests__/Header.spec.js' {
  declare module.exports: $Exports<'react-data-grid/src/__tests__/Header.spec'>;
}
declare module 'react-data-grid/src/__tests__/HeaderCell.spec.js' {
  declare module.exports: $Exports<'react-data-grid/src/__tests__/HeaderCell.spec'>;
}
declare module 'react-data-grid/src/__tests__/HeaderRow.spec.js' {
  declare module.exports: $Exports<'react-data-grid/src/__tests__/HeaderRow.spec'>;
}
declare module 'react-data-grid/src/__tests__/ReactDataGrid.spec.js' {
  declare module.exports: $Exports<'react-data-grid/src/__tests__/ReactDataGrid.spec'>;
}
declare module 'react-data-grid/src/__tests__/Row.spec.js' {
  declare module.exports: $Exports<'react-data-grid/src/__tests__/Row.spec'>;
}
declare module 'react-data-grid/src/__tests__/RowsContainer.spec.js' {
  declare module.exports: $Exports<'react-data-grid/src/__tests__/RowsContainer.spec'>;
}
declare module 'react-data-grid/src/addons/__tests__/data/MockStateObject.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/__tests__/data/MockStateObject'>;
}
declare module 'react-data-grid/src/addons/__tests__/Grid.integration-spec.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/__tests__/Grid.integration-spec'>;
}
declare module 'react-data-grid/src/addons/__tests__/Grid.spec.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/__tests__/Grid.spec'>;
}
declare module 'react-data-grid/src/addons/__tests__/GridRunner.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/__tests__/GridRunner'>;
}
declare module 'react-data-grid/src/addons/cells/headerCells/FilterableHeaderCell.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/cells/headerCells/FilterableHeaderCell'>;
}
declare module 'react-data-grid/src/addons/cells/headerCells/SortableHeaderCell.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/cells/headerCells/SortableHeaderCell'>;
}
declare module 'react-data-grid/src/addons/data/DataStore.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/data/DataStore'>;
}
declare module 'react-data-grid/src/addons/data/index.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/data/index'>;
}
declare module 'react-data-grid/src/addons/editors/__tests__/AutoCompleteEditor-integration.spec.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/editors/__tests__/AutoCompleteEditor-integration.spec'>;
}
declare module 'react-data-grid/src/addons/editors/__tests__/AutoCompleteEditor.spec.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/editors/__tests__/AutoCompleteEditor.spec'>;
}
declare module 'react-data-grid/src/addons/editors/__tests__/CheckboxEditor.spec.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/editors/__tests__/CheckboxEditor.spec'>;
}
declare module 'react-data-grid/src/addons/editors/__tests__/DropDownEditor.spec.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/editors/__tests__/DropDownEditor.spec'>;
}
declare module 'react-data-grid/src/addons/editors/__tests__/EditorContainer.spec.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/editors/__tests__/EditorContainer.spec'>;
}
declare module 'react-data-grid/src/addons/editors/__tests__/SimpleTextEditor.spec.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/editors/__tests__/SimpleTextEditor.spec'>;
}
declare module 'react-data-grid/src/addons/editors/AutoCompleteEditor.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/editors/AutoCompleteEditor'>;
}
declare module 'react-data-grid/src/addons/editors/AutoCompleteTokensEditor.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/editors/AutoCompleteTokensEditor'>;
}
declare module 'react-data-grid/src/addons/editors/CheckboxEditor.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/editors/CheckboxEditor'>;
}
declare module 'react-data-grid/src/addons/editors/DateRangeEditor.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/editors/DateRangeEditor'>;
}
declare module 'react-data-grid/src/addons/editors/DropDownEditor.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/editors/DropDownEditor'>;
}
declare module 'react-data-grid/src/addons/editors/EditorBase.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/editors/EditorBase'>;
}
declare module 'react-data-grid/src/addons/editors/EditorContainer.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/editors/EditorContainer'>;
}
declare module 'react-data-grid/src/addons/editors/index.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/editors/index'>;
}
declare module 'react-data-grid/src/addons/editors/SimpleTextEditor.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/editors/SimpleTextEditor'>;
}
declare module 'react-data-grid/src/addons/editors/widgets/DateRangeFilter.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/editors/widgets/DateRangeFilter'>;
}
declare module 'react-data-grid/src/addons/formatters/DateRangeFormatter.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/formatters/DateRangeFormatter'>;
}
declare module 'react-data-grid/src/addons/formatters/ImageFormatter.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/formatters/ImageFormatter'>;
}
declare module 'react-data-grid/src/addons/formatters/index.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/formatters/index'>;
}
declare module 'react-data-grid/src/addons/formatters/SimpleCellFormatter.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/formatters/SimpleCellFormatter'>;
}
declare module 'react-data-grid/src/addons/index.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/index'>;
}
declare module 'react-data-grid/src/addons/menu/__tests__/ContextMenu.spec.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/menu/__tests__/ContextMenu.spec'>;
}
declare module 'react-data-grid/src/addons/menu/__tests__/MenuHeader.spec.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/menu/__tests__/MenuHeader.spec'>;
}
declare module 'react-data-grid/src/addons/menu/ContextMenu.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/menu/ContextMenu'>;
}
declare module 'react-data-grid/src/addons/menu/index.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/menu/index'>;
}
declare module 'react-data-grid/src/addons/menu/MenuHeader.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/menu/MenuHeader'>;
}
declare module 'react-data-grid/src/addons/toolbars/Toolbar.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/toolbars/Toolbar'>;
}
declare module 'react-data-grid/src/addons/utils/isFunction.js' {
  declare module.exports: $Exports<'react-data-grid/src/addons/utils/isFunction'>;
}
declare module 'react-data-grid/src/Canvas.js' {
  declare module.exports: $Exports<'react-data-grid/src/Canvas'>;
}
declare module 'react-data-grid/src/Cell.js' {
  declare module.exports: $Exports<'react-data-grid/src/Cell'>;
}
declare module 'react-data-grid/src/ColumnComparer.js' {
  declare module.exports: $Exports<'react-data-grid/src/ColumnComparer'>;
}
declare module 'react-data-grid/src/ColumnMetrics.js' {
  declare module.exports: $Exports<'react-data-grid/src/ColumnMetrics'>;
}
declare module 'react-data-grid/src/ColumnMetricsMixin.js' {
  declare module.exports: $Exports<'react-data-grid/src/ColumnMetricsMixin'>;
}
declare module 'react-data-grid/src/ColumnUtils.js' {
  declare module.exports: $Exports<'react-data-grid/src/ColumnUtils'>;
}
declare module 'react-data-grid/src/DOMMetrics.js' {
  declare module.exports: $Exports<'react-data-grid/src/DOMMetrics'>;
}
declare module 'react-data-grid/src/Draggable.js' {
  declare module.exports: $Exports<'react-data-grid/src/Draggable'>;
}
declare module 'react-data-grid/src/getScrollbarSize.js' {
  declare module.exports: $Exports<'react-data-grid/src/getScrollbarSize'>;
}
declare module 'react-data-grid/src/getWindowSize.js' {
  declare module.exports: $Exports<'react-data-grid/src/getWindowSize'>;
}
declare module 'react-data-grid/src/Grid.js' {
  declare module.exports: $Exports<'react-data-grid/src/Grid'>;
}
declare module 'react-data-grid/src/GridScrollMixin.js' {
  declare module.exports: $Exports<'react-data-grid/src/GridScrollMixin'>;
}
declare module 'react-data-grid/src/Header.js' {
  declare module.exports: $Exports<'react-data-grid/src/Header'>;
}
declare module 'react-data-grid/src/HeaderCell.js' {
  declare module.exports: $Exports<'react-data-grid/src/HeaderCell'>;
}
declare module 'react-data-grid/src/HeaderCellType.js' {
  declare module.exports: $Exports<'react-data-grid/src/HeaderCellType'>;
}
declare module 'react-data-grid/src/HeaderRow.js' {
  declare module.exports: $Exports<'react-data-grid/src/HeaderRow'>;
}
declare module 'react-data-grid/src/index.js' {
  declare module.exports: $Exports<'react-data-grid/src/index'>;
}
declare module 'react-data-grid/src/KeyboardHandlerMixin.js' {
  declare module.exports: $Exports<'react-data-grid/src/KeyboardHandlerMixin'>;
}
declare module 'react-data-grid/src/PropTypeShapes/CellMetaDataShape.js' {
  declare module.exports: $Exports<'react-data-grid/src/PropTypeShapes/CellMetaDataShape'>;
}
declare module 'react-data-grid/src/PropTypeShapes/ExcelColumn.js' {
  declare module.exports: $Exports<'react-data-grid/src/PropTypeShapes/ExcelColumn'>;
}
declare module 'react-data-grid/src/ReactDataGrid.js' {
  declare module.exports: $Exports<'react-data-grid/src/ReactDataGrid'>;
}
declare module 'react-data-grid/src/ResizeHandle.js' {
  declare module.exports: $Exports<'react-data-grid/src/ResizeHandle'>;
}
declare module 'react-data-grid/src/Row.js' {
  declare module.exports: $Exports<'react-data-grid/src/Row'>;
}
declare module 'react-data-grid/src/RowsContainer.js' {
  declare module.exports: $Exports<'react-data-grid/src/RowsContainer'>;
}
declare module 'react-data-grid/src/RowUtils.js' {
  declare module.exports: $Exports<'react-data-grid/src/RowUtils'>;
}
declare module 'react-data-grid/src/ScrollShim.js' {
  declare module.exports: $Exports<'react-data-grid/src/ScrollShim'>;
}
declare module 'react-data-grid/src/shallowCloneObject.js' {
  declare module.exports: $Exports<'react-data-grid/src/shallowCloneObject'>;
}
declare module 'react-data-grid/src/Viewport.js' {
  declare module.exports: $Exports<'react-data-grid/src/Viewport'>;
}
declare module 'react-data-grid/src/ViewportScrollMixin.js' {
  declare module.exports: $Exports<'react-data-grid/src/ViewportScrollMixin'>;
}
declare module 'react-data-grid/test/browser/common.spec.js' {
  declare module.exports: $Exports<'react-data-grid/test/browser/common.spec'>;
}
declare module 'react-data-grid/test/browser/helpers.js' {
  declare module.exports: $Exports<'react-data-grid/test/browser/helpers'>;
}
declare module 'react-data-grid/test/browser/Viewport/scroll.spec.js' {
  declare module.exports: $Exports<'react-data-grid/test/browser/Viewport/scroll.spec'>;
}
declare module 'react-data-grid/test/FullTests.jsx' {
  declare module.exports: $Exports<'react-data-grid/test/FullTests'>;
}
declare module 'react-data-grid/test/integrationTests.jsx' {
  declare module.exports: $Exports<'react-data-grid/test/integrationTests'>;
}
declare module 'react-data-grid/test/PropTestUtils.js' {
  declare module.exports: $Exports<'react-data-grid/test/PropTestUtils'>;
}
declare module 'react-data-grid/test/rewireModule.js' {
  declare module.exports: $Exports<'react-data-grid/test/rewireModule'>;
}
declare module 'react-data-grid/test/StubComponent.js' {
  declare module.exports: $Exports<'react-data-grid/test/StubComponent'>;
}
declare module 'react-data-grid/test/unitTests.jsx' {
  declare module.exports: $Exports<'react-data-grid/test/unitTests'>;
}
