// flow-typed signature: e8bd9812d8d8d2964e3c248ec042e8e2
// flow-typed version: <<STUB>>/react-colorpickr_vopenmaphub/react-colorpickr#29c5725cdfd0fba529fe211b930b0c23dffe0649/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-colorpickr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-colorpickr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-colorpickr/dist/colorfunc' {
  declare module.exports: any;
}

declare module 'react-colorpickr/dist/colorpickr' {
  declare module.exports: any;
}

declare module 'react-colorpickr/dist/components/gradients/h-gradient' {
  declare module.exports: any;
}

declare module 'react-colorpickr/dist/components/gradients/rgb-gradient' {
  declare module.exports: any;
}

declare module 'react-colorpickr/dist/components/gradients/sv-gradient' {
  declare module.exports: any;
}

declare module 'react-colorpickr/dist/components/inputs/h-input' {
  declare module.exports: any;
}

declare module 'react-colorpickr/dist/components/inputs/mode-input' {
  declare module.exports: any;
}

declare module 'react-colorpickr/dist/components/inputs/number-input' {
  declare module.exports: any;
}

declare module 'react-colorpickr/dist/components/inputs/rgb-input' {
  declare module.exports: any;
}

declare module 'react-colorpickr/dist/components/inputs/sv-alpha-input' {
  declare module.exports: any;
}

declare module 'react-colorpickr/dist/gradients/h-gradient' {
  declare module.exports: any;
}

declare module 'react-colorpickr/dist/gradients/rgb-gradient' {
  declare module.exports: any;
}

declare module 'react-colorpickr/dist/gradients/sv-gradient' {
  declare module.exports: any;
}

declare module 'react-colorpickr/dist/inputs/color-inputs' {
  declare module.exports: any;
}

declare module 'react-colorpickr/dist/inputs/h-input' {
  declare module.exports: any;
}

declare module 'react-colorpickr/dist/inputs/mode-input' {
  declare module.exports: any;
}

declare module 'react-colorpickr/dist/inputs/number-input' {
  declare module.exports: any;
}

declare module 'react-colorpickr/dist/inputs/rgb-input' {
  declare module.exports: any;
}

declare module 'react-colorpickr/dist/inputs/sv-alpha-input' {
  declare module.exports: any;
}

declare module 'react-colorpickr/dist/xy' {
  declare module.exports: any;
}

declare module 'react-colorpickr/example/bundle' {
  declare module.exports: any;
}

declare module 'react-colorpickr/example/index' {
  declare module.exports: any;
}

declare module 'react-colorpickr/src/colorfunc' {
  declare module.exports: any;
}

declare module 'react-colorpickr/src/colorpickr' {
  declare module.exports: any;
}

declare module 'react-colorpickr/src/components/gradients/h-gradient' {
  declare module.exports: any;
}

declare module 'react-colorpickr/src/components/gradients/rgb-gradient' {
  declare module.exports: any;
}

declare module 'react-colorpickr/src/components/gradients/sv-gradient' {
  declare module.exports: any;
}

declare module 'react-colorpickr/src/components/inputs/h-input' {
  declare module.exports: any;
}

declare module 'react-colorpickr/src/components/inputs/mode-input' {
  declare module.exports: any;
}

declare module 'react-colorpickr/src/components/inputs/number-input' {
  declare module.exports: any;
}

declare module 'react-colorpickr/src/components/inputs/rgb-input' {
  declare module.exports: any;
}

declare module 'react-colorpickr/src/components/inputs/sv-alpha-input' {
  declare module.exports: any;
}

declare module 'react-colorpickr/src/xy' {
  declare module.exports: any;
}

declare module 'react-colorpickr/test/colorfunc' {
  declare module.exports: any;
}

declare module 'react-colorpickr/test/component' {
  declare module.exports: any;
}

declare module 'react-colorpickr/test/components/gradients/h-gradient_test' {
  declare module.exports: any;
}

declare module 'react-colorpickr/test/components/gradients/rgb-gradient_test' {
  declare module.exports: any;
}

declare module 'react-colorpickr/test/components/gradients/sv-gradient_test' {
  declare module.exports: any;
}

declare module 'react-colorpickr/test/components/inputs/h-input_test' {
  declare module.exports: any;
}

declare module 'react-colorpickr/test/components/inputs/mode-input_test' {
  declare module.exports: any;
}

declare module 'react-colorpickr/test/components/inputs/rgb-input_test' {
  declare module.exports: any;
}

declare module 'react-colorpickr/test/components/inputs/sv-alpha-input_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-colorpickr/dist/colorfunc.js' {
  declare module.exports: $Exports<'react-colorpickr/dist/colorfunc'>;
}
declare module 'react-colorpickr/dist/colorpickr.js' {
  declare module.exports: $Exports<'react-colorpickr/dist/colorpickr'>;
}
declare module 'react-colorpickr/dist/components/gradients/h-gradient.js' {
  declare module.exports: $Exports<'react-colorpickr/dist/components/gradients/h-gradient'>;
}
declare module 'react-colorpickr/dist/components/gradients/rgb-gradient.js' {
  declare module.exports: $Exports<'react-colorpickr/dist/components/gradients/rgb-gradient'>;
}
declare module 'react-colorpickr/dist/components/gradients/sv-gradient.js' {
  declare module.exports: $Exports<'react-colorpickr/dist/components/gradients/sv-gradient'>;
}
declare module 'react-colorpickr/dist/components/inputs/h-input.js' {
  declare module.exports: $Exports<'react-colorpickr/dist/components/inputs/h-input'>;
}
declare module 'react-colorpickr/dist/components/inputs/mode-input.js' {
  declare module.exports: $Exports<'react-colorpickr/dist/components/inputs/mode-input'>;
}
declare module 'react-colorpickr/dist/components/inputs/number-input.js' {
  declare module.exports: $Exports<'react-colorpickr/dist/components/inputs/number-input'>;
}
declare module 'react-colorpickr/dist/components/inputs/rgb-input.js' {
  declare module.exports: $Exports<'react-colorpickr/dist/components/inputs/rgb-input'>;
}
declare module 'react-colorpickr/dist/components/inputs/sv-alpha-input.js' {
  declare module.exports: $Exports<'react-colorpickr/dist/components/inputs/sv-alpha-input'>;
}
declare module 'react-colorpickr/dist/gradients/h-gradient.js' {
  declare module.exports: $Exports<'react-colorpickr/dist/gradients/h-gradient'>;
}
declare module 'react-colorpickr/dist/gradients/rgb-gradient.js' {
  declare module.exports: $Exports<'react-colorpickr/dist/gradients/rgb-gradient'>;
}
declare module 'react-colorpickr/dist/gradients/sv-gradient.js' {
  declare module.exports: $Exports<'react-colorpickr/dist/gradients/sv-gradient'>;
}
declare module 'react-colorpickr/dist/inputs/color-inputs.js' {
  declare module.exports: $Exports<'react-colorpickr/dist/inputs/color-inputs'>;
}
declare module 'react-colorpickr/dist/inputs/h-input.js' {
  declare module.exports: $Exports<'react-colorpickr/dist/inputs/h-input'>;
}
declare module 'react-colorpickr/dist/inputs/mode-input.js' {
  declare module.exports: $Exports<'react-colorpickr/dist/inputs/mode-input'>;
}
declare module 'react-colorpickr/dist/inputs/number-input.js' {
  declare module.exports: $Exports<'react-colorpickr/dist/inputs/number-input'>;
}
declare module 'react-colorpickr/dist/inputs/rgb-input.js' {
  declare module.exports: $Exports<'react-colorpickr/dist/inputs/rgb-input'>;
}
declare module 'react-colorpickr/dist/inputs/sv-alpha-input.js' {
  declare module.exports: $Exports<'react-colorpickr/dist/inputs/sv-alpha-input'>;
}
declare module 'react-colorpickr/dist/xy.js' {
  declare module.exports: $Exports<'react-colorpickr/dist/xy'>;
}
declare module 'react-colorpickr/example/bundle.js' {
  declare module.exports: $Exports<'react-colorpickr/example/bundle'>;
}
declare module 'react-colorpickr/example/index.js' {
  declare module.exports: $Exports<'react-colorpickr/example/index'>;
}
declare module 'react-colorpickr/src/colorfunc.js' {
  declare module.exports: $Exports<'react-colorpickr/src/colorfunc'>;
}
declare module 'react-colorpickr/src/colorpickr.js' {
  declare module.exports: $Exports<'react-colorpickr/src/colorpickr'>;
}
declare module 'react-colorpickr/src/components/gradients/h-gradient.js' {
  declare module.exports: $Exports<'react-colorpickr/src/components/gradients/h-gradient'>;
}
declare module 'react-colorpickr/src/components/gradients/rgb-gradient.js' {
  declare module.exports: $Exports<'react-colorpickr/src/components/gradients/rgb-gradient'>;
}
declare module 'react-colorpickr/src/components/gradients/sv-gradient.js' {
  declare module.exports: $Exports<'react-colorpickr/src/components/gradients/sv-gradient'>;
}
declare module 'react-colorpickr/src/components/inputs/h-input.js' {
  declare module.exports: $Exports<'react-colorpickr/src/components/inputs/h-input'>;
}
declare module 'react-colorpickr/src/components/inputs/mode-input.js' {
  declare module.exports: $Exports<'react-colorpickr/src/components/inputs/mode-input'>;
}
declare module 'react-colorpickr/src/components/inputs/number-input.js' {
  declare module.exports: $Exports<'react-colorpickr/src/components/inputs/number-input'>;
}
declare module 'react-colorpickr/src/components/inputs/rgb-input.js' {
  declare module.exports: $Exports<'react-colorpickr/src/components/inputs/rgb-input'>;
}
declare module 'react-colorpickr/src/components/inputs/sv-alpha-input.js' {
  declare module.exports: $Exports<'react-colorpickr/src/components/inputs/sv-alpha-input'>;
}
declare module 'react-colorpickr/src/xy.js' {
  declare module.exports: $Exports<'react-colorpickr/src/xy'>;
}
declare module 'react-colorpickr/test/colorfunc.js' {
  declare module.exports: $Exports<'react-colorpickr/test/colorfunc'>;
}
declare module 'react-colorpickr/test/component.js' {
  declare module.exports: $Exports<'react-colorpickr/test/component'>;
}
declare module 'react-colorpickr/test/components/gradients/h-gradient_test.js' {
  declare module.exports: $Exports<'react-colorpickr/test/components/gradients/h-gradient_test'>;
}
declare module 'react-colorpickr/test/components/gradients/rgb-gradient_test.js' {
  declare module.exports: $Exports<'react-colorpickr/test/components/gradients/rgb-gradient_test'>;
}
declare module 'react-colorpickr/test/components/gradients/sv-gradient_test.js' {
  declare module.exports: $Exports<'react-colorpickr/test/components/gradients/sv-gradient_test'>;
}
declare module 'react-colorpickr/test/components/inputs/h-input_test.js' {
  declare module.exports: $Exports<'react-colorpickr/test/components/inputs/h-input_test'>;
}
declare module 'react-colorpickr/test/components/inputs/mode-input_test.js' {
  declare module.exports: $Exports<'react-colorpickr/test/components/inputs/mode-input_test'>;
}
declare module 'react-colorpickr/test/components/inputs/rgb-input_test.js' {
  declare module.exports: $Exports<'react-colorpickr/test/components/inputs/rgb-input_test'>;
}
declare module 'react-colorpickr/test/components/inputs/sv-alpha-input_test.js' {
  declare module.exports: $Exports<'react-colorpickr/test/components/inputs/sv-alpha-input_test'>;
}
