// flow-typed signature: 64de472e21eeabc331b3a82912f3701d
// flow-typed version: <<STUB>>/react-material-select_vmaphubs/react-material-select#0a35e572d57392bb040c7883331d38365add1db1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-material-select'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-material-select' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-material-select/dist/app.a8c510609eb100fe8969' {
  declare module.exports: any;
}

declare module 'react-material-select/dist/vendor.a8c510609eb100fe8969' {
  declare module.exports: any;
}

declare module 'react-material-select/lib/components/ReactMaterialSelect' {
  declare module.exports: any;
}

declare module 'react-material-select/lib/index' {
  declare module.exports: any;
}

declare module 'react-material-select/src/components/ReactMaterialSelect' {
  declare module.exports: any;
}

declare module 'react-material-select/src/index' {
  declare module.exports: any;
}

declare module 'react-material-select/src/views/Example' {
  declare module.exports: any;
}

declare module 'react-material-select/src/views/ExampleLayout' {
  declare module.exports: any;
}

declare module 'react-material-select/src/views/index' {
  declare module.exports: any;
}

declare module 'react-material-select/webpack.build' {
  declare module.exports: any;
}

declare module 'react-material-select/webpack.config' {
  declare module.exports: any;
}

declare module 'react-material-select/webpack.make' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-material-select/dist/app.a8c510609eb100fe8969.js' {
  declare module.exports: $Exports<'react-material-select/dist/app.a8c510609eb100fe8969'>;
}
declare module 'react-material-select/dist/vendor.a8c510609eb100fe8969.js' {
  declare module.exports: $Exports<'react-material-select/dist/vendor.a8c510609eb100fe8969'>;
}
declare module 'react-material-select/lib/components/ReactMaterialSelect.js' {
  declare module.exports: $Exports<'react-material-select/lib/components/ReactMaterialSelect'>;
}
declare module 'react-material-select/lib/index.js' {
  declare module.exports: $Exports<'react-material-select/lib/index'>;
}
declare module 'react-material-select/src/components/ReactMaterialSelect.jsx' {
  declare module.exports: $Exports<'react-material-select/src/components/ReactMaterialSelect'>;
}
declare module 'react-material-select/src/index.js' {
  declare module.exports: $Exports<'react-material-select/src/index'>;
}
declare module 'react-material-select/src/views/Example.jsx' {
  declare module.exports: $Exports<'react-material-select/src/views/Example'>;
}
declare module 'react-material-select/src/views/ExampleLayout.jsx' {
  declare module.exports: $Exports<'react-material-select/src/views/ExampleLayout'>;
}
declare module 'react-material-select/src/views/index.js' {
  declare module.exports: $Exports<'react-material-select/src/views/index'>;
}
declare module 'react-material-select/webpack.build.js' {
  declare module.exports: $Exports<'react-material-select/webpack.build'>;
}
declare module 'react-material-select/webpack.config.js' {
  declare module.exports: $Exports<'react-material-select/webpack.config'>;
}
declare module 'react-material-select/webpack.make.js' {
  declare module.exports: $Exports<'react-material-select/webpack.make'>;
}
