// flow-typed signature: 6b3eed538cc15b4b1ec9757dcbedf619
// flow-typed version: <<STUB>>/react-data-grid-addons_v^2.0.57/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-data-grid-addons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-data-grid-addons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-data-grid-addons/dist/react-data-grid-addons' {
  declare module.exports: any;
}

declare module 'react-data-grid-addons/dist/react-data-grid-addons.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-data-grid-addons/dist/react-data-grid-addons.js' {
  declare module.exports: $Exports<'react-data-grid-addons/dist/react-data-grid-addons'>;
}
declare module 'react-data-grid-addons/dist/react-data-grid-addons.min.js' {
  declare module.exports: $Exports<'react-data-grid-addons/dist/react-data-grid-addons.min'>;
}
declare module 'react-data-grid-addons/index' {
  declare module.exports: $Exports<'react-data-grid-addons'>;
}
declare module 'react-data-grid-addons/index.js' {
  declare module.exports: $Exports<'react-data-grid-addons'>;
}
