// flow-typed signature: ec195c6342b5a63d0240a689d41aaadd
// flow-typed version: <<STUB>>/react-medium-editor_v1.8.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-medium-editor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-medium-editor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-medium-editor/dist/editor' {
  declare module.exports: any;
}

declare module 'react-medium-editor/example/app' {
  declare module.exports: any;
}

declare module 'react-medium-editor/example/index' {
  declare module.exports: any;
}

declare module 'react-medium-editor/example/styles' {
  declare module.exports: any;
}

declare module 'react-medium-editor/lib/editor' {
  declare module.exports: any;
}

declare module 'react-medium-editor/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-medium-editor/dist/editor.js' {
  declare module.exports: $Exports<'react-medium-editor/dist/editor'>;
}
declare module 'react-medium-editor/example/app.js' {
  declare module.exports: $Exports<'react-medium-editor/example/app'>;
}
declare module 'react-medium-editor/example/index.js' {
  declare module.exports: $Exports<'react-medium-editor/example/index'>;
}
declare module 'react-medium-editor/example/styles.js' {
  declare module.exports: $Exports<'react-medium-editor/example/styles'>;
}
declare module 'react-medium-editor/index' {
  declare module.exports: $Exports<'react-medium-editor'>;
}
declare module 'react-medium-editor/index.js' {
  declare module.exports: $Exports<'react-medium-editor'>;
}
declare module 'react-medium-editor/lib/editor.js' {
  declare module.exports: $Exports<'react-medium-editor/lib/editor'>;
}
declare module 'react-medium-editor/webpack.config.js' {
  declare module.exports: $Exports<'react-medium-editor/webpack.config'>;
}
