// flow-typed signature: 1513c068de36a5652499fd5618041216
// flow-typed version: <<STUB>>/react-fileupload-progress_vopenmaphub/react-fileupload-progress/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-fileupload-progress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-fileupload-progress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-fileupload-progress/example/app' {
  declare module.exports: any;
}

declare module 'react-fileupload-progress/example/bundle' {
  declare module.exports: any;
}

declare module 'react-fileupload-progress/example/server' {
  declare module.exports: any;
}

declare module 'react-fileupload-progress/karma.conf' {
  declare module.exports: any;
}

declare module 'react-fileupload-progress/lib/components/FileUploadProgress' {
  declare module.exports: any;
}

declare module 'react-fileupload-progress/lib/index' {
  declare module.exports: any;
}

declare module 'react-fileupload-progress/src/components/FileUploadProgress' {
  declare module.exports: any;
}

declare module 'react-fileupload-progress/src/index' {
  declare module.exports: any;
}

declare module 'react-fileupload-progress/test/components/FileUploadProgress_spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-fileupload-progress/example/app.js' {
  declare module.exports: $Exports<'react-fileupload-progress/example/app'>;
}
declare module 'react-fileupload-progress/example/bundle.js' {
  declare module.exports: $Exports<'react-fileupload-progress/example/bundle'>;
}
declare module 'react-fileupload-progress/example/server.js' {
  declare module.exports: $Exports<'react-fileupload-progress/example/server'>;
}
declare module 'react-fileupload-progress/karma.conf.js' {
  declare module.exports: $Exports<'react-fileupload-progress/karma.conf'>;
}
declare module 'react-fileupload-progress/lib/components/FileUploadProgress.js' {
  declare module.exports: $Exports<'react-fileupload-progress/lib/components/FileUploadProgress'>;
}
declare module 'react-fileupload-progress/lib/index.js' {
  declare module.exports: $Exports<'react-fileupload-progress/lib/index'>;
}
declare module 'react-fileupload-progress/src/components/FileUploadProgress.js' {
  declare module.exports: $Exports<'react-fileupload-progress/src/components/FileUploadProgress'>;
}
declare module 'react-fileupload-progress/src/index.js' {
  declare module.exports: $Exports<'react-fileupload-progress/src/index'>;
}
declare module 'react-fileupload-progress/test/components/FileUploadProgress_spec.js' {
  declare module.exports: $Exports<'react-fileupload-progress/test/components/FileUploadProgress_spec'>;
}
