// flow-typed signature: 0cc0bff97fc9f0775b401df333a24f2e
// flow-typed version: <<STUB>>/reflux-state-mixin_vopenmaphub/Super-Simple-Flux/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reflux-state-mixin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'reflux-state-mixin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reflux-state-mixin/src/connectMixin' {
  declare module.exports: any;
}

declare module 'reflux-state-mixin/src/decorator' {
  declare module.exports: any;
}

declare module 'reflux-state-mixin/src/index' {
  declare module.exports: any;
}

declare module 'reflux-state-mixin/src/storeMixin' {
  declare module.exports: any;
}

declare module 'reflux-state-mixin/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reflux-state-mixin/src/connectMixin.js' {
  declare module.exports: $Exports<'reflux-state-mixin/src/connectMixin'>;
}
declare module 'reflux-state-mixin/src/decorator.js' {
  declare module.exports: $Exports<'reflux-state-mixin/src/decorator'>;
}
declare module 'reflux-state-mixin/src/index.js' {
  declare module.exports: $Exports<'reflux-state-mixin/src/index'>;
}
declare module 'reflux-state-mixin/src/storeMixin.js' {
  declare module.exports: $Exports<'reflux-state-mixin/src/storeMixin'>;
}
declare module 'reflux-state-mixin/src/utils.js' {
  declare module.exports: $Exports<'reflux-state-mixin/src/utils'>;
}
