// flow-typed signature: c730f73b47d211a4ef9cf2305ec63ca1
// flow-typed version: <<STUB>>/shapefile-fairy_vopenmaphub/shapefile-fairy/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shapefile-fairy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'shapefile-fairy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'shapefile-fairy/bin/shapefile-fairy' {
  declare module.exports: any;
}

declare module 'shapefile-fairy/test/fixtures/index' {
  declare module.exports: any;
}

declare module 'shapefile-fairy/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'shapefile-fairy/bin/shapefile-fairy.js' {
  declare module.exports: $Exports<'shapefile-fairy/bin/shapefile-fairy'>;
}
declare module 'shapefile-fairy/index' {
  declare module.exports: $Exports<'shapefile-fairy'>;
}
declare module 'shapefile-fairy/index.js' {
  declare module.exports: $Exports<'shapefile-fairy'>;
}
declare module 'shapefile-fairy/test/fixtures/index.js' {
  declare module.exports: $Exports<'shapefile-fairy/test/fixtures/index'>;
}
declare module 'shapefile-fairy/test/index.js' {
  declare module.exports: $Exports<'shapefile-fairy/test/index'>;
}
