// flow-typed signature: 7e3eca13beb3c32e7d5b793df63b1a77
// flow-typed version: <<STUB>>/shrink-ray_v0.1.3/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shrink-ray'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'shrink-ray' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'shrink-ray/index' {
  declare module.exports: $Exports<'shrink-ray'>;
}
declare module 'shrink-ray/index.js' {
  declare module.exports: $Exports<'shrink-ray'>;
}
