// flow-typed signature: c123776b47156829422a91073d2fe689
// flow-typed version: <<STUB>>/sphericalmercator_v1.0.5/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sphericalmercator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'sphericalmercator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sphericalmercator/bin/bbox' {
  declare module.exports: any;
}

declare module 'sphericalmercator/bin/to4326' {
  declare module.exports: any;
}

declare module 'sphericalmercator/bin/to900913' {
  declare module.exports: any;
}

declare module 'sphericalmercator/bin/xyz' {
  declare module.exports: any;
}

declare module 'sphericalmercator/sphericalmercator' {
  declare module.exports: any;
}

declare module 'sphericalmercator/test/sphericalmercator.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sphericalmercator/bin/bbox.js' {
  declare module.exports: $Exports<'sphericalmercator/bin/bbox'>;
}
declare module 'sphericalmercator/bin/to4326.js' {
  declare module.exports: $Exports<'sphericalmercator/bin/to4326'>;
}
declare module 'sphericalmercator/bin/to900913.js' {
  declare module.exports: $Exports<'sphericalmercator/bin/to900913'>;
}
declare module 'sphericalmercator/bin/xyz.js' {
  declare module.exports: $Exports<'sphericalmercator/bin/xyz'>;
}
declare module 'sphericalmercator/sphericalmercator.js' {
  declare module.exports: $Exports<'sphericalmercator/sphericalmercator'>;
}
declare module 'sphericalmercator/test/sphericalmercator.test.js' {
  declare module.exports: $Exports<'sphericalmercator/test/sphericalmercator.test'>;
}
