// flow-typed signature: 23ecaca7df5a5cae23e636e3c8d88725
// flow-typed version: <<STUB>>/superagent-bluebird-promise_v^4.2.0/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'superagent-bluebird-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'superagent-bluebird-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'superagent-bluebird-promise/index' {
  declare module.exports: $Exports<'superagent-bluebird-promise'>;
}
declare module 'superagent-bluebird-promise/index.js' {
  declare module.exports: $Exports<'superagent-bluebird-promise'>;
}
