// flow-typed signature: cf70c630fb12f51634bd2db173964910
// flow-typed version: <<STUB>>/superagent-jsonp_v0.2.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'superagent-jsonp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'superagent-jsonp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'superagent-jsonp/dist/superagent-jsonp' {
  declare module.exports: any;
}

declare module 'superagent-jsonp/src/superagent-jsonp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'superagent-jsonp/dist/superagent-jsonp.js' {
  declare module.exports: $Exports<'superagent-jsonp/dist/superagent-jsonp'>;
}
declare module 'superagent-jsonp/src/superagent-jsonp.js' {
  declare module.exports: $Exports<'superagent-jsonp/src/superagent-jsonp'>;
}
