// flow-typed signature: ee6496661ca37af466548044750f31a7
// flow-typed version: <<STUB>>/terraformer-arcgis-parser_v1.0.5/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'terraformer-arcgis-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'terraformer-arcgis-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'terraformer-arcgis-parser/benchmarks/benchmarks' {
  declare module.exports: any;
}

declare module 'terraformer-arcgis-parser/Gruntfile' {
  declare module.exports: any;
}

declare module 'terraformer-arcgis-parser/spec/arcgisSpec' {
  declare module.exports: any;
}

declare module 'terraformer-arcgis-parser/terraformer-arcgis-parser' {
  declare module.exports: any;
}

declare module 'terraformer-arcgis-parser/terraformer-arcgis-parser.min' {
  declare module.exports: any;
}

declare module 'terraformer-arcgis-parser/versions/terraformer-arcgis-parser-1.0.0.min' {
  declare module.exports: any;
}

declare module 'terraformer-arcgis-parser/versions/terraformer-arcgis-parser-1.0.1.min' {
  declare module.exports: any;
}

declare module 'terraformer-arcgis-parser/versions/terraformer-arcgis-parser-1.0.2.min' {
  declare module.exports: any;
}

declare module 'terraformer-arcgis-parser/versions/terraformer-arcgis-parser-1.0.3.min' {
  declare module.exports: any;
}

declare module 'terraformer-arcgis-parser/versions/terraformer-arcgis-parser-1.0.4.min' {
  declare module.exports: any;
}

declare module 'terraformer-arcgis-parser/versions/terraformer-arcgis-parser-1.0.5.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'terraformer-arcgis-parser/benchmarks/benchmarks.js' {
  declare module.exports: $Exports<'terraformer-arcgis-parser/benchmarks/benchmarks'>;
}
declare module 'terraformer-arcgis-parser/Gruntfile.js' {
  declare module.exports: $Exports<'terraformer-arcgis-parser/Gruntfile'>;
}
declare module 'terraformer-arcgis-parser/spec/arcgisSpec.js' {
  declare module.exports: $Exports<'terraformer-arcgis-parser/spec/arcgisSpec'>;
}
declare module 'terraformer-arcgis-parser/terraformer-arcgis-parser.js' {
  declare module.exports: $Exports<'terraformer-arcgis-parser/terraformer-arcgis-parser'>;
}
declare module 'terraformer-arcgis-parser/terraformer-arcgis-parser.min.js' {
  declare module.exports: $Exports<'terraformer-arcgis-parser/terraformer-arcgis-parser.min'>;
}
declare module 'terraformer-arcgis-parser/versions/terraformer-arcgis-parser-1.0.0.min.js' {
  declare module.exports: $Exports<'terraformer-arcgis-parser/versions/terraformer-arcgis-parser-1.0.0.min'>;
}
declare module 'terraformer-arcgis-parser/versions/terraformer-arcgis-parser-1.0.1.min.js' {
  declare module.exports: $Exports<'terraformer-arcgis-parser/versions/terraformer-arcgis-parser-1.0.1.min'>;
}
declare module 'terraformer-arcgis-parser/versions/terraformer-arcgis-parser-1.0.2.min.js' {
  declare module.exports: $Exports<'terraformer-arcgis-parser/versions/terraformer-arcgis-parser-1.0.2.min'>;
}
declare module 'terraformer-arcgis-parser/versions/terraformer-arcgis-parser-1.0.3.min.js' {
  declare module.exports: $Exports<'terraformer-arcgis-parser/versions/terraformer-arcgis-parser-1.0.3.min'>;
}
declare module 'terraformer-arcgis-parser/versions/terraformer-arcgis-parser-1.0.4.min.js' {
  declare module.exports: $Exports<'terraformer-arcgis-parser/versions/terraformer-arcgis-parser-1.0.4.min'>;
}
declare module 'terraformer-arcgis-parser/versions/terraformer-arcgis-parser-1.0.5.min.js' {
  declare module.exports: $Exports<'terraformer-arcgis-parser/versions/terraformer-arcgis-parser-1.0.5.min'>;
}
