// flow-typed signature: a6d8f0b422470c5b91bb25b6b5cd1505
// flow-typed version: <<STUB>>/tokml_vkriscarle/tokml/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tokml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tokml' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tokml/scripts/regenerate' {
  declare module.exports: any;
}

declare module 'tokml/site/index' {
  declare module.exports: any;
}

declare module 'tokml/site/site' {
  declare module.exports: any;
}

declare module 'tokml/tokml' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tokml/index' {
  declare module.exports: $Exports<'tokml'>;
}
declare module 'tokml/index.js' {
  declare module.exports: $Exports<'tokml'>;
}
declare module 'tokml/scripts/regenerate.js' {
  declare module.exports: $Exports<'tokml/scripts/regenerate'>;
}
declare module 'tokml/site/index.js' {
  declare module.exports: $Exports<'tokml/site/index'>;
}
declare module 'tokml/site/site.js' {
  declare module.exports: $Exports<'tokml/site/site'>;
}
declare module 'tokml/tokml.js' {
  declare module.exports: $Exports<'tokml/tokml'>;
}
