// flow-typed signature: 8494078d4efaeb9bcd3104091562bde5
// flow-typed version: <<STUB>>/tokml_v0.4.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tokml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'tokml' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tokml/scripts/regenerate' {
  declare module.exports: any;
}

declare module 'tokml/site/index' {
  declare module.exports: any;
}

declare module 'tokml/site/site' {
  declare module.exports: any;
}

declare module 'tokml/test/kml.test' {
  declare module.exports: any;
}

declare module 'tokml/tokml' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tokml/index' {
  declare module.exports: $Exports<'tokml'>;
}
declare module 'tokml/index.js' {
  declare module.exports: $Exports<'tokml'>;
}
declare module 'tokml/scripts/regenerate.js' {
  declare module.exports: $Exports<'tokml/scripts/regenerate'>;
}
declare module 'tokml/site/index.js' {
  declare module.exports: $Exports<'tokml/site/index'>;
}
declare module 'tokml/site/site.js' {
  declare module.exports: $Exports<'tokml/site/site'>;
}
declare module 'tokml/test/kml.test.js' {
  declare module.exports: $Exports<'tokml/test/kml.test'>;
}
declare module 'tokml/tokml.js' {
  declare module.exports: $Exports<'tokml/tokml'>;
}
