// flow-typed signature: e3f9e3215e4e836657a05aa9f01e845c
// flow-typed version: <<STUB>>/tus-node-server_v0.2.10/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tus-node-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tus-node-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tus-node-server/lib/constants' {
  declare module.exports: any;
}

declare module 'tus-node-server/lib/handlers/BaseHandler' {
  declare module.exports: any;
}

declare module 'tus-node-server/lib/handlers/HeadHandler' {
  declare module.exports: any;
}

declare module 'tus-node-server/lib/handlers/OptionsHandler' {
  declare module.exports: any;
}

declare module 'tus-node-server/lib/handlers/PatchHandler' {
  declare module.exports: any;
}

declare module 'tus-node-server/lib/handlers/PostHandler' {
  declare module.exports: any;
}

declare module 'tus-node-server/lib/models/File' {
  declare module.exports: any;
}

declare module 'tus-node-server/lib/models/Uid' {
  declare module.exports: any;
}

declare module 'tus-node-server/lib/Server' {
  declare module.exports: any;
}

declare module 'tus-node-server/lib/stores/DataStore' {
  declare module.exports: any;
}

declare module 'tus-node-server/lib/stores/FileStore' {
  declare module.exports: any;
}

declare module 'tus-node-server/lib/stores/GCSDataStore' {
  declare module.exports: any;
}

declare module 'tus-node-server/lib/validators/RequestValidator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tus-node-server/index' {
  declare module.exports: $Exports<'tus-node-server'>;
}
declare module 'tus-node-server/index.js' {
  declare module.exports: $Exports<'tus-node-server'>;
}
declare module 'tus-node-server/lib/constants.js' {
  declare module.exports: $Exports<'tus-node-server/lib/constants'>;
}
declare module 'tus-node-server/lib/handlers/BaseHandler.js' {
  declare module.exports: $Exports<'tus-node-server/lib/handlers/BaseHandler'>;
}
declare module 'tus-node-server/lib/handlers/HeadHandler.js' {
  declare module.exports: $Exports<'tus-node-server/lib/handlers/HeadHandler'>;
}
declare module 'tus-node-server/lib/handlers/OptionsHandler.js' {
  declare module.exports: $Exports<'tus-node-server/lib/handlers/OptionsHandler'>;
}
declare module 'tus-node-server/lib/handlers/PatchHandler.js' {
  declare module.exports: $Exports<'tus-node-server/lib/handlers/PatchHandler'>;
}
declare module 'tus-node-server/lib/handlers/PostHandler.js' {
  declare module.exports: $Exports<'tus-node-server/lib/handlers/PostHandler'>;
}
declare module 'tus-node-server/lib/models/File.js' {
  declare module.exports: $Exports<'tus-node-server/lib/models/File'>;
}
declare module 'tus-node-server/lib/models/Uid.js' {
  declare module.exports: $Exports<'tus-node-server/lib/models/Uid'>;
}
declare module 'tus-node-server/lib/Server.js' {
  declare module.exports: $Exports<'tus-node-server/lib/Server'>;
}
declare module 'tus-node-server/lib/stores/DataStore.js' {
  declare module.exports: $Exports<'tus-node-server/lib/stores/DataStore'>;
}
declare module 'tus-node-server/lib/stores/FileStore.js' {
  declare module.exports: $Exports<'tus-node-server/lib/stores/FileStore'>;
}
declare module 'tus-node-server/lib/stores/GCSDataStore.js' {
  declare module.exports: $Exports<'tus-node-server/lib/stores/GCSDataStore'>;
}
declare module 'tus-node-server/lib/validators/RequestValidator.js' {
  declare module.exports: $Exports<'tus-node-server/lib/validators/RequestValidator'>;
}
