// flow-typed signature: 3fa8fb0f6c9824dd071d3bc8df5e8c99
// flow-typed version: <<STUB>>/uppy_v^0.23.2/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uppy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uppy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uppy/bin/build-css' {
  declare module.exports: any;
}

declare module 'uppy/bin/build-js' {
  declare module.exports: any;
}

declare module 'uppy/bin/disc' {
  declare module.exports: any;
}

declare module 'uppy/bin/gzip' {
  declare module.exports: any;
}

declare module 'uppy/bin/start-server' {
  declare module.exports: any;
}

declare module 'uppy/dist/uppy' {
  declare module.exports: any;
}

declare module 'uppy/dist/uppy.min' {
  declare module.exports: any;
}

declare module 'uppy/lib/core/Core' {
  declare module.exports: any;
}

declare module 'uppy/lib/core/Core.test' {
  declare module.exports: any;
}

declare module 'uppy/lib/core/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/core/index.test' {
  declare module.exports: any;
}

declare module 'uppy/lib/core/Plugin' {
  declare module.exports: any;
}

declare module 'uppy/lib/core/Translator' {
  declare module.exports: any;
}

declare module 'uppy/lib/core/Translator.test' {
  declare module.exports: any;
}

declare module 'uppy/lib/core/UppySocket' {
  declare module.exports: any;
}

declare module 'uppy/lib/core/UppySocket.test' {
  declare module.exports: any;
}

declare module 'uppy/lib/core/Utils' {
  declare module.exports: any;
}

declare module 'uppy/lib/core/Utils.test' {
  declare module.exports: any;
}

declare module 'uppy/lib/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/locales/cs_CZ' {
  declare module.exports: any;
}

declare module 'uppy/lib/locales/de_DE' {
  declare module.exports: any;
}

declare module 'uppy/lib/locales/en_US' {
  declare module.exports: any;
}

declare module 'uppy/lib/locales/es_ES' {
  declare module.exports: any;
}

declare module 'uppy/lib/locales/fi_FI' {
  declare module.exports: any;
}

declare module 'uppy/lib/locales/id_ID' {
  declare module.exports: any;
}

declare module 'uppy/lib/locales/it_IT' {
  declare module.exports: any;
}

declare module 'uppy/lib/locales/nb_NO' {
  declare module.exports: any;
}

declare module 'uppy/lib/locales/pl_PL' {
  declare module.exports: any;
}

declare module 'uppy/lib/locales/pt_BR' {
  declare module.exports: any;
}

declare module 'uppy/lib/locales/ru_RU' {
  declare module.exports: any;
}

declare module 'uppy/lib/locales/tr_TR' {
  declare module.exports: any;
}

declare module 'uppy/lib/locales/zh_CN' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/AwsS3/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Dashboard/ActionBrowseTagline' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Dashboard/Dashboard' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Dashboard/FileCard' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Dashboard/FileItem' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Dashboard/FileItemProgress' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Dashboard/FileList' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Dashboard/getFileTypeIcon' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Dashboard/icons' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Dashboard/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Dashboard/Tabs' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/DragDrop/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Dropbox/icons' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Dropbox/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Dummy' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/FileInput' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Form' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/GoldenRetriever/cleanup' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/GoldenRetriever/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/GoldenRetriever/IndexedDBStore' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/GoldenRetriever/MetaDataStore' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/GoldenRetriever/ServiceWorker' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/GoldenRetriever/ServiceWorkerStore' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/GoogleDrive/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Informer' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Instagram/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/MagicLog' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/ProgressBar' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Provider/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Provider/view/AuthView' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Provider/view/Breadcrumb' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Provider/view/Breadcrumbs' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Provider/view/Browser' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Provider/view/Filter' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Provider/view/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Provider/view/Loader' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Provider/view/Table' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Provider/view/TableRow' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Redux' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Redux.test' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/ReduxDevTools' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/StatusBar/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/StatusBar/StatusBar' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/ThumbnailGenerator/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/ThumbnailGenerator/index.test' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Transloadit/Client' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Transloadit/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Transloadit/index.test' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Transloadit/Socket' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Tus' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Url/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Url/UrlUI' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Webcam/CameraIcon' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Webcam/CameraScreen' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Webcam/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Webcam/PermissionsScreen' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Webcam/RecordButton' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Webcam/RecordStartIcon' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Webcam/RecordStopIcon' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Webcam/SnapshotButton' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Webcam/supportsMediaRecorder' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Webcam/supportsMediaRecorder.test' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/Webcam/WebcamIcon' {
  declare module.exports: any;
}

declare module 'uppy/lib/plugins/XHRUpload' {
  declare module.exports: any;
}

declare module 'uppy/lib/react/Dashboard' {
  declare module.exports: any;
}

declare module 'uppy/lib/react/DashboardModal' {
  declare module.exports: any;
}

declare module 'uppy/lib/react/DragDrop' {
  declare module.exports: any;
}

declare module 'uppy/lib/react/index' {
  declare module.exports: any;
}

declare module 'uppy/lib/react/ProgressBar' {
  declare module.exports: any;
}

declare module 'uppy/lib/react/StatusBar' {
  declare module.exports: any;
}

declare module 'uppy/lib/react/Wrapper' {
  declare module.exports: any;
}

declare module 'uppy/lib/store/DefaultStore' {
  declare module.exports: any;
}

declare module 'uppy/lib/store/DefaultStore.test' {
  declare module.exports: any;
}

declare module 'uppy/lib/store/ReduxStore' {
  declare module.exports: any;
}

declare module 'uppy/lib/store/ReduxStore.test' {
  declare module.exports: any;
}

declare module 'uppy/lib/vendor/file-type/index' {
  declare module.exports: any;
}

declare module 'uppy/src/core/Core' {
  declare module.exports: any;
}

declare module 'uppy/src/core/Core.test' {
  declare module.exports: any;
}

declare module 'uppy/src/core/index' {
  declare module.exports: any;
}

declare module 'uppy/src/core/index.test' {
  declare module.exports: any;
}

declare module 'uppy/src/core/Plugin' {
  declare module.exports: any;
}

declare module 'uppy/src/core/Translator' {
  declare module.exports: any;
}

declare module 'uppy/src/core/Translator.test' {
  declare module.exports: any;
}

declare module 'uppy/src/core/UppySocket' {
  declare module.exports: any;
}

declare module 'uppy/src/core/UppySocket.test' {
  declare module.exports: any;
}

declare module 'uppy/src/core/Utils' {
  declare module.exports: any;
}

declare module 'uppy/src/core/Utils.test' {
  declare module.exports: any;
}

declare module 'uppy/src/index' {
  declare module.exports: any;
}

declare module 'uppy/src/locales/cs_CZ' {
  declare module.exports: any;
}

declare module 'uppy/src/locales/de_DE' {
  declare module.exports: any;
}

declare module 'uppy/src/locales/en_US' {
  declare module.exports: any;
}

declare module 'uppy/src/locales/es_ES' {
  declare module.exports: any;
}

declare module 'uppy/src/locales/fi_FI' {
  declare module.exports: any;
}

declare module 'uppy/src/locales/id_ID' {
  declare module.exports: any;
}

declare module 'uppy/src/locales/it_IT' {
  declare module.exports: any;
}

declare module 'uppy/src/locales/nb_NO' {
  declare module.exports: any;
}

declare module 'uppy/src/locales/pl_PL' {
  declare module.exports: any;
}

declare module 'uppy/src/locales/pt_BR' {
  declare module.exports: any;
}

declare module 'uppy/src/locales/ru_RU' {
  declare module.exports: any;
}

declare module 'uppy/src/locales/tr_TR' {
  declare module.exports: any;
}

declare module 'uppy/src/locales/zh_CN' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/AwsS3/index' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Dashboard/ActionBrowseTagline' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Dashboard/Dashboard' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Dashboard/FileCard' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Dashboard/FileItem' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Dashboard/FileItemProgress' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Dashboard/FileList' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Dashboard/getFileTypeIcon' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Dashboard/icons' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Dashboard/index' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Dashboard/Tabs' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/DragDrop/index' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Dropbox/icons' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Dropbox/index' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Dummy' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/FileInput' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Form' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/GoldenRetriever/cleanup' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/GoldenRetriever/index' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/GoldenRetriever/IndexedDBStore' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/GoldenRetriever/MetaDataStore' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/GoldenRetriever/ServiceWorker' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/GoldenRetriever/ServiceWorkerStore' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/GoogleDrive/index' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Informer' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Instagram/index' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/MagicLog' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/ProgressBar' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Provider/index' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Provider/view/AuthView' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Provider/view/Breadcrumb' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Provider/view/Breadcrumbs' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Provider/view/Browser' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Provider/view/Filter' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Provider/view/index' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Provider/view/Loader' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Provider/view/Table' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Provider/view/TableRow' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Redux' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Redux.test' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/ReduxDevTools' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/StatusBar/index' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/StatusBar/StatusBar' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/ThumbnailGenerator/index' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/ThumbnailGenerator/index.test' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Transloadit/Client' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Transloadit/index' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Transloadit/index.test' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Transloadit/Socket' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Tus' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Url/index' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Url/UrlUI' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Webcam/CameraIcon' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Webcam/CameraScreen' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Webcam/index' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Webcam/PermissionsScreen' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Webcam/RecordButton' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Webcam/RecordStartIcon' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Webcam/RecordStopIcon' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Webcam/SnapshotButton' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Webcam/supportsMediaRecorder' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Webcam/supportsMediaRecorder.test' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/Webcam/WebcamIcon' {
  declare module.exports: any;
}

declare module 'uppy/src/plugins/XHRUpload' {
  declare module.exports: any;
}

declare module 'uppy/src/react/Dashboard' {
  declare module.exports: any;
}

declare module 'uppy/src/react/DashboardModal' {
  declare module.exports: any;
}

declare module 'uppy/src/react/DragDrop' {
  declare module.exports: any;
}

declare module 'uppy/src/react/index' {
  declare module.exports: any;
}

declare module 'uppy/src/react/ProgressBar' {
  declare module.exports: any;
}

declare module 'uppy/src/react/StatusBar' {
  declare module.exports: any;
}

declare module 'uppy/src/react/Wrapper' {
  declare module.exports: any;
}

declare module 'uppy/src/store/DefaultStore' {
  declare module.exports: any;
}

declare module 'uppy/src/store/DefaultStore.test' {
  declare module.exports: any;
}

declare module 'uppy/src/store/ReduxStore' {
  declare module.exports: any;
}

declare module 'uppy/src/store/ReduxStore.test' {
  declare module.exports: any;
}

declare module 'uppy/src/vendor/file-type/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uppy/bin/build-css.js' {
  declare module.exports: $Exports<'uppy/bin/build-css'>;
}
declare module 'uppy/bin/build-js.js' {
  declare module.exports: $Exports<'uppy/bin/build-js'>;
}
declare module 'uppy/bin/disc.js' {
  declare module.exports: $Exports<'uppy/bin/disc'>;
}
declare module 'uppy/bin/gzip.js' {
  declare module.exports: $Exports<'uppy/bin/gzip'>;
}
declare module 'uppy/bin/start-server.js' {
  declare module.exports: $Exports<'uppy/bin/start-server'>;
}
declare module 'uppy/dist/uppy.js' {
  declare module.exports: $Exports<'uppy/dist/uppy'>;
}
declare module 'uppy/dist/uppy.min.js' {
  declare module.exports: $Exports<'uppy/dist/uppy.min'>;
}
declare module 'uppy/lib/core/Core.js' {
  declare module.exports: $Exports<'uppy/lib/core/Core'>;
}
declare module 'uppy/lib/core/Core.test.js' {
  declare module.exports: $Exports<'uppy/lib/core/Core.test'>;
}
declare module 'uppy/lib/core/index.js' {
  declare module.exports: $Exports<'uppy/lib/core/index'>;
}
declare module 'uppy/lib/core/index.test.js' {
  declare module.exports: $Exports<'uppy/lib/core/index.test'>;
}
declare module 'uppy/lib/core/Plugin.js' {
  declare module.exports: $Exports<'uppy/lib/core/Plugin'>;
}
declare module 'uppy/lib/core/Translator.js' {
  declare module.exports: $Exports<'uppy/lib/core/Translator'>;
}
declare module 'uppy/lib/core/Translator.test.js' {
  declare module.exports: $Exports<'uppy/lib/core/Translator.test'>;
}
declare module 'uppy/lib/core/UppySocket.js' {
  declare module.exports: $Exports<'uppy/lib/core/UppySocket'>;
}
declare module 'uppy/lib/core/UppySocket.test.js' {
  declare module.exports: $Exports<'uppy/lib/core/UppySocket.test'>;
}
declare module 'uppy/lib/core/Utils.js' {
  declare module.exports: $Exports<'uppy/lib/core/Utils'>;
}
declare module 'uppy/lib/core/Utils.test.js' {
  declare module.exports: $Exports<'uppy/lib/core/Utils.test'>;
}
declare module 'uppy/lib/index.js' {
  declare module.exports: $Exports<'uppy/lib/index'>;
}
declare module 'uppy/lib/locales/cs_CZ.js' {
  declare module.exports: $Exports<'uppy/lib/locales/cs_CZ'>;
}
declare module 'uppy/lib/locales/de_DE.js' {
  declare module.exports: $Exports<'uppy/lib/locales/de_DE'>;
}
declare module 'uppy/lib/locales/en_US.js' {
  declare module.exports: $Exports<'uppy/lib/locales/en_US'>;
}
declare module 'uppy/lib/locales/es_ES.js' {
  declare module.exports: $Exports<'uppy/lib/locales/es_ES'>;
}
declare module 'uppy/lib/locales/fi_FI.js' {
  declare module.exports: $Exports<'uppy/lib/locales/fi_FI'>;
}
declare module 'uppy/lib/locales/id_ID.js' {
  declare module.exports: $Exports<'uppy/lib/locales/id_ID'>;
}
declare module 'uppy/lib/locales/it_IT.js' {
  declare module.exports: $Exports<'uppy/lib/locales/it_IT'>;
}
declare module 'uppy/lib/locales/nb_NO.js' {
  declare module.exports: $Exports<'uppy/lib/locales/nb_NO'>;
}
declare module 'uppy/lib/locales/pl_PL.js' {
  declare module.exports: $Exports<'uppy/lib/locales/pl_PL'>;
}
declare module 'uppy/lib/locales/pt_BR.js' {
  declare module.exports: $Exports<'uppy/lib/locales/pt_BR'>;
}
declare module 'uppy/lib/locales/ru_RU.js' {
  declare module.exports: $Exports<'uppy/lib/locales/ru_RU'>;
}
declare module 'uppy/lib/locales/tr_TR.js' {
  declare module.exports: $Exports<'uppy/lib/locales/tr_TR'>;
}
declare module 'uppy/lib/locales/zh_CN.js' {
  declare module.exports: $Exports<'uppy/lib/locales/zh_CN'>;
}
declare module 'uppy/lib/plugins/AwsS3/index.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/AwsS3/index'>;
}
declare module 'uppy/lib/plugins/Dashboard/ActionBrowseTagline.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Dashboard/ActionBrowseTagline'>;
}
declare module 'uppy/lib/plugins/Dashboard/Dashboard.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Dashboard/Dashboard'>;
}
declare module 'uppy/lib/plugins/Dashboard/FileCard.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Dashboard/FileCard'>;
}
declare module 'uppy/lib/plugins/Dashboard/FileItem.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Dashboard/FileItem'>;
}
declare module 'uppy/lib/plugins/Dashboard/FileItemProgress.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Dashboard/FileItemProgress'>;
}
declare module 'uppy/lib/plugins/Dashboard/FileList.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Dashboard/FileList'>;
}
declare module 'uppy/lib/plugins/Dashboard/getFileTypeIcon.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Dashboard/getFileTypeIcon'>;
}
declare module 'uppy/lib/plugins/Dashboard/icons.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Dashboard/icons'>;
}
declare module 'uppy/lib/plugins/Dashboard/index.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Dashboard/index'>;
}
declare module 'uppy/lib/plugins/Dashboard/Tabs.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Dashboard/Tabs'>;
}
declare module 'uppy/lib/plugins/DragDrop/index.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/DragDrop/index'>;
}
declare module 'uppy/lib/plugins/Dropbox/icons.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Dropbox/icons'>;
}
declare module 'uppy/lib/plugins/Dropbox/index.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Dropbox/index'>;
}
declare module 'uppy/lib/plugins/Dummy.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Dummy'>;
}
declare module 'uppy/lib/plugins/FileInput.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/FileInput'>;
}
declare module 'uppy/lib/plugins/Form.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Form'>;
}
declare module 'uppy/lib/plugins/GoldenRetriever/cleanup.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/GoldenRetriever/cleanup'>;
}
declare module 'uppy/lib/plugins/GoldenRetriever/index.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/GoldenRetriever/index'>;
}
declare module 'uppy/lib/plugins/GoldenRetriever/IndexedDBStore.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/GoldenRetriever/IndexedDBStore'>;
}
declare module 'uppy/lib/plugins/GoldenRetriever/MetaDataStore.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/GoldenRetriever/MetaDataStore'>;
}
declare module 'uppy/lib/plugins/GoldenRetriever/ServiceWorker.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/GoldenRetriever/ServiceWorker'>;
}
declare module 'uppy/lib/plugins/GoldenRetriever/ServiceWorkerStore.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/GoldenRetriever/ServiceWorkerStore'>;
}
declare module 'uppy/lib/plugins/GoogleDrive/index.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/GoogleDrive/index'>;
}
declare module 'uppy/lib/plugins/Informer.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Informer'>;
}
declare module 'uppy/lib/plugins/Instagram/index.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Instagram/index'>;
}
declare module 'uppy/lib/plugins/MagicLog.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/MagicLog'>;
}
declare module 'uppy/lib/plugins/ProgressBar.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/ProgressBar'>;
}
declare module 'uppy/lib/plugins/Provider/index.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Provider/index'>;
}
declare module 'uppy/lib/plugins/Provider/view/AuthView.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Provider/view/AuthView'>;
}
declare module 'uppy/lib/plugins/Provider/view/Breadcrumb.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Provider/view/Breadcrumb'>;
}
declare module 'uppy/lib/plugins/Provider/view/Breadcrumbs.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Provider/view/Breadcrumbs'>;
}
declare module 'uppy/lib/plugins/Provider/view/Browser.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Provider/view/Browser'>;
}
declare module 'uppy/lib/plugins/Provider/view/Filter.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Provider/view/Filter'>;
}
declare module 'uppy/lib/plugins/Provider/view/index.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Provider/view/index'>;
}
declare module 'uppy/lib/plugins/Provider/view/Loader.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Provider/view/Loader'>;
}
declare module 'uppy/lib/plugins/Provider/view/Table.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Provider/view/Table'>;
}
declare module 'uppy/lib/plugins/Provider/view/TableRow.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Provider/view/TableRow'>;
}
declare module 'uppy/lib/plugins/Redux.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Redux'>;
}
declare module 'uppy/lib/plugins/Redux.test.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Redux.test'>;
}
declare module 'uppy/lib/plugins/ReduxDevTools.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/ReduxDevTools'>;
}
declare module 'uppy/lib/plugins/StatusBar/index.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/StatusBar/index'>;
}
declare module 'uppy/lib/plugins/StatusBar/StatusBar.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/StatusBar/StatusBar'>;
}
declare module 'uppy/lib/plugins/ThumbnailGenerator/index.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/ThumbnailGenerator/index'>;
}
declare module 'uppy/lib/plugins/ThumbnailGenerator/index.test.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/ThumbnailGenerator/index.test'>;
}
declare module 'uppy/lib/plugins/Transloadit/Client.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Transloadit/Client'>;
}
declare module 'uppy/lib/plugins/Transloadit/index.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Transloadit/index'>;
}
declare module 'uppy/lib/plugins/Transloadit/index.test.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Transloadit/index.test'>;
}
declare module 'uppy/lib/plugins/Transloadit/Socket.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Transloadit/Socket'>;
}
declare module 'uppy/lib/plugins/Tus.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Tus'>;
}
declare module 'uppy/lib/plugins/Url/index.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Url/index'>;
}
declare module 'uppy/lib/plugins/Url/UrlUI.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Url/UrlUI'>;
}
declare module 'uppy/lib/plugins/Webcam/CameraIcon.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Webcam/CameraIcon'>;
}
declare module 'uppy/lib/plugins/Webcam/CameraScreen.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Webcam/CameraScreen'>;
}
declare module 'uppy/lib/plugins/Webcam/index.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Webcam/index'>;
}
declare module 'uppy/lib/plugins/Webcam/PermissionsScreen.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Webcam/PermissionsScreen'>;
}
declare module 'uppy/lib/plugins/Webcam/RecordButton.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Webcam/RecordButton'>;
}
declare module 'uppy/lib/plugins/Webcam/RecordStartIcon.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Webcam/RecordStartIcon'>;
}
declare module 'uppy/lib/plugins/Webcam/RecordStopIcon.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Webcam/RecordStopIcon'>;
}
declare module 'uppy/lib/plugins/Webcam/SnapshotButton.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Webcam/SnapshotButton'>;
}
declare module 'uppy/lib/plugins/Webcam/supportsMediaRecorder.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Webcam/supportsMediaRecorder'>;
}
declare module 'uppy/lib/plugins/Webcam/supportsMediaRecorder.test.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Webcam/supportsMediaRecorder.test'>;
}
declare module 'uppy/lib/plugins/Webcam/WebcamIcon.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/Webcam/WebcamIcon'>;
}
declare module 'uppy/lib/plugins/XHRUpload.js' {
  declare module.exports: $Exports<'uppy/lib/plugins/XHRUpload'>;
}
declare module 'uppy/lib/react/Dashboard.js' {
  declare module.exports: $Exports<'uppy/lib/react/Dashboard'>;
}
declare module 'uppy/lib/react/DashboardModal.js' {
  declare module.exports: $Exports<'uppy/lib/react/DashboardModal'>;
}
declare module 'uppy/lib/react/DragDrop.js' {
  declare module.exports: $Exports<'uppy/lib/react/DragDrop'>;
}
declare module 'uppy/lib/react/index.js' {
  declare module.exports: $Exports<'uppy/lib/react/index'>;
}
declare module 'uppy/lib/react/ProgressBar.js' {
  declare module.exports: $Exports<'uppy/lib/react/ProgressBar'>;
}
declare module 'uppy/lib/react/StatusBar.js' {
  declare module.exports: $Exports<'uppy/lib/react/StatusBar'>;
}
declare module 'uppy/lib/react/Wrapper.js' {
  declare module.exports: $Exports<'uppy/lib/react/Wrapper'>;
}
declare module 'uppy/lib/store/DefaultStore.js' {
  declare module.exports: $Exports<'uppy/lib/store/DefaultStore'>;
}
declare module 'uppy/lib/store/DefaultStore.test.js' {
  declare module.exports: $Exports<'uppy/lib/store/DefaultStore.test'>;
}
declare module 'uppy/lib/store/ReduxStore.js' {
  declare module.exports: $Exports<'uppy/lib/store/ReduxStore'>;
}
declare module 'uppy/lib/store/ReduxStore.test.js' {
  declare module.exports: $Exports<'uppy/lib/store/ReduxStore.test'>;
}
declare module 'uppy/lib/vendor/file-type/index.js' {
  declare module.exports: $Exports<'uppy/lib/vendor/file-type/index'>;
}
declare module 'uppy/src/core/Core.js' {
  declare module.exports: $Exports<'uppy/src/core/Core'>;
}
declare module 'uppy/src/core/Core.test.js' {
  declare module.exports: $Exports<'uppy/src/core/Core.test'>;
}
declare module 'uppy/src/core/index.js' {
  declare module.exports: $Exports<'uppy/src/core/index'>;
}
declare module 'uppy/src/core/index.test.js' {
  declare module.exports: $Exports<'uppy/src/core/index.test'>;
}
declare module 'uppy/src/core/Plugin.js' {
  declare module.exports: $Exports<'uppy/src/core/Plugin'>;
}
declare module 'uppy/src/core/Translator.js' {
  declare module.exports: $Exports<'uppy/src/core/Translator'>;
}
declare module 'uppy/src/core/Translator.test.js' {
  declare module.exports: $Exports<'uppy/src/core/Translator.test'>;
}
declare module 'uppy/src/core/UppySocket.js' {
  declare module.exports: $Exports<'uppy/src/core/UppySocket'>;
}
declare module 'uppy/src/core/UppySocket.test.js' {
  declare module.exports: $Exports<'uppy/src/core/UppySocket.test'>;
}
declare module 'uppy/src/core/Utils.js' {
  declare module.exports: $Exports<'uppy/src/core/Utils'>;
}
declare module 'uppy/src/core/Utils.test.js' {
  declare module.exports: $Exports<'uppy/src/core/Utils.test'>;
}
declare module 'uppy/src/index.js' {
  declare module.exports: $Exports<'uppy/src/index'>;
}
declare module 'uppy/src/locales/cs_CZ.js' {
  declare module.exports: $Exports<'uppy/src/locales/cs_CZ'>;
}
declare module 'uppy/src/locales/de_DE.js' {
  declare module.exports: $Exports<'uppy/src/locales/de_DE'>;
}
declare module 'uppy/src/locales/en_US.js' {
  declare module.exports: $Exports<'uppy/src/locales/en_US'>;
}
declare module 'uppy/src/locales/es_ES.js' {
  declare module.exports: $Exports<'uppy/src/locales/es_ES'>;
}
declare module 'uppy/src/locales/fi_FI.js' {
  declare module.exports: $Exports<'uppy/src/locales/fi_FI'>;
}
declare module 'uppy/src/locales/id_ID.js' {
  declare module.exports: $Exports<'uppy/src/locales/id_ID'>;
}
declare module 'uppy/src/locales/it_IT.js' {
  declare module.exports: $Exports<'uppy/src/locales/it_IT'>;
}
declare module 'uppy/src/locales/nb_NO.js' {
  declare module.exports: $Exports<'uppy/src/locales/nb_NO'>;
}
declare module 'uppy/src/locales/pl_PL.js' {
  declare module.exports: $Exports<'uppy/src/locales/pl_PL'>;
}
declare module 'uppy/src/locales/pt_BR.js' {
  declare module.exports: $Exports<'uppy/src/locales/pt_BR'>;
}
declare module 'uppy/src/locales/ru_RU.js' {
  declare module.exports: $Exports<'uppy/src/locales/ru_RU'>;
}
declare module 'uppy/src/locales/tr_TR.js' {
  declare module.exports: $Exports<'uppy/src/locales/tr_TR'>;
}
declare module 'uppy/src/locales/zh_CN.js' {
  declare module.exports: $Exports<'uppy/src/locales/zh_CN'>;
}
declare module 'uppy/src/plugins/AwsS3/index.js' {
  declare module.exports: $Exports<'uppy/src/plugins/AwsS3/index'>;
}
declare module 'uppy/src/plugins/Dashboard/ActionBrowseTagline.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Dashboard/ActionBrowseTagline'>;
}
declare module 'uppy/src/plugins/Dashboard/Dashboard.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Dashboard/Dashboard'>;
}
declare module 'uppy/src/plugins/Dashboard/FileCard.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Dashboard/FileCard'>;
}
declare module 'uppy/src/plugins/Dashboard/FileItem.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Dashboard/FileItem'>;
}
declare module 'uppy/src/plugins/Dashboard/FileItemProgress.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Dashboard/FileItemProgress'>;
}
declare module 'uppy/src/plugins/Dashboard/FileList.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Dashboard/FileList'>;
}
declare module 'uppy/src/plugins/Dashboard/getFileTypeIcon.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Dashboard/getFileTypeIcon'>;
}
declare module 'uppy/src/plugins/Dashboard/icons.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Dashboard/icons'>;
}
declare module 'uppy/src/plugins/Dashboard/index.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Dashboard/index'>;
}
declare module 'uppy/src/plugins/Dashboard/Tabs.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Dashboard/Tabs'>;
}
declare module 'uppy/src/plugins/DragDrop/index.js' {
  declare module.exports: $Exports<'uppy/src/plugins/DragDrop/index'>;
}
declare module 'uppy/src/plugins/Dropbox/icons.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Dropbox/icons'>;
}
declare module 'uppy/src/plugins/Dropbox/index.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Dropbox/index'>;
}
declare module 'uppy/src/plugins/Dummy.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Dummy'>;
}
declare module 'uppy/src/plugins/FileInput.js' {
  declare module.exports: $Exports<'uppy/src/plugins/FileInput'>;
}
declare module 'uppy/src/plugins/Form.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Form'>;
}
declare module 'uppy/src/plugins/GoldenRetriever/cleanup.js' {
  declare module.exports: $Exports<'uppy/src/plugins/GoldenRetriever/cleanup'>;
}
declare module 'uppy/src/plugins/GoldenRetriever/index.js' {
  declare module.exports: $Exports<'uppy/src/plugins/GoldenRetriever/index'>;
}
declare module 'uppy/src/plugins/GoldenRetriever/IndexedDBStore.js' {
  declare module.exports: $Exports<'uppy/src/plugins/GoldenRetriever/IndexedDBStore'>;
}
declare module 'uppy/src/plugins/GoldenRetriever/MetaDataStore.js' {
  declare module.exports: $Exports<'uppy/src/plugins/GoldenRetriever/MetaDataStore'>;
}
declare module 'uppy/src/plugins/GoldenRetriever/ServiceWorker.js' {
  declare module.exports: $Exports<'uppy/src/plugins/GoldenRetriever/ServiceWorker'>;
}
declare module 'uppy/src/plugins/GoldenRetriever/ServiceWorkerStore.js' {
  declare module.exports: $Exports<'uppy/src/plugins/GoldenRetriever/ServiceWorkerStore'>;
}
declare module 'uppy/src/plugins/GoogleDrive/index.js' {
  declare module.exports: $Exports<'uppy/src/plugins/GoogleDrive/index'>;
}
declare module 'uppy/src/plugins/Informer.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Informer'>;
}
declare module 'uppy/src/plugins/Instagram/index.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Instagram/index'>;
}
declare module 'uppy/src/plugins/MagicLog.js' {
  declare module.exports: $Exports<'uppy/src/plugins/MagicLog'>;
}
declare module 'uppy/src/plugins/ProgressBar.js' {
  declare module.exports: $Exports<'uppy/src/plugins/ProgressBar'>;
}
declare module 'uppy/src/plugins/Provider/index.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Provider/index'>;
}
declare module 'uppy/src/plugins/Provider/view/AuthView.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Provider/view/AuthView'>;
}
declare module 'uppy/src/plugins/Provider/view/Breadcrumb.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Provider/view/Breadcrumb'>;
}
declare module 'uppy/src/plugins/Provider/view/Breadcrumbs.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Provider/view/Breadcrumbs'>;
}
declare module 'uppy/src/plugins/Provider/view/Browser.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Provider/view/Browser'>;
}
declare module 'uppy/src/plugins/Provider/view/Filter.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Provider/view/Filter'>;
}
declare module 'uppy/src/plugins/Provider/view/index.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Provider/view/index'>;
}
declare module 'uppy/src/plugins/Provider/view/Loader.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Provider/view/Loader'>;
}
declare module 'uppy/src/plugins/Provider/view/Table.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Provider/view/Table'>;
}
declare module 'uppy/src/plugins/Provider/view/TableRow.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Provider/view/TableRow'>;
}
declare module 'uppy/src/plugins/Redux.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Redux'>;
}
declare module 'uppy/src/plugins/Redux.test.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Redux.test'>;
}
declare module 'uppy/src/plugins/ReduxDevTools.js' {
  declare module.exports: $Exports<'uppy/src/plugins/ReduxDevTools'>;
}
declare module 'uppy/src/plugins/StatusBar/index.js' {
  declare module.exports: $Exports<'uppy/src/plugins/StatusBar/index'>;
}
declare module 'uppy/src/plugins/StatusBar/StatusBar.js' {
  declare module.exports: $Exports<'uppy/src/plugins/StatusBar/StatusBar'>;
}
declare module 'uppy/src/plugins/ThumbnailGenerator/index.js' {
  declare module.exports: $Exports<'uppy/src/plugins/ThumbnailGenerator/index'>;
}
declare module 'uppy/src/plugins/ThumbnailGenerator/index.test.js' {
  declare module.exports: $Exports<'uppy/src/plugins/ThumbnailGenerator/index.test'>;
}
declare module 'uppy/src/plugins/Transloadit/Client.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Transloadit/Client'>;
}
declare module 'uppy/src/plugins/Transloadit/index.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Transloadit/index'>;
}
declare module 'uppy/src/plugins/Transloadit/index.test.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Transloadit/index.test'>;
}
declare module 'uppy/src/plugins/Transloadit/Socket.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Transloadit/Socket'>;
}
declare module 'uppy/src/plugins/Tus.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Tus'>;
}
declare module 'uppy/src/plugins/Url/index.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Url/index'>;
}
declare module 'uppy/src/plugins/Url/UrlUI.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Url/UrlUI'>;
}
declare module 'uppy/src/plugins/Webcam/CameraIcon.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Webcam/CameraIcon'>;
}
declare module 'uppy/src/plugins/Webcam/CameraScreen.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Webcam/CameraScreen'>;
}
declare module 'uppy/src/plugins/Webcam/index.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Webcam/index'>;
}
declare module 'uppy/src/plugins/Webcam/PermissionsScreen.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Webcam/PermissionsScreen'>;
}
declare module 'uppy/src/plugins/Webcam/RecordButton.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Webcam/RecordButton'>;
}
declare module 'uppy/src/plugins/Webcam/RecordStartIcon.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Webcam/RecordStartIcon'>;
}
declare module 'uppy/src/plugins/Webcam/RecordStopIcon.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Webcam/RecordStopIcon'>;
}
declare module 'uppy/src/plugins/Webcam/SnapshotButton.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Webcam/SnapshotButton'>;
}
declare module 'uppy/src/plugins/Webcam/supportsMediaRecorder.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Webcam/supportsMediaRecorder'>;
}
declare module 'uppy/src/plugins/Webcam/supportsMediaRecorder.test.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Webcam/supportsMediaRecorder.test'>;
}
declare module 'uppy/src/plugins/Webcam/WebcamIcon.js' {
  declare module.exports: $Exports<'uppy/src/plugins/Webcam/WebcamIcon'>;
}
declare module 'uppy/src/plugins/XHRUpload.js' {
  declare module.exports: $Exports<'uppy/src/plugins/XHRUpload'>;
}
declare module 'uppy/src/react/Dashboard.js' {
  declare module.exports: $Exports<'uppy/src/react/Dashboard'>;
}
declare module 'uppy/src/react/DashboardModal.js' {
  declare module.exports: $Exports<'uppy/src/react/DashboardModal'>;
}
declare module 'uppy/src/react/DragDrop.js' {
  declare module.exports: $Exports<'uppy/src/react/DragDrop'>;
}
declare module 'uppy/src/react/index.js' {
  declare module.exports: $Exports<'uppy/src/react/index'>;
}
declare module 'uppy/src/react/ProgressBar.js' {
  declare module.exports: $Exports<'uppy/src/react/ProgressBar'>;
}
declare module 'uppy/src/react/StatusBar.js' {
  declare module.exports: $Exports<'uppy/src/react/StatusBar'>;
}
declare module 'uppy/src/react/Wrapper.js' {
  declare module.exports: $Exports<'uppy/src/react/Wrapper'>;
}
declare module 'uppy/src/store/DefaultStore.js' {
  declare module.exports: $Exports<'uppy/src/store/DefaultStore'>;
}
declare module 'uppy/src/store/DefaultStore.test.js' {
  declare module.exports: $Exports<'uppy/src/store/DefaultStore.test'>;
}
declare module 'uppy/src/store/ReduxStore.js' {
  declare module.exports: $Exports<'uppy/src/store/ReduxStore'>;
}
declare module 'uppy/src/store/ReduxStore.test.js' {
  declare module.exports: $Exports<'uppy/src/store/ReduxStore.test'>;
}
declare module 'uppy/src/vendor/file-type/index.js' {
  declare module.exports: $Exports<'uppy/src/vendor/file-type/index'>;
}
