// flow-typed signature: 59fb4cfd1e03414bd134126c383392e8
// flow-typed version: <<STUB>>/urlencode_v^1.1.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'urlencode'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'urlencode' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'urlencode/lib/urlencode' {
  declare module.exports: any;
}

// Filename aliases
declare module 'urlencode/lib/urlencode.js' {
  declare module.exports: $Exports<'urlencode/lib/urlencode'>;
}
