// flow-typed signature: 748c22b03c163c8593e03ac9bae91177
// flow-typed version: <<STUB>>/wgs84-util_v3.0.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wgs84-util'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wgs84-util' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wgs84-util/dist/bundle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wgs84-util/dist/bundle.js' {
  declare module.exports: $Exports<'wgs84-util/dist/bundle'>;
}
declare module 'wgs84-util/index' {
  declare module.exports: $Exports<'wgs84-util'>;
}
declare module 'wgs84-util/index.js' {
  declare module.exports: $Exports<'wgs84-util'>;
}
