// flow-typed signature: c38af04aa956818ddc56d89fe30f16a6
// flow-typed version: <<STUB>>/winston-loggly_v1.3.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'winston-loggly'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'winston-loggly' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'winston-loggly/lib/winston-loggly' {
  declare module.exports: any;
}

declare module 'winston-loggly/test/winston-loggly-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'winston-loggly/lib/winston-loggly.js' {
  declare module.exports: $Exports<'winston-loggly/lib/winston-loggly'>;
}
declare module 'winston-loggly/test/winston-loggly-test.js' {
  declare module.exports: $Exports<'winston-loggly/test/winston-loggly-test'>;
}
