// flow-typed signature: 2bba2e2fa29112dd5823b45586d5303a
// flow-typed version: <<STUB>>/xcomponent_v^6.0.49/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xcomponent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xcomponent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xcomponent/dist/xcomponent.frame' {
  declare module.exports: any;
}

declare module 'xcomponent/dist/xcomponent.frame.min' {
  declare module.exports: any;
}

declare module 'xcomponent/dist/xcomponent' {
  declare module.exports: any;
}

declare module 'xcomponent/dist/xcomponent.min' {
  declare module.exports: any;
}

declare module 'xcomponent/postinstall' {
  declare module.exports: any;
}

declare module 'xcomponent/src/component/base' {
  declare module.exports: any;
}

declare module 'xcomponent/src/component/child/index' {
  declare module.exports: any;
}

declare module 'xcomponent/src/component/child/props' {
  declare module.exports: any;
}

declare module 'xcomponent/src/component/child/validate' {
  declare module.exports: any;
}

declare module 'xcomponent/src/component/component/index' {
  declare module.exports: any;
}

declare module 'xcomponent/src/component/component/props' {
  declare module.exports: any;
}

declare module 'xcomponent/src/component/component/templates/component' {
  declare module.exports: any;
}

declare module 'xcomponent/src/component/component/templates/container' {
  declare module.exports: any;
}

declare module 'xcomponent/src/component/component/templates/index' {
  declare module.exports: any;
}

declare module 'xcomponent/src/component/component/validate' {
  declare module.exports: any;
}

declare module 'xcomponent/src/component/delegate/index' {
  declare module.exports: any;
}

declare module 'xcomponent/src/component/index' {
  declare module.exports: any;
}

declare module 'xcomponent/src/component/parent/drivers' {
  declare module.exports: any;
}

declare module 'xcomponent/src/component/parent/index' {
  declare module.exports: any;
}

declare module 'xcomponent/src/component/parent/props' {
  declare module.exports: any;
}

declare module 'xcomponent/src/component/parent/validate' {
  declare module.exports: any;
}

declare module 'xcomponent/src/component/window' {
  declare module.exports: any;
}

declare module 'xcomponent/src/constants' {
  declare module.exports: any;
}

declare module 'xcomponent/src/drivers/angular' {
  declare module.exports: any;
}

declare module 'xcomponent/src/drivers/angular2' {
  declare module.exports: any;
}

declare module 'xcomponent/src/drivers/ember' {
  declare module.exports: any;
}

declare module 'xcomponent/src/drivers/glimmer' {
  declare module.exports: any;
}

declare module 'xcomponent/src/drivers/index' {
  declare module.exports: any;
}

declare module 'xcomponent/src/drivers/react' {
  declare module.exports: any;
}

declare module 'xcomponent/src/drivers/script' {
  declare module.exports: any;
}

declare module 'xcomponent/src/drivers/vue' {
  declare module.exports: any;
}

declare module 'xcomponent/src/error' {
  declare module.exports: any;
}

declare module 'xcomponent/src/index' {
  declare module.exports: any;
}

declare module 'xcomponent/src/interface' {
  declare module.exports: any;
}

declare module 'xcomponent/src/lib/css' {
  declare module.exports: any;
}

declare module 'xcomponent/src/lib/decorators' {
  declare module.exports: any;
}

declare module 'xcomponent/src/lib/dom' {
  declare module.exports: any;
}

declare module 'xcomponent/src/lib/fn' {
  declare module.exports: any;
}

declare module 'xcomponent/src/lib/global' {
  declare module.exports: any;
}

declare module 'xcomponent/src/lib/index' {
  declare module.exports: any;
}

declare module 'xcomponent/src/lib/logger' {
  declare module.exports: any;
}

declare module 'xcomponent/src/lib/promise' {
  declare module.exports: any;
}

declare module 'xcomponent/src/lib/util' {
  declare module.exports: any;
}

declare module 'xcomponent/src/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xcomponent/dist/xcomponent.frame.js' {
  declare module.exports: $Exports<'xcomponent/dist/xcomponent.frame'>;
}
declare module 'xcomponent/dist/xcomponent.frame.min.js' {
  declare module.exports: $Exports<'xcomponent/dist/xcomponent.frame.min'>;
}
declare module 'xcomponent/dist/xcomponent.js' {
  declare module.exports: $Exports<'xcomponent/dist/xcomponent'>;
}
declare module 'xcomponent/dist/xcomponent.min.js' {
  declare module.exports: $Exports<'xcomponent/dist/xcomponent.min'>;
}
declare module 'xcomponent/index' {
  declare module.exports: $Exports<'xcomponent'>;
}
declare module 'xcomponent/index.js' {
  declare module.exports: $Exports<'xcomponent'>;
}
declare module 'xcomponent/postinstall.js' {
  declare module.exports: $Exports<'xcomponent/postinstall'>;
}
declare module 'xcomponent/src/component/base.js' {
  declare module.exports: $Exports<'xcomponent/src/component/base'>;
}
declare module 'xcomponent/src/component/child/index.js' {
  declare module.exports: $Exports<'xcomponent/src/component/child/index'>;
}
declare module 'xcomponent/src/component/child/props.js' {
  declare module.exports: $Exports<'xcomponent/src/component/child/props'>;
}
declare module 'xcomponent/src/component/child/validate.js' {
  declare module.exports: $Exports<'xcomponent/src/component/child/validate'>;
}
declare module 'xcomponent/src/component/component/index.js' {
  declare module.exports: $Exports<'xcomponent/src/component/component/index'>;
}
declare module 'xcomponent/src/component/component/props.js' {
  declare module.exports: $Exports<'xcomponent/src/component/component/props'>;
}
declare module 'xcomponent/src/component/component/templates/component.jsx' {
  declare module.exports: $Exports<'xcomponent/src/component/component/templates/component'>;
}
declare module 'xcomponent/src/component/component/templates/container.jsx' {
  declare module.exports: $Exports<'xcomponent/src/component/component/templates/container'>;
}
declare module 'xcomponent/src/component/component/templates/index.js' {
  declare module.exports: $Exports<'xcomponent/src/component/component/templates/index'>;
}
declare module 'xcomponent/src/component/component/validate.js' {
  declare module.exports: $Exports<'xcomponent/src/component/component/validate'>;
}
declare module 'xcomponent/src/component/delegate/index.js' {
  declare module.exports: $Exports<'xcomponent/src/component/delegate/index'>;
}
declare module 'xcomponent/src/component/index.js' {
  declare module.exports: $Exports<'xcomponent/src/component/index'>;
}
declare module 'xcomponent/src/component/parent/drivers.js' {
  declare module.exports: $Exports<'xcomponent/src/component/parent/drivers'>;
}
declare module 'xcomponent/src/component/parent/index.js' {
  declare module.exports: $Exports<'xcomponent/src/component/parent/index'>;
}
declare module 'xcomponent/src/component/parent/props.js' {
  declare module.exports: $Exports<'xcomponent/src/component/parent/props'>;
}
declare module 'xcomponent/src/component/parent/validate.js' {
  declare module.exports: $Exports<'xcomponent/src/component/parent/validate'>;
}
declare module 'xcomponent/src/component/window.js' {
  declare module.exports: $Exports<'xcomponent/src/component/window'>;
}
declare module 'xcomponent/src/constants.js' {
  declare module.exports: $Exports<'xcomponent/src/constants'>;
}
declare module 'xcomponent/src/drivers/angular.js' {
  declare module.exports: $Exports<'xcomponent/src/drivers/angular'>;
}
declare module 'xcomponent/src/drivers/angular2.js' {
  declare module.exports: $Exports<'xcomponent/src/drivers/angular2'>;
}
declare module 'xcomponent/src/drivers/ember.js' {
  declare module.exports: $Exports<'xcomponent/src/drivers/ember'>;
}
declare module 'xcomponent/src/drivers/glimmer.js' {
  declare module.exports: $Exports<'xcomponent/src/drivers/glimmer'>;
}
declare module 'xcomponent/src/drivers/index.js' {
  declare module.exports: $Exports<'xcomponent/src/drivers/index'>;
}
declare module 'xcomponent/src/drivers/react.js' {
  declare module.exports: $Exports<'xcomponent/src/drivers/react'>;
}
declare module 'xcomponent/src/drivers/script.js' {
  declare module.exports: $Exports<'xcomponent/src/drivers/script'>;
}
declare module 'xcomponent/src/drivers/vue.js' {
  declare module.exports: $Exports<'xcomponent/src/drivers/vue'>;
}
declare module 'xcomponent/src/error.js' {
  declare module.exports: $Exports<'xcomponent/src/error'>;
}
declare module 'xcomponent/src/index.js' {
  declare module.exports: $Exports<'xcomponent/src/index'>;
}
declare module 'xcomponent/src/interface.js' {
  declare module.exports: $Exports<'xcomponent/src/interface'>;
}
declare module 'xcomponent/src/lib/css.js' {
  declare module.exports: $Exports<'xcomponent/src/lib/css'>;
}
declare module 'xcomponent/src/lib/decorators.js' {
  declare module.exports: $Exports<'xcomponent/src/lib/decorators'>;
}
declare module 'xcomponent/src/lib/dom.js' {
  declare module.exports: $Exports<'xcomponent/src/lib/dom'>;
}
declare module 'xcomponent/src/lib/fn.js' {
  declare module.exports: $Exports<'xcomponent/src/lib/fn'>;
}
declare module 'xcomponent/src/lib/global.js' {
  declare module.exports: $Exports<'xcomponent/src/lib/global'>;
}
declare module 'xcomponent/src/lib/index.js' {
  declare module.exports: $Exports<'xcomponent/src/lib/index'>;
}
declare module 'xcomponent/src/lib/logger.js' {
  declare module.exports: $Exports<'xcomponent/src/lib/logger'>;
}
declare module 'xcomponent/src/lib/promise.js' {
  declare module.exports: $Exports<'xcomponent/src/lib/promise'>;
}
declare module 'xcomponent/src/lib/util.js' {
  declare module.exports: $Exports<'xcomponent/src/lib/util'>;
}
declare module 'xcomponent/src/types.js' {
  declare module.exports: $Exports<'xcomponent/src/types'>;
}
