#!/bin/sh

export PGUSER=postgres
psql <<- EOSQL
    CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASS}' SUPERUSER;
    CREATE DATABASE ${DB_DATABASE} OWNER ${DB_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${DB_DATABASE} TO ${DB_USER};
EOSQL

psql -d ${DB_DATABASE} <<- EOSQL
    CREATE EXTENSION postgis;
    CREATE EXTENSION hstore;
EOSQL
