// flow-typed signature: 000a03a5130e1a0f1f1066f62a2c378f
// flow-typed version: <<STUB>>/@mapbox/mapbox-gl-draw_v1.0.6/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mapbox/mapbox-gl-draw'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mapbox/mapbox-gl-draw' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mapbox/mapbox-gl-draw/bench/index' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/lib/format_number' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/lib/fps' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/lib/mouse_drag' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/lib/mouse_draw' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/lib/mouse_events' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/lib/mouse_path' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/lib/mouse_trace' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/lib/trace_progress' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/dist/mapbox-gl-draw' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/server' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/api' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/constants' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/events' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/feature_types/feature' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/feature_types/line_string' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/feature_types/multi_feature' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/feature_types/point' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/feature_types/polygon' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/common_selectors' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/constrain_feature_movement' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/create_midpoint' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/create_supplementary_points' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/create_vertex' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/double_click_zoom' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/euclidean_distance' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/features_at' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/get_features_and_set_cursor' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/is_click' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/is_event_at_coordinates' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/is_tap' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/map_event_to_bounding_box' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/mode_handler' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/mouse_event_point' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/move_features' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/sort_features' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/string_set' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/string_sets_are_equal' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/theme' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/throttle' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/to_dense_array' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/modes/direct_select' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/modes/draw_line_string' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/modes/draw_point' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/modes/draw_polygon' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/modes/index' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/modes/mode_interface_accessors' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/modes/mode_interface' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/modes/object_to_mode' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/modes/simple_select' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/options' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/render' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/setup' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/store' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/ui' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mapbox/mapbox-gl-draw/bench/index.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/index'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/lib/format_number.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/lib/format_number'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/lib/fps.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/lib/fps'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/lib/mouse_drag.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/lib/mouse_drag'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/lib/mouse_draw.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/lib/mouse_draw'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/lib/mouse_events.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/lib/mouse_events'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/lib/mouse_path.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/lib/mouse_path'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/lib/mouse_trace.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/lib/mouse_trace'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/lib/trace_progress.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/lib/trace_progress'>;
}
declare module '@mapbox/mapbox-gl-draw/dist/mapbox-gl-draw.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/dist/mapbox-gl-draw'>;
}
declare module '@mapbox/mapbox-gl-draw/index' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw'>;
}
declare module '@mapbox/mapbox-gl-draw/index.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw'>;
}
declare module '@mapbox/mapbox-gl-draw/server.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/server'>;
}
declare module '@mapbox/mapbox-gl-draw/src/api.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/api'>;
}
declare module '@mapbox/mapbox-gl-draw/src/constants.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/constants'>;
}
declare module '@mapbox/mapbox-gl-draw/src/events.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/events'>;
}
declare module '@mapbox/mapbox-gl-draw/src/feature_types/feature.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/feature_types/feature'>;
}
declare module '@mapbox/mapbox-gl-draw/src/feature_types/line_string.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/feature_types/line_string'>;
}
declare module '@mapbox/mapbox-gl-draw/src/feature_types/multi_feature.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/feature_types/multi_feature'>;
}
declare module '@mapbox/mapbox-gl-draw/src/feature_types/point.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/feature_types/point'>;
}
declare module '@mapbox/mapbox-gl-draw/src/feature_types/polygon.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/feature_types/polygon'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/common_selectors.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/common_selectors'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/constrain_feature_movement.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/constrain_feature_movement'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/create_midpoint.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/create_midpoint'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/create_supplementary_points.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/create_supplementary_points'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/create_vertex.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/create_vertex'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/double_click_zoom.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/double_click_zoom'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/euclidean_distance.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/euclidean_distance'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/features_at.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/features_at'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/get_features_and_set_cursor.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/get_features_and_set_cursor'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/is_click.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/is_click'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/is_event_at_coordinates.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/is_event_at_coordinates'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/is_tap.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/is_tap'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/map_event_to_bounding_box.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/map_event_to_bounding_box'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/mode_handler.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/mode_handler'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/mouse_event_point.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/mouse_event_point'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/move_features.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/move_features'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/sort_features.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/sort_features'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/string_set.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/string_set'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/string_sets_are_equal.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/string_sets_are_equal'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/theme.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/theme'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/throttle.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/throttle'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/to_dense_array.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/to_dense_array'>;
}
declare module '@mapbox/mapbox-gl-draw/src/modes/direct_select.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/modes/direct_select'>;
}
declare module '@mapbox/mapbox-gl-draw/src/modes/draw_line_string.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/modes/draw_line_string'>;
}
declare module '@mapbox/mapbox-gl-draw/src/modes/draw_point.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/modes/draw_point'>;
}
declare module '@mapbox/mapbox-gl-draw/src/modes/draw_polygon.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/modes/draw_polygon'>;
}
declare module '@mapbox/mapbox-gl-draw/src/modes/index.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/modes/index'>;
}
declare module '@mapbox/mapbox-gl-draw/src/modes/mode_interface_accessors.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/modes/mode_interface_accessors'>;
}
declare module '@mapbox/mapbox-gl-draw/src/modes/mode_interface.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/modes/mode_interface'>;
}
declare module '@mapbox/mapbox-gl-draw/src/modes/object_to_mode.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/modes/object_to_mode'>;
}
declare module '@mapbox/mapbox-gl-draw/src/modes/simple_select.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/modes/simple_select'>;
}
declare module '@mapbox/mapbox-gl-draw/src/options.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/options'>;
}
declare module '@mapbox/mapbox-gl-draw/src/render.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/render'>;
}
declare module '@mapbox/mapbox-gl-draw/src/setup.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/setup'>;
}
declare module '@mapbox/mapbox-gl-draw/src/store.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/store'>;
}
declare module '@mapbox/mapbox-gl-draw/src/ui.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/ui'>;
}
