// flow-typed signature: 4c01a1331f1a616ca43d62a2eaea27a5
// flow-typed version: <<STUB>>/@mapbox/mapbox-gl-draw_v^0.19.1/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mapbox/mapbox-gl-draw'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mapbox/mapbox-gl-draw' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mapbox/mapbox-gl-draw/bench/index' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/lib/format_number' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/lib/fps' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/lib/mouse_drag' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/lib/mouse_draw' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/lib/mouse_events' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/lib/mouse_path' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/lib/mouse_trace' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/lib/trace_progress' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/tests/direct_select_large_zoomed' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/tests/direct_select_large' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/tests/direct_select_small_zoomed' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/tests/direct_select_small' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/tests/draw_land_polygon_large' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/tests/draw_land_polygon_small' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/tests/draw_line_string_large_zoomed' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/tests/draw_line_string_large' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/tests/draw_line_string_small' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/tests/draw_point_large_zoomed' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/tests/draw_point_large' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/tests/draw_point_small' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/tests/draw_polygon_large_zoomed' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/tests/draw_polygon_large' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/tests/draw_polygon_small' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/tests/draw_urban_areas_polygon_large' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/tests/draw_urban_areas_polygon_small' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/tests/simple_select_large_two_maps' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/tests/simple_select_large_zoomed' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/tests/simple_select_large' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/bench/tests/simple_select_small' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/coverage/prettify' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/coverage/sorter' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/dist/mapbox-gl-draw' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/server' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/api' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/constants' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/events' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/feature_types/feature' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/feature_types/line_string' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/feature_types/multi_feature' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/feature_types/point' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/feature_types/polygon' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/common_selectors' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/constrain_feature_movement' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/create_midpoint' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/create_supplementary_points' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/create_vertex' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/double_click_zoom' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/euclidean_distance' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/features_at' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/get_features_and_set_cursor' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/is_click' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/is_event_at_coordinates' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/is_tap' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/map_event_to_bounding_box' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/mode_handler' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/mouse_event_point' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/move_features' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/sort_features' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/string_set' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/string_sets_are_equal' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/theme' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/throttle' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/lib/to_dense_array' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/modes/direct_select' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/modes/draw_line_string' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/modes/draw_point' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/modes/draw_polygon' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/modes/simple_select' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/modes/static' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/options' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/render' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/setup' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/store' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/src/ui' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/api.test' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/common_selectors.test' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/constrain_feature_movement.test' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/create_supplementary_points.test' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/create_vertex.test' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/direct_select.test' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/draw_line_string.test' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/draw_point.test' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/draw_polygon.test' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/euclidean_distance.test' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/feature.test' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/features_at.test' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/interaction_events.test' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/is_click.test' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/is_event_at_coordinates.test' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/is_tap.test' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/line_string.test' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/map_event_to_bounding_box.test' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/mock-browser' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/mode_handler.test' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/mouse_event_point.test' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/move_features.test' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/multi_feature.test' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/options.test' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/point.test' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/polygon.test' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/simple_select.test' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/sort_features.test' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/static.test' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/store.test' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/string_set.test' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/ui.test' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/utils/after_next_render' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/utils/create_feature' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/utils/create_map' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/utils/create_mock_draw_mode_context' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/utils/create_mock_feature_context' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/utils/create_mock_lifecycle_context' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/utils/create_mock_mode_handler_context' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/utils/create_mock_mode' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/utils/draw_geometry' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/utils/get_geojson' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/utils/get_public_member_keys' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/utils/key_events' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/utils/make_mouse_event' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/utils/make_touch_event' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/utils/mouse_click' {
  declare module.exports: any;
}

declare module '@mapbox/mapbox-gl-draw/test/utils/touch_tap' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mapbox/mapbox-gl-draw/bench/index.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/index'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/lib/format_number.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/lib/format_number'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/lib/fps.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/lib/fps'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/lib/mouse_drag.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/lib/mouse_drag'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/lib/mouse_draw.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/lib/mouse_draw'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/lib/mouse_events.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/lib/mouse_events'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/lib/mouse_path.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/lib/mouse_path'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/lib/mouse_trace.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/lib/mouse_trace'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/lib/trace_progress.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/lib/trace_progress'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/tests/direct_select_large_zoomed.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/tests/direct_select_large_zoomed'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/tests/direct_select_large.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/tests/direct_select_large'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/tests/direct_select_small_zoomed.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/tests/direct_select_small_zoomed'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/tests/direct_select_small.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/tests/direct_select_small'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/tests/draw_land_polygon_large.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/tests/draw_land_polygon_large'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/tests/draw_land_polygon_small.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/tests/draw_land_polygon_small'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/tests/draw_line_string_large_zoomed.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/tests/draw_line_string_large_zoomed'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/tests/draw_line_string_large.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/tests/draw_line_string_large'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/tests/draw_line_string_small.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/tests/draw_line_string_small'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/tests/draw_point_large_zoomed.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/tests/draw_point_large_zoomed'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/tests/draw_point_large.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/tests/draw_point_large'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/tests/draw_point_small.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/tests/draw_point_small'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/tests/draw_polygon_large_zoomed.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/tests/draw_polygon_large_zoomed'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/tests/draw_polygon_large.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/tests/draw_polygon_large'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/tests/draw_polygon_small.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/tests/draw_polygon_small'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/tests/draw_urban_areas_polygon_large.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/tests/draw_urban_areas_polygon_large'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/tests/draw_urban_areas_polygon_small.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/tests/draw_urban_areas_polygon_small'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/tests/simple_select_large_two_maps.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/tests/simple_select_large_two_maps'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/tests/simple_select_large_zoomed.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/tests/simple_select_large_zoomed'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/tests/simple_select_large.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/tests/simple_select_large'>;
}
declare module '@mapbox/mapbox-gl-draw/bench/tests/simple_select_small.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/bench/tests/simple_select_small'>;
}
declare module '@mapbox/mapbox-gl-draw/coverage/prettify.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/coverage/prettify'>;
}
declare module '@mapbox/mapbox-gl-draw/coverage/sorter.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/coverage/sorter'>;
}
declare module '@mapbox/mapbox-gl-draw/dist/mapbox-gl-draw.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/dist/mapbox-gl-draw'>;
}
declare module '@mapbox/mapbox-gl-draw/index' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw'>;
}
declare module '@mapbox/mapbox-gl-draw/index.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw'>;
}
declare module '@mapbox/mapbox-gl-draw/server.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/server'>;
}
declare module '@mapbox/mapbox-gl-draw/src/api.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/api'>;
}
declare module '@mapbox/mapbox-gl-draw/src/constants.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/constants'>;
}
declare module '@mapbox/mapbox-gl-draw/src/events.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/events'>;
}
declare module '@mapbox/mapbox-gl-draw/src/feature_types/feature.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/feature_types/feature'>;
}
declare module '@mapbox/mapbox-gl-draw/src/feature_types/line_string.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/feature_types/line_string'>;
}
declare module '@mapbox/mapbox-gl-draw/src/feature_types/multi_feature.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/feature_types/multi_feature'>;
}
declare module '@mapbox/mapbox-gl-draw/src/feature_types/point.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/feature_types/point'>;
}
declare module '@mapbox/mapbox-gl-draw/src/feature_types/polygon.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/feature_types/polygon'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/common_selectors.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/common_selectors'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/constrain_feature_movement.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/constrain_feature_movement'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/create_midpoint.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/create_midpoint'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/create_supplementary_points.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/create_supplementary_points'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/create_vertex.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/create_vertex'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/double_click_zoom.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/double_click_zoom'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/euclidean_distance.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/euclidean_distance'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/features_at.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/features_at'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/get_features_and_set_cursor.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/get_features_and_set_cursor'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/is_click.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/is_click'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/is_event_at_coordinates.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/is_event_at_coordinates'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/is_tap.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/is_tap'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/map_event_to_bounding_box.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/map_event_to_bounding_box'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/mode_handler.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/mode_handler'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/mouse_event_point.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/mouse_event_point'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/move_features.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/move_features'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/sort_features.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/sort_features'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/string_set.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/string_set'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/string_sets_are_equal.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/string_sets_are_equal'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/theme.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/theme'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/throttle.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/throttle'>;
}
declare module '@mapbox/mapbox-gl-draw/src/lib/to_dense_array.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/lib/to_dense_array'>;
}
declare module '@mapbox/mapbox-gl-draw/src/modes/direct_select.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/modes/direct_select'>;
}
declare module '@mapbox/mapbox-gl-draw/src/modes/draw_line_string.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/modes/draw_line_string'>;
}
declare module '@mapbox/mapbox-gl-draw/src/modes/draw_point.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/modes/draw_point'>;
}
declare module '@mapbox/mapbox-gl-draw/src/modes/draw_polygon.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/modes/draw_polygon'>;
}
declare module '@mapbox/mapbox-gl-draw/src/modes/simple_select.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/modes/simple_select'>;
}
declare module '@mapbox/mapbox-gl-draw/src/modes/static.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/modes/static'>;
}
declare module '@mapbox/mapbox-gl-draw/src/options.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/options'>;
}
declare module '@mapbox/mapbox-gl-draw/src/render.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/render'>;
}
declare module '@mapbox/mapbox-gl-draw/src/setup.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/setup'>;
}
declare module '@mapbox/mapbox-gl-draw/src/store.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/store'>;
}
declare module '@mapbox/mapbox-gl-draw/src/ui.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/src/ui'>;
}
declare module '@mapbox/mapbox-gl-draw/test/api.test.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/api.test'>;
}
declare module '@mapbox/mapbox-gl-draw/test/common_selectors.test.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/common_selectors.test'>;
}
declare module '@mapbox/mapbox-gl-draw/test/constrain_feature_movement.test.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/constrain_feature_movement.test'>;
}
declare module '@mapbox/mapbox-gl-draw/test/create_supplementary_points.test.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/create_supplementary_points.test'>;
}
declare module '@mapbox/mapbox-gl-draw/test/create_vertex.test.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/create_vertex.test'>;
}
declare module '@mapbox/mapbox-gl-draw/test/direct_select.test.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/direct_select.test'>;
}
declare module '@mapbox/mapbox-gl-draw/test/draw_line_string.test.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/draw_line_string.test'>;
}
declare module '@mapbox/mapbox-gl-draw/test/draw_point.test.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/draw_point.test'>;
}
declare module '@mapbox/mapbox-gl-draw/test/draw_polygon.test.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/draw_polygon.test'>;
}
declare module '@mapbox/mapbox-gl-draw/test/euclidean_distance.test.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/euclidean_distance.test'>;
}
declare module '@mapbox/mapbox-gl-draw/test/feature.test.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/feature.test'>;
}
declare module '@mapbox/mapbox-gl-draw/test/features_at.test.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/features_at.test'>;
}
declare module '@mapbox/mapbox-gl-draw/test/interaction_events.test.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/interaction_events.test'>;
}
declare module '@mapbox/mapbox-gl-draw/test/is_click.test.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/is_click.test'>;
}
declare module '@mapbox/mapbox-gl-draw/test/is_event_at_coordinates.test.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/is_event_at_coordinates.test'>;
}
declare module '@mapbox/mapbox-gl-draw/test/is_tap.test.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/is_tap.test'>;
}
declare module '@mapbox/mapbox-gl-draw/test/line_string.test.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/line_string.test'>;
}
declare module '@mapbox/mapbox-gl-draw/test/map_event_to_bounding_box.test.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/map_event_to_bounding_box.test'>;
}
declare module '@mapbox/mapbox-gl-draw/test/mock-browser.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/mock-browser'>;
}
declare module '@mapbox/mapbox-gl-draw/test/mode_handler.test.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/mode_handler.test'>;
}
declare module '@mapbox/mapbox-gl-draw/test/mouse_event_point.test.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/mouse_event_point.test'>;
}
declare module '@mapbox/mapbox-gl-draw/test/move_features.test.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/move_features.test'>;
}
declare module '@mapbox/mapbox-gl-draw/test/multi_feature.test.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/multi_feature.test'>;
}
declare module '@mapbox/mapbox-gl-draw/test/options.test.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/options.test'>;
}
declare module '@mapbox/mapbox-gl-draw/test/point.test.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/point.test'>;
}
declare module '@mapbox/mapbox-gl-draw/test/polygon.test.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/polygon.test'>;
}
declare module '@mapbox/mapbox-gl-draw/test/simple_select.test.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/simple_select.test'>;
}
declare module '@mapbox/mapbox-gl-draw/test/sort_features.test.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/sort_features.test'>;
}
declare module '@mapbox/mapbox-gl-draw/test/static.test.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/static.test'>;
}
declare module '@mapbox/mapbox-gl-draw/test/store.test.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/store.test'>;
}
declare module '@mapbox/mapbox-gl-draw/test/string_set.test.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/string_set.test'>;
}
declare module '@mapbox/mapbox-gl-draw/test/ui.test.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/ui.test'>;
}
declare module '@mapbox/mapbox-gl-draw/test/utils/after_next_render.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/utils/after_next_render'>;
}
declare module '@mapbox/mapbox-gl-draw/test/utils/create_feature.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/utils/create_feature'>;
}
declare module '@mapbox/mapbox-gl-draw/test/utils/create_map.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/utils/create_map'>;
}
declare module '@mapbox/mapbox-gl-draw/test/utils/create_mock_draw_mode_context.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/utils/create_mock_draw_mode_context'>;
}
declare module '@mapbox/mapbox-gl-draw/test/utils/create_mock_feature_context.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/utils/create_mock_feature_context'>;
}
declare module '@mapbox/mapbox-gl-draw/test/utils/create_mock_lifecycle_context.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/utils/create_mock_lifecycle_context'>;
}
declare module '@mapbox/mapbox-gl-draw/test/utils/create_mock_mode_handler_context.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/utils/create_mock_mode_handler_context'>;
}
declare module '@mapbox/mapbox-gl-draw/test/utils/create_mock_mode.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/utils/create_mock_mode'>;
}
declare module '@mapbox/mapbox-gl-draw/test/utils/draw_geometry.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/utils/draw_geometry'>;
}
declare module '@mapbox/mapbox-gl-draw/test/utils/get_geojson.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/utils/get_geojson'>;
}
declare module '@mapbox/mapbox-gl-draw/test/utils/get_public_member_keys.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/utils/get_public_member_keys'>;
}
declare module '@mapbox/mapbox-gl-draw/test/utils/key_events.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/utils/key_events'>;
}
declare module '@mapbox/mapbox-gl-draw/test/utils/make_mouse_event.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/utils/make_mouse_event'>;
}
declare module '@mapbox/mapbox-gl-draw/test/utils/make_touch_event.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/utils/make_touch_event'>;
}
declare module '@mapbox/mapbox-gl-draw/test/utils/mouse_click.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/utils/mouse_click'>;
}
declare module '@mapbox/mapbox-gl-draw/test/utils/touch_tap.js' {
  declare module.exports: $Exports<'@mapbox/mapbox-gl-draw/test/utils/touch_tap'>;
}
