// flow-typed signature: db2088b02a9cee874648459bd7060575
// flow-typed version: <<STUB>>/@mapbox/shapefile-fairy_vopenmaphub/shapefile-fairy#950cb59adfadc6cbbccac2d33f7bc23c2f2b713e/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mapbox/shapefile-fairy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mapbox/shapefile-fairy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mapbox/shapefile-fairy/bin/shapefile-fairy' {
  declare module.exports: any;
}

declare module '@mapbox/shapefile-fairy/test/fixtures/index' {
  declare module.exports: any;
}

declare module '@mapbox/shapefile-fairy/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mapbox/shapefile-fairy/bin/shapefile-fairy.js' {
  declare module.exports: $Exports<'@mapbox/shapefile-fairy/bin/shapefile-fairy'>;
}
declare module '@mapbox/shapefile-fairy/index' {
  declare module.exports: $Exports<'@mapbox/shapefile-fairy'>;
}
declare module '@mapbox/shapefile-fairy/index.js' {
  declare module.exports: $Exports<'@mapbox/shapefile-fairy'>;
}
declare module '@mapbox/shapefile-fairy/test/fixtures/index.js' {
  declare module.exports: $Exports<'@mapbox/shapefile-fairy/test/fixtures/index'>;
}
declare module '@mapbox/shapefile-fairy/test/index.js' {
  declare module.exports: $Exports<'@mapbox/shapefile-fairy/test/index'>;
}
